import { Sandbox } from '@vercel/sandbox';
import { mkdir, writeFile } from 'node:fs/promises';

const REPO_URL = process.env.BUILDER_REPO_URL || 'https://github.com/bikeztagram-ai/bikeztagram-ai-build-v2.git';
const BATCH_ID = process.env.BUILDER_BATCH_ID || `batch-${Date.now()}`;
const BRANCH = process.env.BUILDER_WORKING_BRANCH || `autonomous-builder/${BATCH_ID}`;
const BASE_BRANCH = process.env.BUILDER_BASE_BRANCH || 'main';
const MAX_MINUTES = Math.min(Number(process.env.BUILDER_MAX_MINUTES || 45), 45);
const MAX_PASSES = Math.min(Math.max(Number(process.env.BUILDER_MAX_PASSES || 8), 1), 8);
const SANDBOX_ROOT = '/vercel/sandbox';
const REPO_DIR = `${SANDBOX_ROOT}/repo`;
const ASKPASS_PATH = `${SANDBOX_ROOT}/git-askpass.sh`;
const AGENT_CMD = process.env.BUILDER_AGENT_CMD ? JSON.parse(process.env.BUILDER_AGENT_CMD) : ['npx', '-y', '@openai/codex', 'exec', '--model', 'gpt-5.3-codex', '--dangerously-bypass-approvals-and-sandbox'];
const OBJECTIVE = process.env.BUILDER_OBJECTIVE || 'Improve Bikeztagram based on the highest-impact product weakness found in the repository.';
const ACCEPTANCE = (process.env.BUILDER_ACCEPTANCE || 'Real product behaviour improves.;Build and relevant verification commands pass.;No automatic merge to main.;No Gemini usage.')
  .split(';').map((x) => x.trim()).filter(Boolean);
const VERIFY_COMMANDS = (process.env.BUILDER_VERIFY_COMMANDS || 'npm run build').split(',').map((x) => x.trim()).filter(Boolean);
const PROTECTED_PATHS = ['.github/workflows/'];
const safeBranch = (value) => value && value !== 'main' && value !== 'master' && !value.startsWith('production/');
const results = [];
async function command(sandbox, cmd, args = [], cwd = REPO_DIR, env) { const r = await sandbox.runCommand({ cmd, args, cwd, ...(env ? { env } : {}) }); const result = { command:[cmd,...args].join(' '), exitCode:r.exitCode, stdout:await r.stdout(), stderr:await r.stderr() }; results.push(result); return result; }
const compact = (text, limit=6000) => { const value=String(text||'').trim(); return value.length<=limit?value:`${value.slice(0,limit)}\n...[truncated]`; };
async function verify(sandbox) { const failures=[]; const diff=await command(sandbox,'git',['diff','--check']); if(diff.exitCode) failures.push(`git diff --check failed: ${compact(diff.stderr||diff.stdout)}`); for(const spec of VERIFY_COMMANDS){const [cmd,...args]=spec.split(/\s+/);const r=await command(sandbox,cmd,args);if(r.exitCode) failures.push(`${spec} failed (exit ${r.exitCode})\n${compact(r.stderr||r.stdout)}`);} return failures; }
async function resetProtected(sandbox){ for(const p of PROTECTED_PATHS){ const r=await command(sandbox,'git',['status','--short','--',p]); if(r.exitCode) throw new Error(r.stderr); if(r.stdout.trim()){ const restore=await command(sandbox,'git',['restore','--source=HEAD','--staged','--worktree','--',p]); if(restore.exitCode) throw new Error(`protected path restore failed: ${restore.stderr}`); } } }
async function publish(sandbox,gitEnv){ await command(sandbox,'git',['config','user.name','Bikeztagram Autonomous Builder']); await command(sandbox,'git',['config','user.email','41898282+github-actions[bot]@users.noreply.github.com']); const add=await command(sandbox,'git',['add','-A']);if(add.exitCode)throw new Error(add.stderr);const commit=await command(sandbox,'git',['commit','-m',`builder: complete ${BATCH_ID}`]);if(commit.exitCode)throw new Error(commit.stderr);const sha=await command(sandbox,'git',['rev-parse','HEAD']);const push=await command(sandbox,'git',['push','--set-upstream','origin',`HEAD:${BRANCH}`],REPO_DIR,gitEnv);if(push.exitCode)throw new Error(push.stderr);return sha.stdout.trim();}
async function main(){
 if(!safeBranch(BRANCH))throw new Error(`Refusing unsafe branch: ${BRANCH}`); if(!process.env.GITHUB_TOKEN)throw new Error('GITHUB_TOKEN is required'); if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is required'); if(!process.env.VERCEL_TOKEN||!process.env.VERCEL_TEAM_ID||!process.env.VERCEL_PROJECT_ID)throw new Error('Vercel sandbox credentials are required');
 const gitEnv={GITHUB_TOKEN:process.env.GITHUB_TOKEN,GIT_ASKPASS:ASKPASS_PATH,GIT_TERMINAL_PROMPT:'0'}; const agentEnv={OPENAI_API_KEY:process.env.OPENAI_API_KEY}; let sandbox;let status='FAILED';let failure=null;let commitSha=null;let passesCompleted=0;let failures=[];
 try{
  sandbox=await Sandbox.create({teamId:process.env.VERCEL_TEAM_ID,projectId:process.env.VERCEL_PROJECT_ID,token:process.env.VERCEL_TOKEN,runtime:'node24',resources:{vcpus:2},persistent:false,timeout:MAX_MINUTES*60*1000,networkPolicy:'allow-all'});
  await command(sandbox,'sh',['-lc',`mkdir -p '${REPO_DIR}' && printf '#!/bin/sh\nprintf "%s\\n" "$GITHUB_TOKEN"\n' > '${ASKPASS_PATH}' && chmod 700 '${ASKPASS_PATH}'`],SANDBOX_ROOT,gitEnv);
  const clone=await command(sandbox,'git',['clone','--branch',BASE_BRANCH,'--depth','1',REPO_URL,REPO_DIR],SANDBOX_ROOT,gitEnv);if(clone.exitCode)throw new Error(`clone failed: ${clone.stderr}`);const checkout=await command(sandbox,'git',['checkout','-b',BRANCH]);if(checkout.exitCode)throw new Error(checkout.stderr);const install=await command(sandbox,'npm',['install','--no-audit','--no-fund','--no-package-lock']);if(install.exitCode)throw new Error(`dependency install failed: ${install.stderr||install.stdout}`);
  const prompt=[`You are the primary autonomous engineer for Bikeztagram.`,`Build the PRODUCT, not merely the bot.`,`Objective: ${OBJECTIVE}`,`Acceptance: ${ACCEPTANCE.join(' | ')}`,`First inspect the existing product, its director, renderer, media pipeline, UI and verification suite. Identify the highest-impact unfinished or weak product capability.`,`Then implement the largest coherent improvement you can safely complete in this run. Prefer real user-visible behaviour: better shot selection, cinematic direction, motion, transitions, pacing, audio, export quality, media intelligence and Android UX.`,`Do not waste the run on documentation, cosmetic refactors, duplicate tests or infrastructure unless required for the product improvement.`,`Never use Gemini, Google model APIs, @google/genai, GEMINI_API_KEY, or Gemini failovers.`,`Do not modify .github/workflows/**. Do not merge or deploy production. Do not commit or push.`,`Run relevant verification and the production build. If a check fails, diagnose and fix it before stopping.`,`Do not stop merely because one objective is complete: inspect for the next highest-value improvement and continue until the time/pass budget is exhausted or the product batch is genuinely complete.`].join('\n');
  for(let pass=1;pass<=MAX_PASSES;pass++){passesCompleted=pass;const agent=await command(sandbox,AGENT_CMD[0],[...AGENT_CMD.slice(1),prompt],REPO_DIR,agentEnv);if(agent.exitCode){failures=[`Codex failed (exit ${agent.exitCode})\n${compact(agent.stderr||agent.stdout)}`];continue;}failures=await verify(sandbox);if(!failures.length) { await resetProtected(sandbox); const st=await command(sandbox,'git',['status','--short']); if(!st.stdout.trim()) { failures=['No product changes were produced.']; continue; } status='VERIFIED'; break; }}
  if(status!=='VERIFIED')throw new Error(`Builder verification failed after ${passesCompleted} passes:\n${failures.join('\n\n')}`); commitSha=await publish(sandbox,gitEnv);status='READY_FOR_REVIEW';
 }catch(error){failure=error instanceof Error?error.message:String(error);}finally{if(sandbox){try{await sandbox.stop();}catch(error){failure??=String(error);}}await mkdir('./builder/reports',{recursive:true});await writeFile(`./builder/reports/${BATCH_ID}.json`,JSON.stringify({batchId:BATCH_ID,objective:OBJECTIVE,workingBranch:BRANCH,commitSha,provider:'openai-codex',model:'gpt-5.3-codex',passesCompleted,maxPasses:MAX_PASSES,maxDurationMinutes:MAX_MINUTES,status,failure,gemini:'forbidden',autoMerge:false,autoProductionDeploy:false,finishedAt:new Date().toISOString(),checks:results},null,2));if(status!=='READY_FOR_REVIEW')process.exitCode=1;}}
main();
