import { Sandbox } from '@vercel/sandbox';
import { mkdir, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const REPO_URL = process.env.BUILDER_REPO_URL || 'https://github.com/bikeztagram-ai/bikeztagram-ai-build-v2.git';
const BATCH_ID = process.env.BUILDER_BATCH_ID || 'batch-77';
const BRANCH = process.env.BUILDER_WORKING_BRANCH || `autonomous-builder/${BATCH_ID}`;
const BASE_BRANCH = process.env.BUILDER_BASE_BRANCH || 'main';
const MAX_MINUTES = Number(process.env.BUILDER_MAX_MINUTES || 60);
const AGENT_CMD = process.env.BUILDER_AGENT_CMD ? JSON.parse(process.env.BUILDER_AGENT_CMD) : null;
const VERIFY_COMMANDS = (process.env.BUILDER_VERIFY_COMMANDS || 'npm run build,npm run verify:batch76')
  .split(',').map((value) => value.trim()).filter(Boolean);

function assertSafeBranch(branch) {
  if (!branch || branch === 'main' || branch === 'master' || branch.startsWith('production/')) {
    throw new Error(`Unsafe working branch: ${branch}`);
  }
}

async function runCommand(sandbox, cmd, args = [], cwd = '/workspace/repo') {
  const result = await sandbox.runCommand({ cmd, args, cwd });
  return {
    command: [cmd, ...args].join(' '),
    exitCode: result.exitCode,
    stdout: await result.stdout(),
    stderr: await result.stderr(),
  };
}

async function main() {
  assertSafeBranch(BRANCH);
  if (!process.env.GITHUB_TOKEN) throw new Error('GITHUB_TOKEN is required');
  if (!AGENT_CMD) throw new Error('BUILDER_AGENT_CMD is required; runner will not guess or install an agent');

  const startedAt = new Date().toISOString();
  const timeoutMs = Math.min(MAX_MINUTES, 60) * 60 * 1000;
  let sandbox;
  const checks = [];
  let status = 'FAILED';
  let failure = null;

  try {
    sandbox = await Sandbox.create({ persistent: false, timeout: timeoutMs });
    await sandbox.runCommand({ cmd: 'mkdir', args: ['-p', '/workspace'] });

    const authHeader = `AUTHORIZATION: bearer ${process.env.GITHUB_TOKEN}`;
    const clone = await runCommand(
      sandbox,
      'git',
      ['-c', `http.extraheader=${authHeader}`, 'clone', '--branch', BASE_BRANCH, '--depth', '1', REPO_URL, '/workspace/repo'],
      '/workspace',
    );
    checks.push(clone);
    if (clone.exitCode !== 0) throw new Error(`Git clone failed: ${clone.stderr}`);

    const branch = await runCommand(sandbox, 'git', ['checkout', '-b', BRANCH]);
    checks.push(branch);
    if (branch.exitCode !== 0) throw new Error(`Branch creation failed: ${branch.stderr}`);

    const prompt = [
      `You are the Bikeztagram autonomous builder for ${BATCH_ID}.`,
      `Work only on branch ${BRANCH}. Never checkout or modify main. Never deploy production.`,
      'Read builder/README.md and builder/batch-77.json before changing anything.',
      'Implement only the batch objective and acceptance criteria.',
      'Do not commit or push; the runner owns Git commits and pushes.',
      'Do not create paid infrastructure, storage, domains, or production deployments.',
      'When implementation is complete, leave the working tree with the intended changes and stop.',
    ].join(' ');

    const agent = await runCommand(sandbox, AGENT_CMD[0], [...AGENT_CMD.slice(1), prompt]);
    checks.push(agent);
    if (agent.exitCode !== 0) throw new Error(`Agent failed: ${agent.stderr || agent.stdout}`);

    for (const verify of VERIFY_COMMANDS) {
      const [cmd, ...args] = verify.split(/\s+/);
      const result = await runCommand(sandbox, cmd, args);
      checks.push(result);
      if (result.exitCode !== 0) throw new Error(`Verification failed: ${verify}`);
    }

    const diff = await runCommand(sandbox, 'git', ['diff', '--stat']);
    checks.push(diff);
    const statusResult = await runCommand(sandbox, 'git', ['status', '--short']);
    checks.push(statusResult);

    if (statusResult.stdout.includes('package-lock.json')) {
      // Lockfiles are allowed when generated by the build, but the runner does not create them itself.
    }

    const add = await runCommand(sandbox, 'git', ['add', '-A']);
    checks.push(add);
    if (add.exitCode !== 0) throw new Error(`git add failed: ${add.stderr}`);

    const commit = await runCommand(sandbox, 'git', ['commit', '-m', `builder: complete ${BATCH_ID}`]);
    checks.push(commit);
    if (commit.exitCode !== 0) throw new Error(`git commit failed: ${commit.stderr}`);

    const push = await runCommand(
      sandbox,
      'git',
      ['-c', `http.extraheader=${authHeader}`, 'push', '--set-upstream', 'origin', BRANCH],
    );
    checks.push(push);
    if (push.exitCode !== 0) throw new Error(`git push failed: ${push.stderr}`);

    status = 'READY_FOR_REVIEW';
  } catch (error) {
    failure = error instanceof Error ? error.message : String(error);
  } finally {
    const report = {
      batchId: BATCH_ID,
      baseBranch: BASE_BRANCH,
      workingBranch: BRANCH,
      maxDurationMinutes: Math.min(MAX_MINUTES, 60),
      keepAlive: false,
      status,
      failure,
      startedAt,
      finishedAt: new Date().toISOString(),
      checks: checks.map(({ command, exitCode, stdout, stderr }) => ({ command, exitCode, stdout, stderr })),
    };

    if (sandbox) {
      try {
        await sandbox.stop();
      } catch (error) {
        report.sandboxStopError = error instanceof Error ? error.message : String(error);
      }
    }

    await mkdir('./builder/reports', { recursive: true });
    await writeFile(`./builder/reports/${BATCH_ID}.json`, JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report, null, 2));
    if (status !== 'READY_FOR_REVIEW') process.exitCode = 1;
  }
}

main();
