import { refineCinematicTimeline } from './timelineDirector.js';
import { critiqueAndImproveTimeline, describeCritique } from './editCritic.js';
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const t=v=>String(v||'').trim();
export function createAIEditPlan(analysis,options={}){const p=t(options.creativePrompt).toLowerCase();const action=/action|chase|race|speed|pursuit|aggressive/.test(p);const dark=/dark|night|moody|horror|noir/.test(p);const emotional=/emotional|romantic|beautiful|nostalgic/.test(p);const list=Array.isArray(analysis?.bestMoments)?analysis.bestMoments:Array.isArray(analysis?.cuts)?analysis.cuts:[];const source=Math.max(3,n(analysis?.durationInSeconds,11));const target=Math.max(5,n(options.targetDuration,15));const total=Math.max(3,Math.min(8,list.length||5));const segment=Math.min(source,target)/total;const MOTION_ACTION=['pan-right','orbit','tilt-up','tilt-down'];
const MOTION_STORY=['slow-push','slow-pull','pan-left','pan-right','tilt-up'];
const TRANSITIONS_ACTION=['flash-cut','whip-right','whip-left','zoom-punch'];
const TRANSITIONS_STORY=['crossfade','hard-cut','light-leak-left','light-leak-right'];

const cuts=Array.from({length:total},(_,i)=>{const m=list[i]||{};const role=i===0?'hook':i===total-1?'hero-ending':action?'action':emotional?'emotional-beat':'story-beat';const start=Math.max(0,Math.min(source-.5,n(m.start??m.startTime,i*segment)));const duration=Math.max(.5,Math.min(4.5,n(m.duration,segment)));return{mediaIndex:0,mediaId:'video-0',startTime:Number(start.toFixed(2)),duration:Number(duration.toFixed(2)),purpose:role,speed:action&&role==='action'?1.15:role==='hero-ending'?.85:1,speedEnd:1,motionStyle:role==='action'?MOTION_ACTION[i%MOTION_ACTION.length]:MOTION_STORY[i%MOTION_STORY.length],motionIntensity:role==='action'?1.1:.85,transition:i===0?'fade-in':i===total-1?(dark?'dip-black':'fade-out'):action?TRANSITIONS_ACTION[i%TRANSITIONS_ACTION.length]:TRANSITIONS_STORY[i%TRANSITIONS_STORY.length],stabilization:true,colorGrade:dark?'dark-cinematic':emotional?'warm-cinematic':options.colorGrade||'cinematic',text:''};});const refined=refineCinematicTimeline(cuts,{creativePrompt:options.creativePrompt});const critique=critiqueAndImproveTimeline(refined,{flags:{action,dark,emotional,comedy:/funny|comedy/.test(p)}});return{title:`${t(analysis?.subject?.description)||t(analysis?.contentType)||'Media'} — AI Cinematic Edit`,style:action?'cinematic action edit':emotional?'emotional cinematic story':'cinematic creative edit',creativePrompt:t(options.creativePrompt),subject:t(analysis?.subject?.description)||'uploaded media',mediaType:t(analysis?.mediaType)||'video',cuts:critique.cuts,duration:critique.cuts.reduce((s,c)=>s+n(c.duration),0),targetDuration:target,colorGrade:dark?'dark-cinematic':options.colorGrade||'cinematic',qualityScore:critique.after.score,qualityReport:describeCritique(critique),source:'bikeztagram-director-v2'};}
export function describeAIEditPlan(plan){if(!plan?.cuts?.length)return'No AI edit plan available.';return`AI edit plan: ${plan.cuts.length} cuts • ${plan.duration.toFixed(1)}s • Quality ${plan.qualityScore}/100`;}
