/* BIKEZTAGRAM AI — universal filmmaker UI. Blob/Gemini/render infrastructure remains protected. */
import React,{useState} from 'react';
import {upload} from '@vercel/blob/client';
import {createAIEditPlan,describeAIEditPlan} from './aiEditPlanner.js';
import {renderInspectImprove} from './renderQualityLoop.js';
import {renderWorldScene} from './worldScene.js';
import {generateOriginalMusic} from './musicGenerator.js';
import {downloadSocialFilm,shareSocialFilm,getSocialExportInfo} from './socialExport.js';
import {applySpeechCaptionsToPlan,describeCaptionPlan} from './captionPlanner.js';
import {downloadRhythmReplacementMap} from './musicReplacementGuide.js';
import './styles.css';
const DEFAULT_PROMPT='Create the strongest cinematic social-media film from this media. Prioritise authentic footage, clear story, rhythm, composition, premium visual direction and a strong ending.';
const safeName=(name)=>String(name||'media').replace(/[^a-zA-Z0-9._-]/g,'_');
export default function App(){
 const [files,setFiles]=useState([]),[sources,setSources]=useState([]),[prompt,setPrompt]=useState(DEFAULT_PROMPT),[analysis,setAnalysis]=useState(null),[plan,setPlan]=useState(null),[productionPlan,setProductionPlan]=useState(null),[status,setStatus]=useState(''),[stage,setStage]=useState(''),[uploadProgress,setUploadProgress]=useState(0),[renderProgress,setRenderProgress]=useState(0),[loading,setLoading]=useState(false),[rendering,setRendering]=useState(false),[renderedUrl,setRenderedUrl]=useState(''),[qa,setQa]=useState(null),[attempts,setAttempts]=useState(0),[error,setError]=useState(null),[worldUrl,setWorldUrl]=useState(''),[soundtrack,setSoundtrack]=useState(null),[exportInfo,setExportInfo]=useState(null),[autoCaptions,setAutoCaptions]=useState(true),[captionResult,setCaptionResult]=useState(null);
 const busy=loading||rendering;const isSingle=files.length===1;const isVideo=isSingle&&files[0]?.type?.startsWith('video/');
 function reset(){if(renderedUrl)URL.revokeObjectURL(renderedUrl);if(worldUrl)URL.revokeObjectURL(worldUrl);setFiles([]);setSources([]);setAnalysis(null);setPlan(null);setProductionPlan(null);setRenderedUrl('');setWorldUrl('');setQa(null);setAttempts(0);setError(null);setStatus('');setStage('');setUploadProgress(0);setRenderProgress(0);setSoundtrack(null);setExportInfo(null);setCaptionResult(null);}
 function choose(e){const selected=Array.from(e.target.files||[]).slice(0,12);if(renderedUrl)URL.revokeObjectURL(renderedUrl);setFiles(selected);setSources([]);setAnalysis(null);setPlan(null);setProductionPlan(null);setRenderedUrl('');setWorldUrl('');setQa(null);setAttempts(0);setError(null);setSoundtrack(null);setExportInfo(null);setCaptionResult(null);setStatus(selected.length?`Selected ${selected.length} media file${selected.length===1?'':'s'}.`:'');setStage('');}
 function details(err){return{time:new Date().toISOString(),stage,message:err?.message||String(err),name:err?.name||'Error',stack:err?.stack||'',files:files.map(f=>({name:f.name,type:f.type,sizeBytes:f.size})),online:navigator.onLine};}
 async function uploadOne(file,index,total){const folder=file.type.startsWith('image/')?'images':'videos';const path=`${folder}/${Date.now()}-${crypto.randomUUID()}-${safeName(file.name)}`;const blob=await upload(path,file,{access:'public',handleUploadUrl:'/api/upload',multipart:false,clientPayload:JSON.stringify({source:'bikeztagram-ai',filename:file.name,mimeType:file.type,size:file.size,mediaType:file.type.startsWith('image/')?'image':'video'}),onUploadProgress:(e)=>{const p=Number(e?.percentage)||0;setUploadProgress(Math.round(((index+p/100)/total)*100));}});if(!blob?.url)throw new Error(`Blob upload failed for ${file.name}.`);return{id:`source-${index}`,file,name:file.name,type:file.type,sourceUrl:blob.url,url:blob.url,pathname:blob.pathname,mimeType:file.type};}
 async function analyseSpeech(item){if(!autoCaptions||!item?.type?.startsWith('video/'))return null;setStage('STEP 3A — Gemini speech/caption analysis');setStatus('📝 Checking the actual video for spoken dialogue and time-coded captions...');try{const r=await fetch('/api/captions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoUrl:item.url,filename:item.name,mimeType:item.mimeType})});const t=await r.text();let data;try{data=JSON.parse(t);}catch{throw new Error(`Caption analysis returned invalid JSON: ${t.slice(0,300)}`);}if(!r.ok)throw new Error(data?.error||`Caption analysis HTTP ${r.status}`);return data;}catch(err){console.warn('[APP] caption analysis fallback',err);setStatus('📝 Caption analysis unavailable; continuing without captions.');return null;}}
 async function analyse(){if(!files.length)return setStatus('Choose one or more images/videos first.');if(files.some(f=>!f.type.startsWith('image/')&&!f.type.startsWith('video/')))return setStatus('Only images and videos are supported.');setLoading(true);setError(null);setAnalysis(null);setPlan(null);setProductionPlan(null);setRenderedUrl('');setQa(null);setAttempts(0);setUploadProgress(0);setSoundtrack(null);setExportInfo(null);setCaptionResult(null);try{setStage('STEP 1 — Uploading source library to Vercel Blob');setStatus(`Uploading ${files.length} source${files.length===1?'':'s'}...`);const uploaded=[];for(let i=0;i<files.length;i++)uploaded.push(await uploadOne(files[i],i,files.length));setSources(uploaded);setUploadProgress(100);setStage('STEP 2 — Gemini analysing the actual source library');let data;
 if(uploaded.length>1){const r=await fetch('/api/analyse-library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,targetDuration:15,items:uploaded.map(x=>({url:x.url,filename:x.name,mimeType:x.mimeType,mediaType:x.type.startsWith('image/')?'image':'video'})))});const t=await r.text();try{data=JSON.parse(t);}catch{throw new Error(`Mixed-media analysis returned invalid JSON: ${t.slice(0,500)}`);}if(!r.ok)throw new Error(data?.error||`Mixed-media analysis HTTP ${r.status}`);if(!data?.analysis||!data?.aiEditPlan?.cuts?.length)throw new Error('Gemini returned no valid mixed-media director plan.');setAnalysis(data.analysis);setPlan(data.aiEditPlan);setProductionPlan({title:data.aiEditPlan.title,creativeDirection:data.analysis.librarySummary,scenes:data.aiEditPlan.cuts.map(c=>({mediaIndex:c.sourceIndex,sourceType:'uploaded',startTime:c.startTime,duration:c.duration,purpose:c.purpose,transitionIn:c.transition,motionStyle:c.motionStyle}))});setStatus(`✅ Gemini directed ${uploaded.length} sources as one film: ${data.aiEditPlan.cuts.length} selected shots.`);
 }else{const item=uploaded[0];const image=item.type.startsWith('image/');const endpoint=image?'/api/analyse-image':'/api/analyse';const payload=image?{imageUrl:item.url,pathname:item.pathname,filename:item.name,mimeType:item.mimeType,prompt}:{videoUrl:item.url,pathname:item.pathname,filename:item.name,mimeType:item.mimeType,prompt};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const t=await r.text();try{data=JSON.parse(t);}catch{throw new Error(`Analysis returned invalid JSON: ${t.slice(0,500)}`);}if(!r.ok)throw new Error(data?.error||`Analysis HTTP ${r.status}`);if(!data?.analysis)throw new Error('Gemini returned no media analysis.');setAnalysis(data.analysis);setStage('STEP 3 — AI Director + production blueprint');let localPlan=createAIEditPlan(data.analysis,{maxCuts:8,targetDuration:15,colorGrade:'dark-cinematic',creativePrompt:prompt});if(!localPlan?.cuts?.length)throw new Error('AI Director returned no usable cuts.');const captionData=await analyseSpeech(item);if(captionData?.cues?.length){const applied=applySpeechCaptionsToPlan(localPlan,captionData.cues,{minimumConfidence:.55});localPlan=applied.plan;setCaptionResult({...applied,...captionData});setStatus(`✅ Gemini analysed the actual ${image?'image':'video'}. ${describeAIEditPlan(localPlan)} • ${describeCaptionPlan(applied)}`);}else{setCaptionResult(captionData?{...captionData,captionCount:0,appliedCount:0}:null);setStatus(`✅ Gemini analysed the actual ${image?'image':'video'}. ${describeAIEditPlan(localPlan)}`);}setPlan(localPlan);try{const pr=await fetch('/api/production-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,analysis:data.analysis,targetDuration:15})});const pd=await pr.json();if(pr.ok&&pd?.productionPlan?.scenes?.length)setProductionPlan(pd.productionPlan);}catch(e){console.warn('[APP] production blueprint fallback',e);}}
 }catch(err){const d=details(err);console.error('[APP]',d);setError(d);setStatus(`❌ ERROR — ${d.message}`);}finally{setLoading(false);}}
 function makeRenderPlan(){if(!plan?.cuts?.length)return null;const cuts=plan.cuts.map((c,i)=>{const sourceIndex=Number.isInteger(Number(c.sourceIndex))?Number(c.sourceIndex):0;const source=sources[sourceIndex]||sources[0];return{...c,mediaIndex:sourceIndex,mediaId:source?.id||`source-${sourceIndex}`,sourceType:'uploaded',generated:false,colorGrade:plan.colorGrade||'dark-cinematic',motionIntensity:1,stabilization:true,speedEnd:c.speed||1,transition:c.transition||((i===0)?'fade-in':'hard-cut')};});return{title:plan.title||'Universal AI Film',style:plan.style||'cinematic',creativePrompt:prompt,colorGrade:plan.colorGrade||'dark-cinematic',cuts,targetDuration:Number(plan.targetDuration)||15,speechCaptions:plan.speechCaptions||[],captioning:plan.captioning||{enabled:false}};}
 async function render(){if(!plan?.cuts?.length||!sources.length)return setStatus('Analyse the media first.');setRendering(true);setError(null);setRenderProgress(0);setQa(null);setAttempts(0);setExportInfo(null);try{setStage('STEP 4A — Creating original soundtrack');setStatus('🎵 Creating an original soundtrack and analysing its beat grid...');let musicResult=null;try{musicResult=await generateOriginalMusic({prompt,duration:15});if(musicResult?.soundtrack){setSoundtrack(musicResult.soundtrack);if(musicResult.soundtrack.audioAvailable)setStatus(`🎵 Original soundtrack ready — ${musicResult.soundtrack.bpm||'target'} BPM. Preparing cinematic render...`);else setStatus('🎵 Music plan ready; live audio generation unavailable, continuing with visual render.');}}catch(musicError){console.warn('[APP] soundtrack generation fallback',musicError);setStatus('🎵 Soundtrack generation unavailable; continuing with visual render.');}
 setStage('STEP 4B — Render → inspect → improve');const renderPlan=makeRenderPlan();if(musicResult?.soundtrack?.audioAvailable)renderPlan.music={...musicResult.soundtrack};const result=await renderInspectImprove({mediaItems:sources,plan:renderPlan,expectedDuration:renderPlan.targetDuration,maxAttempts:2,onProgress:(e)=>{if(e.stage==='render'){setRenderProgress(Math.round(Number(e.value)||0));setStatus(`🎬 Rendering attempt ${e.attempt}... ${Math.round(Number(e.value)||0)}%`);}if(e.stage==='qa'){setQa(e.qa);setAttempts(e.attempt);setStatus(`🔎 Automatic render QA — ${e.qa?.verdict||'CHECKING'}`);}if(e.stage==='revise')setStatus(`🛠️ Improving render: ${(e.reasons||[]).join(', ')||'quality revision'}`);}});if(!(result?.output instanceof Blob)||!result.output.size)throw new Error('Renderer produced no usable video.');if(renderedUrl)URL.revokeObjectURL(renderedUrl);setRenderedUrl(URL.createObjectURL(result.output));setQa(result.qa);setAttempts(result.attempts?.length||1);setExportInfo(getSocialExportInfo(result.output,'portrait'));setRenderProgress(100);setStage('STEP 5 — Finished film + automatic QA checkpoint');setStatus(`✅ Finished AI film created, soundtrack processed and QA checked — ${result.attempts?.length||1} render attempt(s).`);}catch(err){const d=details(err);console.error('[APP RENDER]',d);setError(d);setStatus(`❌ RENDER ERROR — ${d.message}`);}finally{setRendering(false);}}
 function exportRhythmMap(){try{const payload=downloadRhythmReplacementMap(plan,soundtrack,plan?.title||'bikeztagram-ai-rhythm-map');setStatus(`🎵 Rhythm replacement map exported — ${payload.editCuts.length} timed edit sections.`);}catch(err){setStatus(`❌ RHYTHM MAP ERROR — ${err.message}`);}}
 return <div className="app-container"><header className="app-header"><div><h1>BIKEZTAGRAM AI</h1><p>Universal AI filmmaker — mixed-media source library</p></div></header><main><section className="form-group"><label htmlFor="media-file">Source media library</label><input id="media-file" type="file" accept="video/*,image/*" multiple onChange={choose} disabled={busy}/>{files.length>0&&<div className="status-text">{files.map((f,i)=><div key={`${f.name}-${i}`}>{f.type.startsWith('image/')?'🖼️':'🎬'} {f.name}</div>)}<small>Maximum 12 sources • images + videos can be mixed</small></div>}</section><section className="form-group"><label htmlFor="analysis-prompt">Creative brief</label><textarea id="analysis-prompt" rows="7" value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={busy}/></section><section className="form-group"><label><input type="checkbox" checked={autoCaptions} onChange={e=>setAutoCaptions(e.target.checked)} disabled={busy||!isVideo}/> Auto-detect spoken dialogue and add verified captions to video edits</label></section><div className="button-row"><button className="generate-btn" onClick={analyse} disabled={busy||!files.length}>{loading?'👁️ Analysing...':'👁️ Analyse Source Library'}</button>{plan&&!busy&&<button className="generate-btn" onClick={render}>🎬 Build + Self-Check AI Film</button>}{!busy&&plan&&<button className="generate-btn" onClick={exportRhythmMap}>🎵 Export Rhythm Map</button>}{isVideo&&sources.length===1&&!busy&&<button className="generate-btn" onClick={world}>✨ Create AI World Scene</button>}{!busy&&files.length>0&&<button className="clear-btn" onClick={reset}>Clear</button>}</div>{(busy||status)&&<section className="status-panel" style={{marginTop:15}}><p className="status-text">{status}</p><p style={{fontSize:13,opacity:.8}}>{stage}</p>{loading&&<div>Blob upload: {uploadProgress}%</div>}{rendering&&<div>Render pipeline: {renderProgress}%</div>}</section>}{error&&<pre className="error-panel">{JSON.stringify(error,null,2)}</pre>}{renderedUrl&&<section className="result-panel"><video src={renderedUrl} controls playsInline style={{width:'100%',maxHeight:'70vh',background:'#000'}}/><div className="button-row"><button className="generate-btn" onClick={exportFilm}>⬇️ Export Film</button><button className="generate-btn" onClick={shareFilm}>📤 Share Film</button></div>{qa&&<p className="status-text">QA: {qa.verdict||'CHECKED'} • attempts: {attempts}</p>}</section>}{worldUrl&&<section className="result-panel"><video src={worldUrl} controls playsInline style={{width:'100%',maxHeight:'70vh',background:'#000'}}/></section>}</main></div>;
}
