/* BIKEZTAGRAM AI — V3 cinematic renderer: real motion + visible transitions. */
import { attachPlanAudioToRenderStream } from './renderAudioBridge.js';
import { mergeFocalMotion } from './temporalFocalInterpolator.js';
import { resolveRenderOutput } from './renderOutputRuntime.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ease=v=>v<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2;
const lerp=(a,b,t)=>a+(b-a)*t;
const supported=()=>['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4;codecs=h264','video/mp4'].find(t=>typeof MediaRecorder!=='undefined'&&MediaRecorder.isTypeSupported(t))||'';

function grade(name){const g=String(name||'').toLowerCase();if(g.includes('warm'))return'brightness(.96) contrast(1.14) saturate(1.15) sepia(.06)';if(g.includes('vivid'))return'brightness(.96) contrast(1.22) saturate(1.3)';if(g.includes('natural'))return'brightness(1) contrast(1.06) saturate(1.06)';if(g.includes('blue')||g.includes('moody')||g.includes('dark'))return'brightness(.92) contrast(1.18) saturate(1.14) hue-rotate(-5deg)';return'brightness(.95) contrast(1.16) saturate(1.12)';}
function motion(cut,p,w,h){const m=String(cut.motionStyle||cut.motion||'cinematic').toLowerCase(),e=ease(p),i=clamp(Number(cut.motionIntensity)||.9,.35,1.7);let scale=1.045,x=0,y=0,r=0;if(m.includes('push')||m==='zoom')scale+=e*.13*i;else if(m.includes('pull'))scale+=(1-e)*.13*i;else if(m.includes('pan-right')){scale=1.10;x=(e-.5)*w*.16*i}else if(m.includes('pan-left')){scale=1.10;x=(.5-e)*w*.16*i}else if(m.includes('tilt-up')){scale=1.09;y=(.5-e)*h*.10*i}else if(m.includes('tilt-down')){scale=1.09;y=(e-.5)*h*.10*i}else if(m.includes('orbit')||m.includes('parallax')){scale=1.11;x=Math.sin(e*Math.PI*2)*w*.045*i;y=Math.cos(e*Math.PI*2)*h*.025*i;r=Math.sin(e*Math.PI*2)*.008*i}else if(m==='static')scale=1.015;return{scale:clamp(scale,1.01,1.32),x,y,r};}
function drawCover(ctx,el,t,gradeName,focal,w,h){const sw=el.videoWidth||el.naturalWidth,sh=el.videoHeight||el.naturalHeight;if(!sw||!sh)return false;const ratio=sw/sh,target=w/h;let dw,dh;if(ratio>target){dh=h*t.scale;dw=dh*ratio}else{dw=w*t.scale;dh=dw/ratio}const fx=clamp(Number(focal?.x)||.5,.1,.9),fy=clamp(Number(focal?.y)||.5,.1,.9),fs=clamp(Number(focal?.scale)||1,1,1.18);let x=(w-dw)/2+t.x+(.5-fx)*(dw-w)*.72,y=(h-dh)/2+t.y+(.5-fy)*(dh-h)*.72;x+=(.5-fx)*w*.025;y+=(.5-fy)*h*.025;ctx.save();ctx.filter=grade(gradeName);ctx.translate(w/2,h/2);ctx.rotate(t.r);ctx.translate(-w/2,-h/2);ctx.drawImage(el,x,y,dw*fs,dh*fs);ctx.restore();return true;}
function effect(ctx,name,p,w,h){const n=String(name||'hard-cut').toLowerCase(),d=.28;const q=clamp(p/d,0,1),out=clamp((1-p)/d,0,1),mid=Math.max(0,1-Math.abs(p-.5)/.5);if(n==='fade-in'){ctx.fillStyle='#000';ctx.globalAlpha=out;ctx.fillRect(0,0,w,h)}else if(n==='fade-out'){ctx.fillStyle='#000';ctx.globalAlpha=1-clamp((p-(1-d))/d,0,1);ctx.fillRect(0,0,w,h)}else if(n==='dip-black'){ctx.fillStyle='#000';ctx.globalAlpha=mid*.95;ctx.fillRect(0,0,w,h)}else if(n==='flash-cut'){ctx.fillStyle='#fff';ctx.globalAlpha=Math.pow(mid,2)*.8;ctx.fillRect(0,0,w,h)}else if(n==='zoom-punch'){const a=Math.pow(Math.sin(Math.PI*clamp(p/.45,0,1)),2)*.16;ctx.fillStyle='#fff';ctx.globalAlpha=a;ctx.fillRect(0,0,w,h)}else if(n.startsWith('light-leak')){const dir=n.endsWith('left')?-1:n.endsWith('right')?1:0;const g=ctx.createLinearGradient(dir<0?w:0,0,dir>0?w:0,0);g.addColorStop(0,'rgba(255,255,220,.38)');g.addColorStop(.45,'rgba(255,170,70,.16)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.globalAlpha=Math.pow(mid,1.5);ctx.fillRect(0,0,w,h)}else if(n==='whip-left'||n==='whip-right'){const dir=n==='whip-right'?1:-1,amt=(1-q)*dir*w*.18;ctx.fillStyle='#05070b';ctx.globalAlpha=.55*(1-q);ctx.fillRect(amt,0,w,h)}ctx.globalAlpha=1;}
function vignette(ctx,w,h){const g=ctx.createRadialGradient(w/2,h/2,h*.16,w/2,h/2,h*.8);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.7,'rgba(0,0,0,.06)');g.addColorStop(1,'rgba(0,0,0,.58)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function cinematicFinish(ctx,plan,w,h){if(!plan)return;vignette(ctx,w,h);if(/cinematic|trailer|film|commercial/i.test(String(plan.creativePrompt||plan.style||''))){const b=Math.round(h*.028);ctx.fillStyle='rgba(0,0,0,.9)';ctx.fillRect(0,0,w,b);ctx.fillRect(0,h-b,w,b)}}

export async function renderProject(mediaItems,plan,onProgress){return new Promise((resolve,reject)=>{let recorder=null,audioBridge=null,raf=0;const urls=[];try{const output=resolveRenderOutput(plan);const canvas=document.createElement('canvas');canvas.width=output.width;canvas.height=output.height;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Could not create canvas context.');const stream=canvas.captureStream(output.fps);const type=supported();const chunks=[];let stopped=false;const fail=e=>{if(stopped)return;stopped=true;cancelAnimationFrame(raf);try{recorder?.stop()}catch{}try{audioBridge?.cleanup?.()}catch{}urls.forEach(u=>{try{URL.revokeObjectURL(u)}catch{}});reject(e instanceof Error?e:Error(String(e)))};const cuts=Array.isArray(plan?.cuts)?plan.cuts:Array.isArray(plan?.scenes)?plan.scenes.map((s,i)=>({...s,mediaIndex:s.mediaIndex??0,duration:s.duration??2,transition:s.transitionIn||s.transition||(i?'crossfade':'fade-in'),motionStyle:s.motionStyle||'slow-push'})):[];if(!cuts.length)throw Error('AI edit plan contains no cuts.');const getMedia=c=>c.mediaId!=null?(mediaItems.find(x=>String(x.id)===String(c.mediaId))||mediaItems[Number(c.mediaIndex)]):mediaItems[Number(c.mediaIndex)];const sourceOf=m=>m?.sourceUrl?{url:m.sourceUrl,revoke:false}:m?.file?{url:URL.createObjectURL(m.file),revoke:true}:null;const generated=c=>Boolean(c.generated||c.sourceType==='generated'||c.sourceType==='procedural'||c.generationPrompt);let previousFrame=null;
const load=async(el,src,isVideo)=>{if(isVideo){el.muted=true;el.playsInline=true;el.preload='auto';el.src=src.url;el.load();await new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('Timed out decoding source video.')),12000);const ok=()=>{if(el.videoWidth&&el.videoHeight){clearTimeout(timer);res()}};el.addEventListener('loadeddata',ok,{once:true});el.addEventListener('canplay',ok,{once:true});el.addEventListener('error',()=>{clearTimeout(timer);rej(Error('Could not decode source video.'))},{once:true})});}else{el.src=src.url;await new Promise((res,rej)=>{el.onload=()=>res();el.onerror=()=>rej(Error('Could not load source image.'))})}};
const renderCut=async(index)=>{if(index>=cuts.length){if(recorder?.state!=='inactive')recorder.stop();return}const c=cuts[index]||{},dur=clamp(Number(c.duration)||2,.5,8),isGen=generated(c),m=isGen?null:getMedia(c);if(!isGen&&!m)throw Error(`Cut ${index+1} references missing media.`);const src=isGen?null:sourceOf(m);if(src?.revoke)urls.push(src.url);const isVideo=!isGen&&String(m.type||'').startsWith('video');const el=isGen?null:(isVideo?document.createElement('video'):new Image());try{if(el)await load(el,src,isVideo);if(isVideo){const st=Math.max(0,Number(c.startTime)||0);if(Number.isFinite(st)){try{el.currentTime=Math.min(st,Math.max(0,(el.duration||st+.1)-.05))}catch{}}el.playbackRate=clamp(Number(c.speed)||1,.5,1.75);await el.play()}const started=performance.now();await new Promise(done=>{const tick=()=>{const p=clamp((performance.now()-started)/(dur*1000),0,1);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);if(isGen){const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,'#07101c');g.addColorStop(.5,'#122d3c');g.addColorStop(1,'#02060a');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=.5;for(let i=0;i<14;i++){ctx.strokeStyle=i%2?'#66d9ff':'#ffffff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(canvas.width/2,canvas.height*.55);ctx.lineTo((i/14)*canvas.width+Math.sin(p*5+i)*80,canvas.height);ctx.stroke()}ctx.globalAlpha=1}else{const mm=motion(c,p,canvas.width,canvas.height),tm=mergeFocalMotion(mm,c.temporalFocal,p,.65);drawCover(ctx,el,tm,c.colorGrade||plan.colorGrade,{...(c.focalFraming||{}),x:tm.focalX??c.focalFraming?.x??.5,y:tm.focalY??c.focalFraming?.y??.5},canvas.width,canvas.height);if(isVideo)try{el.playbackRate=lerp(Number(c.speed)||1,Number(c.speedEnd??c.speed)||Number(c.speed)||1,ease(p))}catch{}}
const tr=String(c.transition||'hard-cut').toLowerCase(),td=clamp(Number(c.transitionDuration)||.28,.12,Math.min(.8,dur*.45));if(previousFrame&&(index>0)&&tr==='crossfade'&&p<td){ctx.save();ctx.globalAlpha=1-p/td;ctx.drawImage(previousFrame,0,0);ctx.restore();}else if(previousFrame&&index>0&&p<td&&(tr==='whip-left'||tr==='whip-right')){ctx.save();ctx.globalAlpha=.7*(1-p/td);ctx.drawImage(previousFrame,(tr==='whip-right'?1:-1)*(p/td-1)*canvas.width*.35,0,canvas.width,canvas.height);ctx.restore();}effect(ctx,tr,p,canvas.width,canvas.height);cinematicFinish(ctx,plan,canvas.width,canvas.height);if(c.text){ctx.save();ctx.fillStyle='#fff';ctx.font=`800 ${Math.max(28,Math.round(canvas.width*.045))}px Arial`;ctx.textAlign='center';ctx.shadowColor='#000';ctx.shadowBlur=18;ctx.fillText(String(c.text).toUpperCase(),canvas.width/2,canvas.height*.88);ctx.restore()}onProgress?.(Math.round(((index+p)/cuts.length)*100));if(p>=1){if(!previousFrame)previousFrame=document.createElement('canvas');previousFrame.width=canvas.width;previousFrame.height=canvas.height;previousFrame.getContext('2d').drawImage(canvas,0,0);done();return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)});if(isVideo)el.pause();await renderCut(index+1)}catch(e){throw Error(`Cut ${index+1} failed: ${e?.message||e}`)}};
(async()=>{try{audioBridge=await attachPlanAudioToRenderStream(stream,plan);recorder=type?new MediaRecorder(stream,{mimeType:type}):new MediaRecorder(stream);recorder.ondataavailable=e=>e.data?.size&&chunks.push(e.data);recorder.onerror=e=>fail(e.error||Error('Video recording failed.'));recorder.onstop=()=>{if(stopped)return;stopped=true;cancelAnimationFrame(raf);try{audioBridge?.cleanup?.()}catch{}urls.forEach(u=>{try{URL.revokeObjectURL(u)}catch{}});if(!chunks.length)return reject(Error('MediaRecorder produced no video data.'));resolve(new Blob(chunks,{type:chunks[0]?.type||type||'video/webm'}))};recorder.start(250);await renderCut(0)}catch(e){fail(e)}})()}catch(e){reject(e)}})}
