/* BIKEZTAGRAM AI — capability registry. */
const registry = new Map();
export const CREATIVE_CAPABILITIES = Object.freeze({UNDERSTAND:'creative-understanding',PLAN:'creative-planning',IMAGE_GENERATION:'image-generation',TEXT_TO_VIDEO:'text-to-video',IMAGE_TO_VIDEO:'image-to-video',FOOTAGE_ANALYSIS:'footage-analysis',MUSIC_GENERATION:'music-generation',MUSIC_ANALYSIS:'music-analysis',VOICE_GENERATION:'voice-generation',TIMELINE_EDIT:'timeline-edit',RENDER:'render',QUALITY_ANALYSIS:'quality-analysis',REVISION:'revision'});
export const CAPABILITY_REQUIREMENTS = Object.freeze({'text-to-video':['creative-planning','text-to-video','render'],'image-to-video':['creative-planning','image-to-video','render'],'footage-edit':['creative-understanding','footage-analysis','timeline-edit','render','quality-analysis'],'music-video':['creative-planning','music-generation','music-analysis','timeline-edit','render','quality-analysis']});
export function capabilitiesFor(mode){return [...(CAPABILITY_REQUIREMENTS[mode]||[])];}
export function hasCapabilities(available,required){const set=new Set(Array.isArray(available)?available:[]);return(Array.isArray(required)?required:[]).every(x=>set.has(x));}
export function registerCreativeCapability(capability={}){const id=String(capability.id||'').trim();if(!id)throw new Error('Creative capability requires an id.');registry.set(id,{id,kind:capability.kind||'creative',label:capability.label||id,description:capability.description||'',input:capability.input||[],output:capability.output||[],providers:capability.providers||['local'],priority:Number(capability.priority||0),available:typeof capability.available==='function'?capability.available:()=>true,execute:typeof capability.execute==='function'?capability.execute:null});return registry.get(id);}
export function getCreativeCapability(id){return registry.get(String(id||''))||null;}
export function listCreativeCapabilities(context={}){return[...registry.values()].filter(item=>{try{return item.available(context)!==false;}catch{return false;}}).sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id)).map(({execute,...publicCapability})=>publicCapability);}
export function resolveCreativeCapabilities(requested=[],context={}){const wanted=Array.isArray(requested)?requested:[requested];const available=listCreativeCapabilities(context);return wanted.map(id=>available.find(item=>item.id===id)).filter(Boolean);}
export async function executeCreativeCapability(id,input,context={}){const capability=getCreativeCapability(id);if(!capability||typeof capability.execute!=='function')throw new Error(`Creative capability is unavailable: ${id}`);if(capability.available(context)===false)throw new Error(`Creative capability is not currently available: ${id}`);return capability.execute(input,context);}
export function createCapabilityManifest(){return listCreativeCapabilities().map(item=>({id:item.id,kind:item.kind,label:item.label,providers:item.providers,input:item.input,output:item.output}));}
