/* Autonomous Creative Engine — deterministic orchestration; adapters are injected. */
const STAGES=['understand','direct','music','scenes','assemble','render','qa','revise','export'];
const now=()=>Date.now();
export function createCreativeRuntime({job,adapters={},maxAttempts=3}={}){return{version:'creative-runtime-v2',job,stage:'understand',completed:[],outputs:{},attempts:{},errors:[],maxAttempts,adapters,startedAt:now(),updatedAt:now(),status:'ready'};}
export function canRunStage(state,stage){const index=STAGES.indexOf(stage);if(index<0)return false;if(index===0)return true;return state.completed.includes(STAGES[index-1]);}
function blocked(state,stage,reason){return{...state,stage,status:'blocked',outputs:{...state.outputs,[stage]:{status:'blocked',reason,required:true}},updatedAt:now()};}
function failed(state,stage,error){const attempts={...state.attempts,[stage]:Number(state.attempts?.[stage]||0)+1};return{...state,stage,status:'failed',attempts,errors:[...(state.errors||[]),{stage,message:error?.message||String(error),at:now()}],updatedAt:now()};}
export async function runCreativeStage(state,stage,context={}){if(!STAGES.includes(stage))throw new Error(`Unknown Creative Engine stage: ${stage}`);if(!canRunStage(state,stage))throw new Error(`Stage dependency not satisfied: ${stage}`);const fn=state.adapters?.[stage];if(typeof fn!=='function')return blocked(state,stage,'required adapter unavailable');try{const output=await fn({state,context});if(output==null)return failed(state,stage,new Error('Stage adapter returned no output.'));if(output?.status==='blocked')return blocked(state,stage,output.reason||'adapter blocked stage');if(output?.status==='failed')return failed(state,stage,new Error(output.error||'stage adapter failed'));const completed=[...new Set([...state.completed,stage])];return{...state,stage:STAGES[STAGES.indexOf(stage)+1]||'complete',status:'running',completed,outputs:{...state.outputs,[stage]:{status:'ready',...output}},updatedAt:now()};}catch(error){return failed(state,stage,error);}}
export function nextCreativeStage(state){return state?.status==='blocked'||state?.status==='failed'?state.stage:(STAGES.find(stage=>!state.completed.includes(stage))||'complete');}
export function getCreativeProgress(state){const completed=(state?.completed||[]).length;return{stage:state?.stage||'understand',status:state?.status||'ready',completed,total:STAGES.length,percent:Math.round((completed/STAGES.length)*100),stages:STAGES};}
export function shouldRevise(state,quality){const score=Number(quality?.score)||0;const attempts=Number(state?.attempts?.qa||0)+Number(state?.attempts?.revise||0);return score<80&&attempts<Number(state?.maxAttempts||3);}
export function getCreativeStageStatus(state,stage){return state?.outputs?.[stage]?.status||((state?.completed||[]).includes(stage)?'ready':'pending');}
