const ACTION_WORDS=['action','movement','running','walking','riding','driving','accelerating','cornering','chase','jumping','playing','flying','swimming','dancing','travel','journey','bike','ride'];
const HERO_WORDS=['hero','reveal','portrait','close-up','landscape','sunset','detail','showcase','beautiful','epic','product'];
const EMOTION_WORDS=['smile','laugh','joy','cute','love','dramatic','emotional','surprise','calm','peaceful','excited'];
const FAMILY_WORDS={wide:['wide','landscape','establishing','scene','environment'],detail:['detail','close-up','macro','texture','badge','face'],action:['action','movement','riding','driving','chase','race','speed','bike','ride','motion','dynamic'],hero:['hero','reveal','showcase','portrait','product'],approach:['approach','journey','travel','road','walk','follow']};
function clamp(n,min,max){return Math.max(min,Math.min(n,max));}
function lower(value){return String(value??'').toLowerCase();}
function searchableMedia(m){return lower([m?.name,m?.filename,m?.description,m?.subject?.label,m?.subject?.description,m?.subject,m?.label,m?.contentType].filter(Boolean).join(' '));}
function evidenceScore(m){const v=m?.visualQuality||{};const cinematic=Number(m?.cinematicScore??m?.score);const motion=Math.max(0,...(Array.isArray(m?.bestMoments)?m.bestMoments.map(x=>Number(x.motionScore)||0):[Number(m?.motionScore)||0]));return clamp((Number.isFinite(cinematic)?cinematic:50)*.45+Number(v.detail||0)*18+Number(v.contrast||0)*12+motion*20,0,100);}
function mediaFamily(m){const text=searchableMedia(m);for(const [family,words] of Object.entries(FAMILY_WORDS)){if(words.some(w=>text.includes(w)))return family;}const type=lower(m?.type||m?.mediaType);if(type.startsWith('video'))return'motion';if(type.startsWith('image'))return'frame';return'unknown';}
export function scoreMedia(m){const searchable=searchableMedia(m);let score=50;if(lower(m?.type||m?.mediaType).startsWith('video'))score+=15;if(lower(m?.type||m?.mediaType).startsWith('image'))score+=8;if(Number(m?.duration||m?.durationInSeconds)>0)score+=clamp(Math.min(Number(m.duration||m.durationInSeconds),15)*1.5,0,18);ACTION_WORDS.forEach(w=>{if(searchable.includes(w))score+=3;});HERO_WORDS.forEach(w=>{if(searchable.includes(w))score+=2;});EMOTION_WORDS.forEach(w=>{if(searchable.includes(w))score+=2;});if(Number(m?.score)>0)score+=clamp(Number(m.score)*.2,0,15);score+=evidenceScore(m)*.18;if(m?.width&&m?.height){const ratio=Number(m.width)/Number(m.height);if(ratio>.45&&ratio<2.4)score+=5;if(ratio>.8&&ratio<2)score+=4;}return clamp(Math.round(score),0,100);}
export function classifyMediaSubject(media={}){const text=searchableMedia(media);const rules=[['animal',/animal|dog|puppy|cat|horse|bird|wildlife|pet/],['vehicle',/motorcycle|motorbike|bike|car|vehicle|truck|van|bus|boat|plane|aircraft/],['person',/person|people|rider|driver|traveller|traveler|athlete|dancer|portrait/],['landscape',/landscape|mountain|beach|forest|lake|ocean|city|skyline|sunset|nature/],['product',/product|watch|phone|shoe|clothing|food|drink|advert|commercial/],['event',/event|concert|wedding|party|festival|sport|race/]];const match=rules.find(([,pattern])=>pattern.test(text));return match?match[0]:'unknown';}

export function buildDirectorStory(mediaItems=[],{creativePrompt='',targetDuration=15}={}){
 const items=Array.isArray(mediaItems)?mediaItems:[];if(!items.length)return[];
 const prompt=lower(creativePrompt);const action=/action|fast|race|speed|chase|energetic|adventure/.test(prompt);const reveal=/reveal|launch|unveil|showcase|introduction|trailer/.test(prompt);const emotional=/emotional|beautiful|romantic|nostalgic|heartfelt/.test(prompt);
 const ranked=items.map((media,index)=>({...media,__score:scoreMedia(media),__index:index,__subject:classifyMediaSubject(media)})).sort((a,b)=>b.__score-a.__score);
 const roles=items.length===1?['hero']:items.length===2?['hook','hero']:['hook','build',reveal?'reveal':action?'action':emotional?'emotional-beat':'build','hero'];const chosen=[];const usedSubjects=new Set();
 for(let i=0;i<Math.min(roles.length,ranked.length);i++){const role=roles[i];let best=null;let bestValue=-Infinity;for(const candidate of ranked){if(chosen.some(x=>x.__index===candidate.__index))continue;let value=candidate.__score;const s=searchableMedia(candidate);if(i===0&&/action|movement|hook|impact/.test(s))value+=18;if(role==='hero'&&/hero|reveal|showcase|detail|landscape/.test(s))value+=20;if(role==='action'&&/action|movement|speed|race|ride|drive/.test(s))value+=20;if(role==='reveal'&&/reveal|unveil|showcase|product|vehicle|motorcycle/.test(s))value+=20;if(role==='emotional'&&/beautiful|sunset|landscape|emotion|calm/.test(s))value+=18;if(candidate.__subject!=='unknown'&&usedSubjects.has(candidate.__subject))value-=12;if(value>bestValue){bestValue=value;best=candidate;}}if(best){chosen.push({...best,editorialRole:role});if(best.__subject!=='unknown')usedSubjects.add(best.__subject);}}
 if(chosen.length<Math.min(3,ranked.length))for(const candidate of ranked){if(chosen.some(x=>x.__index===candidate.__index))continue;chosen.push({...candidate,editorialRole:chosen.length===0?'hook':'build'});if(chosen.length>=Math.min(3,ranked.length))break;}
 return chosen.map(({__score,__index,__subject,...media})=>({...media,mediaIndex:Number.isInteger(Number(media.mediaIndex))?Number(media.mediaIndex):__index,directorStoryRole:media.editorialRole,directorStoryScore:__score,targetDuration:Number(targetDuration)||15}));
}
export function buildUniversalMediaProfile(mediaItems=[]){const items=Array.isArray(mediaItems)?mediaItems:[];const profiles=items.map((media,index)=>({index,subjectType:classifyMediaSubject(media),family:mediaFamily(media),score:scoreMedia(media),evidenceScore:evidenceScore(media),type:media?.type||media?.mediaType||'unknown',duration:Number(media?.duration||media?.durationInSeconds)||0,width:Number(media?.width)||0,height:Number(media?.height)||0}));const subjectCounts={};profiles.forEach(p=>{subjectCounts[p.subjectType]=(subjectCounts[p.subjectType]||0)+1;});return{version:'universal-director-v2',mediaCount:profiles.length,subjectCounts,primarySubjectType:Object.entries(subjectCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'unknown',items:profiles};}
export function buildShotMotion(shot={}){const type=lower(shot?.type||shot?.intent||shot?.role||'');const subject=lower(shot?.subjectType||shot?.subject||'unknown');if(type.includes('action')||type.includes('movement'))return{type:subject==='vehicle'?'tracking-push-pan':subject==='person'?'orbit-push':subject==='landscape'?'wide-pan':'push-pan',scale:1.08,duration:Number(shot.duration)||3};if(type.includes('hero')||type.includes('reveal'))return{type:subject==='vehicle'?'slow-arc':subject==='product'?'precision-push':'slow-push',scale:1.05,duration:Number(shot.duration)||3};if(subject==='landscape')return{type:'wide-drift',scale:1.025,duration:Number(shot.duration)||3};if(subject==='person'||subject==='animal')return{type:'gentle-follow',scale:1.03,duration:Number(shot.duration)||3};return{type:'subtle-drift',scale:1.02,duration:Number(shot.duration)||3};}
export function buildShotDirection(shot={}){const subject=lower(shot?.subjectType||shot?.subject||'unknown');const role=lower(shot?.role||shot?.intent||'story-beat');const direction=buildShotMotion({...shot,subjectType:subject});return{subjectType:subject,role,motion:direction,cameraIntent:role==='hero-ending'?'hold-and-settle':role==='hook'?'immediate-attention':role==='action'?'escalate-motion':'controlled-cinematic',preserveSubject:true};}
const STORY_ROLES=['hook','build','action','reveal','hero-ending'];
export function rankMediaForRole(media={},role='story-beat',creativePrompt=''){const base=scoreMedia(media);const text=searchableMedia(media)+' '+lower(creativePrompt);let bonus=0;const r=lower(role);if(r==='hook')bonus+=(ACTION_WORDS.some(w=>text.includes(w))?9:0)+(HERO_WORDS.some(w=>text.includes(w))?4:0);if(r==='build')bonus+=(EMOTION_WORDS.some(w=>text.includes(w))?5:0)+(Number(media?.duration||media?.durationInSeconds)>1?3:0);if(r==='action')bonus+=ACTION_WORDS.reduce((n,w)=>n+(text.includes(w)?2:0),0)+evidenceScore(media)*.12;if(r==='reveal')bonus+=(HERO_WORDS.some(w=>text.includes(w))?8:0)+(Number(media?.width)>Number(media?.height)?3:0);if(r==='hero-ending')bonus+=(HERO_WORDS.some(w=>text.includes(w))?10:0)+(Number(media?.score)>=70?4:0);const family=mediaFamily(media);if((r==='action'&&family==='action')||(r==='reveal'&&family==='hero')||(r==='hero-ending'&&family==='hero'))bonus+=6;if(r==='build'&&family==='approach')bonus+=5;if(r==='hook'&&['wide','action','hero'].includes(family))bonus+=4;return clamp(Math.round(base+bonus),0,100);}
export function buildCoveragePlan(mediaItems=[],options={}){const items=Array.isArray(mediaItems)?mediaItems:[];const prompt=String(options.creativePrompt||'');const maxShots=clamp(Number(options.maxShots)||Math.min(6,items.length),Math.min(1,items.length||1),Math.max(1,items.length||1));if(!items.length)return[];const used=new Set();const usedFamilies=new Set();const plan=[];for(let i=0;i<Math.min(STORY_ROLES.length,maxShots);i++){const role=STORY_ROLES[i];const candidates=items.map((media,index)=>({media,index,subjectType:classifyMediaSubject(media),family:mediaFamily(media),score:rankMediaForRole(media,role,prompt)})).filter(c=>!used.has(c.index)).sort((a,b)=>b.score-a.score||a.index-b.index);const preferred=candidates.find(c=>!usedFamilies.has(c.family)&&c.family!=='unknown')||candidates.find(c=>!plan.some(p=>p.subjectType===c.subjectType))||candidates[0];if(!preferred)break;used.add(preferred.index);if(preferred.family!=='unknown')usedFamilies.add(preferred.family);plan.push({role,mediaIndex:preferred.index,subjectType:preferred.subjectType,family:preferred.family,selectionScore:preferred.score,selectionReason:`${role}: strongest evidenced role fit with coverage diversity`});}return plan;}
export function buildDirectorDecision(mediaItems=[],options={}){const media=Array.isArray(mediaItems)?mediaItems:[];const coverage=buildCoveragePlan(media,options);return{version:'universal-director-decision-v2',creativePrompt:String(options.creativePrompt||''),shotCount:coverage.length,coverage,selectedMedia:coverage.map(c=>media[c.mediaIndex]).filter(Boolean),decisionEvidence:coverage.map(c=>({role:c.role,sourceIndex:c.mediaIndex,score:c.selectionScore,family:c.family,reason:c.selectionReason}))};}

export function rankDirectorCandidates(candidates=[]){
 if(!Array.isArray(candidates))return [];
 const seen=new Set();
 return [...candidates].sort((a,b)=>{
  const as=Number(a?.score??a?.directorSelectionScore??0),bs=Number(b?.score??b?.directorSelectionScore??0);
  const ak=String(a?.subjectRole||a?.subject||a?.mediaIndex||'');
  const bk=String(b?.subjectRole||b?.subject||b?.mediaIndex||'');
  const ap=seen.has(ak)?-8:0,bp=seen.has(bk)?-8:0;
  return (bs+bp)-(as+ap);
 }).map(item=>{const key=String(item?.subjectRole||item?.subject||item?.mediaIndex||'');seen.add(key);return item;});
}

export function buildSubjectAwareMotion(shot={}, subjectType='unknown'){
 const type=String(shot?.type||shot?.intent||'').toLowerCase();
 const subject=String(subjectType||'unknown').toLowerCase();
 const base=buildShotMotion(shot);
 if(subject==='vehicle'&&(/action|movement/.test(type))) return {...base,type:'orbit-push',scale:Math.max(base.scale,1.08),intensity:1.15};
 if(subject==='landscape'&&(/hero|reveal/.test(type))) return {...base,type:'slow-pan',scale:1.04,intensity:.72};
 if(subject==='person'&&/detail|portrait/.test(type)) return {...base,type:'micro-push',scale:1.03,intensity:.62};
 return {...base,intensity:type.includes('action')?1.1:.85};
}
