const ACTION_WORDS=['action','movement','running','walking','riding','driving','accelerating','cornering','chase','jumping','playing','flying','swimming','dancing','travel','journey','speed','race'];
const HERO_WORDS=['hero','reveal','portrait','close-up','landscape','sunset','detail','showcase','beautiful','epic','product','final'];
const EMOTION_WORDS=['smile','laugh','joy','cute','love','dramatic','emotional','surprise','calm','peaceful','excited','mystery','cinematic'];
const FAMILY_WORDS={wide:['wide','landscape','establishing','scene','environment','panorama'],detail:['detail','close-up','macro','texture','badge','face','cockpit'],action:['action','movement','riding','driving','chase','race','speed','cornering'],hero:['hero','reveal','showcase','portrait','product','sunset'],approach:['approach','journey','travel','road','walk','follow','arrival']};
const ROLE_FAMILY_WEIGHTS={hook:{action:14,wide:10,approach:7,hero:6,detail:2},build:{approach:12,wide:9,detail:7,hero:5,action:4},action:{action:18,approach:8,wide:5,hero:3,detail:2},reveal:{hero:18,detail:10,wide:8,approach:5,action:3},'hero-ending':{hero:20,wide:11,detail:8,approach:4,action:2}};
const ROLE_SUBJECT_WEIGHTS={hook:{vehicle:7,person:5,event:4,landscape:3,animal:2,product:2},build:{person:7,landscape:6,vehicle:5,animal:4,product:3,event:3},action:{vehicle:12,person:8,animal:6,event:5,landscape:3,product:2},reveal:{vehicle:10,product:9,person:7,landscape:6,animal:4,event:3},'hero-ending':{vehicle:11,landscape:10,product:9,person:7,animal:5,event:4}};
function clamp(n,min,max){return Math.max(min,Math.min(n,max));}
function lower(value){return String(value??'').toLowerCase();}
function searchableMedia(m){return lower([m?.name,m?.filename,m?.description,m?.subject?.label,m?.subject?.description,m?.subject,m?.label,m?.contentType].filter(Boolean).join(' '));}
function numeric(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function evidenceScore(m){const v=m?.visualQuality||{};const cinematic=numeric(m?.cinematicScore??m?.score,50);const motion=Math.max(0,...(Array.isArray(m?.bestMoments)?m.bestMoments.map(x=>numeric(x?.motionScore||x?.score)):[]),numeric(m?.motionScore));const detail=clamp(numeric(v.detail)*100,0,100);const contrast=clamp(numeric(v.contrast)*100,0,100);const sharpness=clamp(numeric(v.sharpness)*100,0,100);const composition=clamp(numeric(v.composition)*100,0,100);const evidenceParts=[];if(Number.isFinite(cinematic))evidenceParts.push(cinematic*.4);if(detail) evidenceParts.push(detail*.16);if(contrast)evidenceParts.push(contrast*.1);if(sharpness)evidenceParts.push(sharpness*.1);if(composition)evidenceParts.push(composition*.1);if(motion)evidenceParts.push(clamp(motion,0,100)*.14);return clamp(evidenceParts.length?evidenceParts.reduce((a,b)=>a+b,0):50,0,100);}
function mediaFamily(m){const text=searchableMedia(m);for(const [family,words] of Object.entries(FAMILY_WORDS)){if(words.some(w=>text.includes(w)))return family;}const type=lower(m?.type||m?.mediaType);if(type.startsWith('video'))return'motion';if(type.startsWith('image'))return'frame';return'unknown';}
function mediaAspect(m){const width=numeric(m?.width);const height=numeric(m?.height);return width>0&&height>0?width/height:0;}
function promptTerms(prompt){return lower(prompt).split(/[^a-z0-9]+/).filter(t=>t.length>=4);}
function promptMatchScore(m,prompt){const terms=promptTerms(prompt);if(!terms.length)return 0;const text=searchableMedia(m);let hits=0;for(const term of terms)if(text.includes(term))hits++;return clamp((hits/Math.min(terms.length,10))*100,0,100);}
export function scoreMedia(m){const searchable=searchableMedia(m);let score=42;const type=lower(m?.type||m?.mediaType);if(type.startsWith('video'))score+=12;if(type.startsWith('image'))score+=8;const duration=numeric(m?.duration||m?.durationInSeconds);if(duration>0)score+=clamp(Math.min(duration,15)*1.4,0,18);ACTION_WORDS.forEach(w=>{if(searchable.includes(w))score+=2;});HERO_WORDS.forEach(w=>{if(searchable.includes(w))score+=2;});EMOTION_WORDS.forEach(w=>{if(searchable.includes(w))score+=1.5;});if(numeric(m?.score)>0)score+=clamp(numeric(m.score)*.18,0,15);score+=evidenceScore(m)*.2;const ratio=mediaAspect(m);if(ratio>.45&&ratio<2.4)score+=4;if(ratio>.8&&ratio<2)score+=3;return clamp(Math.round(score),0,100);}
export function classifyMediaSubject(media={}){const text=searchableMedia(media);const rules=[['animal',/animal|dog|puppy|cat|horse|bird|wildlife|pet/],['vehicle',/motorcycle|motorbike|bike|car|vehicle|truck|van|bus|boat|plane|aircraft/],['person',/person|people|rider|driver|traveller|traveler|athlete|dancer|portrait/],['landscape',/landscape|mountain|beach|forest|lake|ocean|city|skyline|sunset|nature|road/],['product',/product|watch|phone|shoe|clothing|food|drink|advert|commercial/],['event',/event|concert|wedding|party|festival|sport|race/]];const match=rules.find(([,pattern])=>pattern.test(text));return match?match[0]:'unknown';}
export function buildUniversalMediaProfile(mediaItems=[]){const items=Array.isArray(mediaItems)?mediaItems:[];const profiles=items.map((media,index)=>({index,subjectType:classifyMediaSubject(media),family:mediaFamily(media),score:scoreMedia(media),evidenceScore:evidenceScore(media),promptMatch:0,type:media?.type||media?.mediaType||'unknown',duration:numeric(media?.duration||media?.durationInSeconds),width:numeric(media?.width),height:numeric(media?.height)}));const subjectCounts={};profiles.forEach(p=>{subjectCounts[p.subjectType]=(subjectCounts[p.subjectType]||0)+1;});return{version:'universal-director-v2',mediaCount:profiles.length,subjectCounts,primarySubjectType:Object.entries(subjectCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'unknown',items:profiles};}
export function buildShotMotion(shot={}){const type=lower(shot?.type||shot?.intent||shot?.role||'');const subject=lower(shot?.subjectType||shot?.subject||'unknown');if(type.includes('action')||type.includes('movement'))return{type:subject==='vehicle'?'tracking-push-pan':subject==='person'?'orbit-push':subject==='landscape'?'wide-pan':'push-pan',scale:1.08,duration:numeric(shot.duration,3)};if(type.includes('hero')||type.includes('reveal'))return{type:subject==='vehicle'?'slow-arc':subject==='product'?'precision-push':'slow-push',scale:1.05,duration:numeric(shot.duration,3)};if(subject==='landscape')return{type:'wide-drift',scale:1.025,duration:numeric(shot.duration,3)};if(subject==='person'||subject==='animal')return{type:'gentle-follow',scale:1.03,duration:numeric(shot.duration,3)};return{type:'subtle-drift',scale:1.02,duration:numeric(shot.duration,3)};}
export function buildShotDirection(shot={}){const subject=lower(shot?.subjectType||shot?.subject||'unknown');const role=lower(shot?.role||shot?.intent||'story-beat');const direction=buildShotMotion({...shot,subjectType:subject});return{subjectType:subject,role,motion:direction,cameraIntent:role==='hero-ending'?'hold-and-settle':role==='hook'?'immediate-attention':role==='action'?'escalate-motion':'controlled-cinematic',preserveSubject:true};}
const STORY_ROLES=['hook','build','action','reveal','hero-ending'];
export function rankMediaForRole(media={},role='story-beat',creativePrompt=''){const base=scoreMedia(media);const text=searchableMedia(media)+' '+lower(creativePrompt);const family=mediaFamily(media);const subject=classifyMediaSubject(media);const r=lower(role);let score=base;let reasons=[];const familyBonus=ROLE_FAMILY_WEIGHTS[r]?.[family]||0;if(familyBonus){score+=familyBonus;reasons.push(`${family} family +${familyBonus}`);}const subjectBonus=ROLE_SUBJECT_WEIGHTS[r]?.[subject]||0;if(subjectBonus){score+=subjectBonus;reasons.push(`${subject} subject +${subjectBonus}`);}const promptBonus=promptMatchScore(media,creativePrompt)*.12;if(promptBonus){score+=promptBonus;reasons.push(`prompt evidence +${Math.round(promptBonus)}`);}if(r==='hook'){if(ACTION_WORDS.some(w=>text.includes(w))){score+=7;reasons.push('immediate motion cue +7');}if(HERO_WORDS.some(w=>text.includes(w))){score+=3;reasons.push('visual hook cue +3');}}if(r==='build'){if(EMOTION_WORDS.some(w=>text.includes(w))){score+=5;reasons.push('emotional build cue +5');}if(numeric(media?.duration||media?.durationInSeconds)>1){score+=3;reasons.push('usable duration +3');}}if(r==='action'){const hits=ACTION_WORDS.reduce((n,w)=>n+(text.includes(w)?1:0),0);score+=Math.min(hits*2,10);if(hits)reasons.push(`action evidence +${Math.min(hits*2,10)}`);}if(r==='reveal'){if(HERO_WORDS.some(w=>text.includes(w))){score+=7;reasons.push('reveal cue +7');}if(mediaAspect(media)>1){score+=2;reasons.push('landscape reveal framing +2');}}if(r==='hero-ending'){if(HERO_WORDS.some(w=>text.includes(w))){score+=9;reasons.push('hero cue +9');}if(numeric(media?.score)>=70){score+=4;reasons.push('strong source score +4');}}return clamp(Math.round(score),0,100);}
export function rankDirectorCandidates(mediaItems=[],role='story-beat',options={}){const items=Array.isArray(mediaItems)?mediaItems:[];const prompt=String(options.creativePrompt||'');const usedIndices=new Set(Array.isArray(options.usedIndices)?options.usedIndices:[]);const usedFamilies=new Set(Array.isArray(options.usedFamilies)?options.usedFamilies:[]);const usedSubjects=new Set(Array.isArray(options.usedSubjects)?options.usedSubjects:[]);const candidates=items.map((media,index)=>{const subjectType=classifyMediaSubject(media);const family=mediaFamily(media);const roleScore=rankMediaForRole(media,role,prompt);const evidence=evidenceScore(media);const promptFit=promptMatchScore(media,prompt);let diversityPenalty=0;const reasons=[];if(usedIndices.has(index)){diversityPenalty+=1000;reasons.push('already selected');}if(usedFamilies.has(family)&&family!=='unknown'){diversityPenalty+=9;reasons.push('family repetition -9');}if(usedSubjects.has(subjectType)&&subjectType!=='unknown'){diversityPenalty+=5;reasons.push('subject repetition -5');}const qualityBoost=evidence*.16;const promptBoost=promptFit*.08;const finalScore=clamp(Math.round(roleScore+qualityBoost+promptBoost-diversityPenalty),0,100);if(qualityBoost)reasons.push(`evidence +${Math.round(qualityBoost)}`);if(promptBoost)reasons.push(`prompt fit +${Math.round(promptBoost)}`);return{media,index,subjectType,family,score:finalScore,roleScore,evidenceScore:evidence,promptMatch:promptFit,reasons};}).filter(c=>!usedIndices.has(c.index)).sort((a,b)=>b.score-a.score||b.evidenceScore-a.evidenceScore||a.index-b.index);return candidates;}
export function buildCoveragePlan(mediaItems=[],options={}){const items=Array.isArray(mediaItems)?mediaItems:[];const prompt=String(options.creativePrompt||'');if(!items.length)return[];const requested=Number(options.maxShots);const maxShots=clamp(Number.isFinite(requested)&&requested>0?Math.floor(requested):Math.min(6,items.length),1,items.length);const usedIndices=new Set();const usedFamilies=new Set();const usedSubjects=new Set();const plan=[];for(const role of STORY_ROLES.slice(0,maxShots)){const candidates=rankDirectorCandidates(items,role,{creativePrompt:prompt,usedIndices:[...usedIndices],usedFamilies:[...usedFamilies],usedSubjects:[...usedSubjects]});if(!candidates.length)break;let chosen=candidates[0];if(chosen.family==='unknown'&&candidates.length>1){const diversified=candidates.find(c=>c.family!=='unknown');if(diversified)chosen=diversified;}usedIndices.add(chosen.index);if(chosen.family!=='unknown')usedFamilies.add(chosen.family);if(chosen.subjectType!=='unknown')usedSubjects.add(chosen.subjectType);const reasonParts=[`${role}: role-aware editor selection`,...chosen.reasons.slice(0,4)];plan.push({role,mediaIndex:chosen.index,subjectType:chosen.subjectType,family:chosen.family,selectionScore:chosen.score,selectionReason:reasonParts.join('; '),evidenceScore:Math.round(chosen.evidenceScore),promptMatch:Math.round(chosen.promptMatch)});}return plan;}
export function buildDirectorDecision(mediaItems=[],options={}){const media=Array.isArray(mediaItems)?mediaItems:[];const coverage=buildCoveragePlan(media,options);return{version:'universal-director-decision-v2',creativePrompt:String(options.creativePrompt||''),shotCount:coverage.length,coverage,selectedMedia:coverage.map(c=>media[c.mediaIndex]).filter(Boolean),decisionEvidence:coverage.map(c=>({role:c.role,sourceIndex:c.mediaIndex,score:c.selectionScore,family:c.family,subjectType:c.subjectType,evidenceScore:c.evidenceScore,promptMatch:c.promptMatch,reason:c.selectionReason}))};}
