/* BIKEZTAGRAM AI — universal pre-edit shot selector.
   Never invents media. Balances quality with story coverage, visual variety,
   subject/source diversity, temporal separation and target-duration fit. */
const n=(v,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f};
const text=v=>String(v??'').toLowerCase();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const describe=m=>text([m.description,m.reason,m.action,m.event,m.editorialRole,m.role,m.purpose,m.intent,m.shotType,m.composition,m.framing,m.cameraAngle].join(' '));
const subject=m=>text(m.subjectRole||m.subject||m.identity||m.subjectLabel||m.subjectCategory);
const sourceKey=m=>String(m.mediaId??m.mediaIndex??'unknown');
const startOf=m=>n(m.start??m.startTime,NaN);
const durationOf=m=>{const explicit=n(m.duration,NaN);if(Number.isFinite(explicit))return clamp(explicit,.5,6);const start=startOf(m),end=n(m.end??m.endTime,NaN);return Number.isFinite(start)&&Number.isFinite(end)&&end>start?clamp(end-start,.5,6):2};
function explicitRole(m){const r=[m?.editorialRole,m?.role,m?.purpose,m?.intent].map(text).find(Boolean)||'';if(/hero|hero-ending|final|ending|resolution/.test(r))return'hero';if(/hook|opening|intro/.test(r))return'hook';if(/reveal|unveil|showcase/.test(r))return'reveal';if(/action|chase|impact|movement/.test(r))return'action';if(/build|approach|journey|setup/.test(r))return'build';if(/emotional|emotion|beat/.test(r))return'emotional';return r}
function shotFamily(m){const s=describe(m);if(/extreme close|macro|detail|insert/.test(s))return'detail';if(/close-up|close up|portrait|face|headshot/.test(s))return'close';if(/wide|establish|landscape|aerial|drone|panorama/.test(s))return'wide';if(/medium|mid shot|waist|tracking/.test(s))return'medium';if(/action|chase|race|ride|drive|movement|impact|speed/.test(s))return'action';if(/overhead|top-down|top down|bird's-eye|birds-eye/.test(s))return'overhead';return text(m.shotType)||'general'}
function subjectFamily(m){const s=subject(m);if(!s)return'unknown';if(/motorcycle|motorbike|bike|vehicle|car|truck|machine|product/.test(s))return'object';if(/person|people|rider|driver|character|face|human|man|woman|child|animal|dog|cat|horse|bird|wildlife/.test(s))return'living';if(/landscape|road|street|city|building|environment|scene|location|nature/.test(s))return'environment';return s.slice(0,48)}
function modes(prompt){const p=text(prompt);return{action:/action|fast|race|speed|chase|aggressive|energetic|pursuit|fight|battle/.test(p),emotional:/emotional|beautiful|romantic|heartfelt|nostalgic|sentimental/.test(p),reveal:/reveal|launch|introduc|unveil|showcase|product/.test(p),trailer:/trailer|cinematic|film|movie|teaser|commercial|promo/.test(p),dark:/dark|moody|night|dramatic|gritty|noir|mysterious/.test(p),game:/game|open world|gaming|interactive/.test(p),funny:/funny|comedy|comic|humorous|meme/.test(p)}}
function scoreMoment(m,index,total,mode){const s=describe(m);let score=n(m.score,0)*2;if(/hook|opening|establish/.test(s))score+=18;if(/reveal|unveil|showcase|profile|detail|close-up|macro/.test(s))score+=12;if(/action|movement|moving|speed|race|ride|drive|travel|impact|chase/.test(s))score+=mode.action?20:8;if(/emotion|beautiful|sunset|landscape|reaction|smile|laugh/.test(s))score+=mode.emotional?18:7;if(/hero|ending|resolution|final/.test(s))score+=15;if(index===0)score+=8;if(index===total-1)score+=6;if(m.shotType)score+=5;if(m.confidence!=null)score+=n(m.confidence,.5)*8;if(mode.reveal&&/product|vehicle|motorcycle|bike/.test(s))score+=8;if(mode.trailer&&/hero|reveal|establish|action/.test(s))score+=5;if(mode.game&&/world|environment|vehicle|character|action/.test(s))score+=5;const role=explicitRole(m);if(role)score+=role==='hook'||role==='hero'?10:role==='reveal'||role==='action'?8:5;return score}
function desiredRole(position,total,mode){if(position===0)return'hook';if(position===total-1)return'hero';const ratio=position/Math.max(1,total-1);if(ratio<.34)return'build';if(mode.reveal&&ratio<.62)return'reveal';if(mode.action&&ratio<.78)return'action';if(mode.emotional&&ratio>.55)return'emotional';return'variation'}
function roleBonus(m,role){const s=describe(m),e=explicitRole(m);if(e===role)return role==='hook'||role==='hero'?32:26;if((role==='hero'&&e==='hook')||(role==='hook'&&e==='hero'))return-24;if(role==='hook')return/hook|opening|establish|impact|action|reveal/.test(s)?24:0;if(role==='hero')return/hero|ending|resolution|final|showcase|reveal|portrait|landscape/.test(s)?24:0;if(role==='build')return/movement|tracking|journey|road|approach|detail|medium|wide/.test(s)?10:0;if(role==='reveal')return/reveal|unveil|showcase|profile|product|vehicle|portrait/.test(s)?18:0;if(role==='action')return/action|movement|speed|race|ride|drive|chase|impact/.test(s)?18:0;if(role==='emotional')return/emotion|beautiful|sunset|landscape|reaction|smile|laugh|calm/.test(s)?16:0;return 0}
function durationFit(m,used,target,remainingSlots){const d=durationOf(m),remaining=Math.max(0,n(target,15)-used);let v=0;if(remaining>0){const gap=Math.abs(d-Math.min(remaining,3));v+=Math.max(0,8-gap*3);if(d<=remaining+.75)v+=5;else v-=Math.min(14,(d-remaining)*5)}if(remainingSlots===1)v+=Math.max(-12,12-Math.abs((used+d)-Math.max(1,n(target,15)))*5);return v}
function similarity(a,b){const aw=new Set(describe(a).split(/\W+/).filter(x=>x.length>4)),bw=new Set(describe(b).split(/\W+/).filter(x=>x.length>4));let common=0;for(const x of aw)if(bw.has(x))common++;return common/Math.max(1,Math.min(aw.size,bw.size))}
export function selectDirectorMoments(moments,{maxCuts=8,targetDuration=15,creativePrompt=''}={}){if(!Array.isArray(moments)||!moments.length)return[];const mode=modes(creativePrompt),ranked=moments.map((m,i)=>({...m,__score:scoreMoment(m,i,moments.length,mode),__family:shotFamily(m),__subject:subjectFamily(m),__duration:durationOf(m)})).sort((a,b)=>b.__score-a.__score),limit=Math.min(Math.max(1,maxCuts),ranked.length),chosen=[],sources=new Set(),families=new Map(),subjects=new Map();let usedDuration=0;const pool=[...ranked];while(chosen.length<limit&&pool.length){let bi=0,best=-Infinity,role=desiredRole(chosen.length,limit,mode);for(let i=0;i<pool.length;i++){const m=pool[i];let v=m.__score+roleBonus(m,role)+durationFit(m,usedDuration,targetDuration,limit-chosen.length);const src=sourceKey(m),fc=families.get(m.__family)||0,sc=subjects.get(m.__subject)||0;if(sources.has(src))v-=12;if(fc)v-=12*fc;if(sc&&m.__subject!=='unknown')v-=clamp(9*sc,9,24);if(chosen.length&&similarity(m,chosen[chosen.length-1])>.65)v-=18;if(chosen.some(c=>{const a=startOf(c),b=startOf(m);return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<1.25}))v-=12;if(!fc&&chosen.length)v+=7;if(!sc&&m.__subject!=='unknown'&&chosen.length)v+=5;if(v>best){best=v;bi=i}}const pick=pool.splice(bi,1)[0];chosen.push(pick);sources.add(sourceKey(pick));families.set(pick.__family,(families.get(pick.__family)||0)+1);subjects.set(pick.__subject,(subjects.get(pick.__subject)||0)+1);usedDuration+=pick.__duration}chosen.sort((a,b)=>startOf(a)-startOf(b));if(chosen.length>1){chosen[0]={...chosen[0],editorialRole:chosen[0].editorialRole||'hook'};chosen[chosen.length-1]={...chosen[chosen.length-1],editorialRole:chosen[chosen.length-1].editorialRole||'hero-ending'}}return chosen.map(({__score,__family,__subject,__duration,...m},i)=>({...m,directorSelectionScore:Number(__score.toFixed(1)),directorSelectionIndex:i,directorShotFamily:shotFamily(m),directorSubjectFamily:subjectFamily(m)}))}
