/* BIKEZTAGRAM AI — safe director-to-render execution normalizer.
   Enriches executable cuts without replacing the director's chosen media. */
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const number=(value,fallback)=>{const n=Number(value);return Number.isFinite(n)?n:fallback;};
const text=(value)=>String(value||'').toLowerCase();
const sourceId=(cut)=>cut?.mediaId!=null&&String(cut.mediaId).trim()?String(cut.mediaId):Number.isInteger(Number(cut?.mediaIndex))?`media:${Number(cut.mediaIndex)}`:'unknown';
const intentText=(cut,plan)=>text([cut?.purpose,cut?.intent,cut?.role,cut?.editorialRole,plan?.creativePrompt].join(' '));
function roleFor(index,total,plan){const explicit=text(plan?.cuts?.[index]?.editorialRole||plan?.cuts?.[index]?.role);if(explicit)return explicit;if(index===0)return'hook';if(index===total-1)return'hero-ending';const p=intentText(plan?.cuts?.[index]||{},plan);if(/reveal|unveil|showcase/.test(p))return'reveal';if(/action|chase|race|speed|impact|ride|drive/.test(p))return'action';if(/build|approach|journey|setup/.test(p))return'build';return'story-beat';}
function motionFor(cut,role){if(cut?.motionStyle&&cut.motionStyle!=='static')return cut.motionStyle;const s=text([cut?.purpose,cut?.intent,role].join(' '));if(/action|chase|race|speed|impact|ride|drive/.test(s))return role==='action'?'zoom-punch':'pan-right';if(role==='hook')return'slow-push';if(role==='hero-ending')return'slow-pull';if(/reveal|showcase|detail/.test(s))return'slow-push';return'pan-right';}
function transitionFor(cut,index,total,plan){if(cut?.transition&&cut.transition!=='hard-cut')return cut.transition;if(index===0)return'fade-in';if(index===total-1)return text(plan?.creativePrompt).includes('dark')?'dip-black':'fade-out';const s=intentText(cut,plan);if(/action|chase|race|speed|impact/.test(s))return index%2?'whip-right':'zoom-punch';if(/emotional|beautiful|romantic/.test(s))return'crossfade';return index%3===0?'crossfade':'hard-cut';}
function normalizeDuration(cut){return Number(clamp(number(cut?.duration,2),.5,6).toFixed(3));}
export function buildExecutableTimeline(plan,{targetDuration=15}={}){const sourceCuts=Array.isArray(plan?.cuts)?plan.cuts:Array.isArray(plan?.scenes)?plan.scenes:[];if(!sourceCuts.length)return{...plan,cuts:[],targetDuration};const total=sourceCuts.length;const cuts=sourceCuts.map((raw,index)=>{const cut={...raw};const role=roleFor(index,total,plan);const source=sourceId(cut);cut.role=cut.role||role;cut.editorialRole=cut.editorialRole||role;cut.motionStyle=motionFor(cut,role);cut.motionIntensity=Number(clamp(number(cut.motionIntensity,1),.35,1.6).toFixed(2));cut.transition=transitionFor(cut,index,total,plan);cut.duration=normalizeDuration(cut);cut.speed=Number(clamp(number(cut.speed,1),.5,1.75).toFixed(2));cut.speedEnd=Number(clamp(number(cut.speedEnd,cut.speed),.5,1.75).toFixed(2));cut.sourceType=cut.sourceType||'uploaded';cut.directorExecution={...(cut.directorExecution||{}),sourceId:source,role,motionStyle:cut.motionStyle,motionIntensity:cut.motionIntensity,transition:cut.transition,duration:cut.duration,speed:cut.speed,speedEnd:cut.speedEnd,preserveDirectorMedia:true};return cut;});return{...plan,cuts,targetDuration:Number(clamp(number(plan?.targetDuration,targetDuration),1,120).toFixed(2)),executionVersion:'director-execution-v1'};}
export function validateExecutableTimeline(plan){const cuts=Array.isArray(plan?.cuts)?plan.cuts:[];const failures=[];if(!cuts.length)failures.push('no-cuts');cuts.forEach((cut,index)=>{if(sourceId(cut)==='unknown'&&!cut.generated)failures.push(`cut-${index}-missing-source`);if(!cut.role)failures.push(`cut-${index}-missing-role`);if(!cut.motionStyle)failures.push(`cut-${index}-missing-motion`);if(!cut.transition)failures.push(`cut-${index}-missing-transition`);if(number(cut.duration,0)<=0)failures.push(`cut-${index}-invalid-duration`);});return{passed:failures.length===0,failures};}
