/* BIKEZTAGRAM AI — safe director-to-render execution normalizer.
   Keeps source identity while making editorial timing, motion, transitions and
   render handoff deterministic and provider-neutral. */
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const number=(value,fallback)=>{const n=Number(value);return Number.isFinite(n)?n:fallback;};
const text=(value)=>String(value??'').toLowerCase();
const sourceId=(cut)=>cut?.mediaId!=null&&String(cut.mediaId).trim()?String(cut.mediaId):Number.isInteger(Number(cut?.mediaIndex))?`media:${Number(cut.mediaIndex)}`:cut?.sourceId?String(cut.sourceId):'unknown';
const intentText=(cut,plan)=>text([cut?.purpose,cut?.intent,cut?.role,cut?.editorialRole,plan?.creativePrompt].join(' '));
function roleFor(index,total,plan){const explicit=text(plan?.cuts?.[index]?.editorialRole||plan?.cuts?.[index]?.role);if(explicit)return explicit;if(index===0)return'hook';if(index===total-1)return'hero-ending';const p=intentText(plan?.cuts?.[index]||{},plan);if(/reveal|unveil|showcase/.test(p))return'reveal';if(/action|chase|race|speed|impact|ride|drive/.test(p))return'action';if(/build|approach|journey|setup/.test(p))return'build';return'story-beat';}
function motionFor(cut,role){if(cut?.motionStyle&&cut.motionStyle!=='static')return cut.motionStyle;const s=text([cut?.purpose,cut?.intent,role].join(' '));if(/action|chase|race|speed|impact|ride|drive/.test(s))return role==='action'?'zoom-punch':'pan-right';if(role==='hook')return'slow-push';if(role==='hero-ending')return'slow-pull';if(/reveal|showcase|detail/.test(s))return'slow-push';return'pan-right';}
function transitionFor(cut,index,total,plan){if(cut?.transition&&cut.transition!=='hard-cut')return cut.transition;if(index===0)return'fade-in';if(index===total-1)return text(plan?.creativePrompt).includes('dark')?'dip-black':'fade-out';const s=intentText(cut,plan);if(/action|chase|race|speed|impact/.test(s))return index%2?'whip-right':'zoom-punch';if(/emotional|beautiful|romantic/.test(s))return'crossfade';return index%3===0?'crossfade':'hard-cut';}
function normalizeDuration(cut){return Number(clamp(number(cut?.duration,2),.5,6).toFixed(3));}
function normalizeTrim(cut){const start=Math.max(0,number(cut?.trimStart,number(cut?.start,0)));const endRaw=number(cut?.trimEnd,number(cut?.end,NaN));const duration=normalizeDuration(cut);const end=Number.isFinite(endRaw)&&endRaw>start?endRaw:start+duration;return{trimStart:Number(start.toFixed(3)),trimEnd:Number(end.toFixed(3))};}
function normalizeTransform(cut){const t=cut?.transform||{};return{scale:Number(clamp(number(t.scale,1),.5,3).toFixed(3)),x:Number(clamp(number(t.x,0),-1,1).toFixed(3)),y:Number(clamp(number(t.y,0),-1,1).toFixed(3)),rotation:Number(clamp(number(t.rotation,0),-180,180).toFixed(2))};}
function normalizeTimelineDuration(cuts,target){if(!cuts.length)return cuts;const desired=clamp(number(target,15),1,120);const sum=cuts.reduce((s,c)=>s+c.duration,0);if(!sum)return cuts;const factor=desired/sum;const weighted=cuts.map(c=>{const raw=c.duration*factor;return{...c,duration:Number(clamp(raw,.5,6).toFixed(3)),_fraction:raw};});let delta=Number((desired-weighted.reduce((s,c)=>s+c.duration,0)).toFixed(3));const order=[...weighted.keys()].sort((a,b)=>weighted[b]._fraction-weighted[a]._fraction);for(const i of order){if(Math.abs(delta)<.001)break;const next=Number(clamp(weighted[i].duration+delta,.5,6).toFixed(3));delta=Number((delta-(next-weighted[i].duration)).toFixed(3));weighted[i].duration=next;}return weighted.map(({_fraction,...c})=>c);}
function frameLedger(cuts,targetDuration,fps){const rate=Math.round(clamp(number(fps,30),1,120));const targetFrames=Math.max(1,Math.round(clamp(number(targetDuration,15),1,120)*rate));let cursor=0;const framed=cuts.map(c=>{const durationFrames=Math.max(1,Math.round(c.duration*rate));const startFrame=cursor;const endFrame=startFrame+durationFrames;cursor=endFrame;const trimStartFrame=Math.max(0,Math.round(c.trimStart*rate));const trimEndFrame=Math.max(trimStartFrame+1,Math.round(c.trimEnd*rate));return{...c,startFrame,endFrame,durationFrames,trimStartFrame,trimEndFrame,directorExecution:{...c.directorExecution,startFrame,endFrame,durationFrames,trimStartFrame,trimEndFrame,fps:rate}};});if(framed.length){const delta=targetFrames-cursor;const last=framed[framed.length-1];const adjusted=Math.max(1,last.durationFrames+delta);framed[framed.length-1]={...last,durationFrames:adjusted,endFrame:last.startFrame+adjusted,duration:Number((adjusted/rate).toFixed(3)),directorExecution:{...last.directorExecution,durationFrames:adjusted,endFrame:last.startFrame+adjusted,duration:Number((adjusted/rate).toFixed(3))}};}return{cuts:framed,fps:rate,totalFrames:framed.length?framed[framed.length-1].endFrame:0,targetFrames};}
export function buildExecutableTimeline(plan,{targetDuration=15,fps=30}={}){const sourceCuts=Array.isArray(plan?.cuts)?plan.cuts:Array.isArray(plan?.scenes)?plan.scenes:[];if(!sourceCuts.length)return{...plan,cuts:[],targetDuration,fps:Math.round(clamp(number(fps,30),1,120)),totalFrames:0};const total=sourceCuts.length;let cuts=sourceCuts.map((raw,index)=>{const cut={...raw};const role=roleFor(index,total,plan);const source=sourceId(cut);const trim=normalizeTrim(cut);cut.role=cut.role||role;cut.editorialRole=cut.editorialRole||role;cut.motionStyle=motionFor(cut,role);cut.motionIntensity=Number(clamp(number(cut.motionIntensity,1),.35,1.6).toFixed(2));cut.transition=transitionFor(cut,index,total,plan);cut.duration=normalizeDuration(cut);cut.speed=Number(clamp(number(cut.speed,1),.5,1.75).toFixed(2));cut.speedEnd=Number(clamp(number(cut.speedEnd,cut.speed),.5,1.75).toFixed(2));cut.trimStart=trim.trimStart;cut.trimEnd=trim.trimEnd;cut.transform=normalizeTransform(cut);cut.sourceType=cut.sourceType||'uploaded';cut.directorExecution={...(cut.directorExecution||{}),sourceId:source,role,motionStyle:cut.motionStyle,motionIntensity:cut.motionIntensity,transition:cut.transition,duration:cut.duration,speed:cut.speed,speedEnd:cut.speedEnd,trimStart:trim.trimStart,trimEnd:trim.trimEnd,transform:cut.transform,preserveDirectorMedia:true};return cut;});
const resolvedDuration=Number(clamp(number(plan?.targetDuration,targetDuration),1,120).toFixed(2));cuts=normalizeTimelineDuration(cuts,resolvedDuration);const ledger=frameLedger(cuts,resolvedDuration,plan?.outputFps??plan?.fps??fps);cuts=ledger.cuts;return{...plan,cuts,targetDuration:resolvedDuration,fps:ledger.fps,totalFrames:ledger.totalFrames,frameAccurate:true,executionVersion:'director-execution-v3'};}
export function validateExecutableTimeline(plan){const cuts=Array.isArray(plan?.cuts)?plan.cuts:[];const failures=[];if(!cuts.length)failures.push('no-cuts');const fps=number(plan?.fps,0);if(!Number.isInteger(fps)||fps<1||fps>120)failures.push('invalid-fps');if(!Number.isInteger(plan?.totalFrames)||plan.totalFrames<1)failures.push('invalid-total-frames');let cursor=0;cuts.forEach((cut,index)=>{if(sourceId(cut)==='unknown'&&!cut.generated)failures.push(`cut-${index}-missing-source`);if(!cut.role)failures.push(`cut-${index}-missing-role`);if(!cut.motionStyle)failures.push(`cut-${index}-missing-motion`);if(!cut.transition)failures.push(`cut-${index}-missing-transition`);if(number(cut.duration,0)<=0)failures.push(`cut-${index}-invalid-duration`);if(number(cut.trimEnd,0)<=number(cut.trimStart,0))failures.push(`cut-${index}-invalid-trim`);if(number(cut.speed,0)<=0||number(cut.speedEnd,0)<=0)failures.push(`cut-${index}-invalid-speed`);if(!Number.isInteger(cut.startFrame)||cut.startFrame!==cursor)failures.push(`cut-${index}-invalid-frame-start`);if(!Number.isInteger(cut.endFrame)||cut.endFrame<=cut.startFrame)failures.push(`cut-${index}-invalid-frame-end`);if(cut.endFrame-cut.startFrame!==cut.durationFrames)failures.push(`cut-${index}-frame-duration-mismatch`);if(!Number.isInteger(cut.trimStartFrame)||!Number.isInteger(cut.trimEndFrame)||cut.trimEndFrame<=cut.trimStartFrame)failures.push(`cut-${index}-invalid-trim-frames`);cursor=cut.endFrame;});if(cuts.length&&cursor!==plan.totalFrames)failures.push('timeline-frame-total-mismatch');return{passed:failures.length===0,failures};}
