/* Bikeztagram AI — provider-neutral music director. The director stays ours; only the renderer is replaceable. */
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||a));
const GENRES=[['drum and bass',/drum.?and.?bass|dnb|jungle/i],['hip-hop',/hip.?hop|rap|trap|808/i],['rock',/rock|guitar|band|punk|grunge|metal/i],['country',/country|western|twang|honky|americana/i],['pop',/pop|radio|anthem/i],['dance',/edm|house|techno|dance|electronic|trance/i],['indie',/indie|alternative/i],['cinematic',/cinematic|orchestral|film|score|trailer/i]];
const MOODS=[['dark',/dark|moody|gritty|menacing|noir|night/i],['uplifting',/happy|bright|uplifting|joy|summer|feel.?good/i],['emotional',/sad|emotional|melancholy|heartbreak|moving/i],['dreamy',/dreamy|ambient|ethereal|peaceful|calm/i],['energetic',/energetic|driving|racing|action|powerful|aggressive/i]];
function pick(list,text,fallback){return list.find(([,rx])=>rx.test(text))?.[0]||fallback;}
function clean(text){return String(text||'').replace(/\s+/g,' ').trim();}
function titleCase(s){return s.replace(/\b\w/g,c=>c.toUpperCase());}
export function compileMusicRequest({prompt='',lyrics='',duration=30,bpm='auto',key='auto',mode='auto',vocalLanguage='en',vocalDirection='',forceInstrumental=false}={}){
 const p=clean(prompt),genre=pick(GENRES,p,'cinematic'),mood=pick(MOODS,p,'cinematic');
 const tempo=bpm==='auto'?'adaptive':clamp(bpm,55,190);
 const sections=Number(duration)>=90?['intro','verse','pre-chorus','chorus','verse','bridge','final chorus','outro']:Number(duration)>=45?['intro','verse','chorus','verse','chorus','outro']:['intro','verse','chorus','outro'];
 const instruction=['Original song for Bikeztagram AI.','Genre: '+genre+'. Mood: '+mood+'.',tempo==='adaptive'?'Tempo: choose a natural tempo that matches the brief.':'Tempo: '+tempo+' BPM.',key!=='auto'?'Key centre: '+String(key)+'.':'',mode!=='auto'?'Mode: '+String(mode)+'.':'',vocalDirection?'Vocal direction: '+clean(vocalDirection)+'.':'',forceInstrumental?'Instrumental only; no sung lead.':'Clear melodic lead vocal with intelligible lyrics.','Structure: '+sections.join(' → ')+'.','Use strong musical development, memorable motifs, real section contrast, a convincing chorus lift and a deliberate ending.','Do not imitate a named artist, existing recording or copyrighted song. Create a new production.'].filter(Boolean).join(' ');
 return {version:'music-director-v1',prompt:p,genre,mood,duration:clamp(duration,5,300),bpm:tempo,key,mode,vocalLanguage,forceInstrumental:Boolean(forceInstrumental),sections,lyrics:clean(lyrics),instruction};
}
function topicWords(prompt){const p=clean(prompt).replace(/[^a-zA-Z0-9' ]/g,' ').split(/\s+/).filter(Boolean);return p.filter(w=>w.length>3&&!/^(make|song|music|about|with|that|this|into|from|like|style|please|create|original)$/i.test(w)).slice(0,8);}
export function generateDirectorLyrics(brief={}){
 if(brief.forceInstrumental)return '[Intro]\n(instrumental)\n[Verse]\n(instrumental)\n[Chorus]\n(instrumental)';
 if(brief.lyrics)return brief.lyrics;
 const topic=topicWords(brief.prompt),subject=topic.length?topic.join(' '):'the road tonight',mood=brief.mood||'cinematic';
 const banks={dark:['Under the midnight sky, the city holds its breath','Every shadow moves like it remembers what we left','No turning back, no looking down','We light the dark and own this town'],uplifting:['Feel the world open wide beneath our feet','Every little heartbeat finds the beat','We rise together, higher than before','Open up the night and give us more'],emotional:['Hold this moment close before it fades away','Every road remembers every word we could not say','If the night gets heavy, stay with me','There is still a light ahead that we can see'],dreamy:['Drift with the lights while the whole world slows','Follow the feeling wherever it goes','Let the night breathe, let the colours run','We are still here underneath the sun'],energetic:['Turn it up, let the whole room shake','Every heartbeat hits like an earthquake','No brakes tonight, we are moving fast','Make this moment something built to last'],cinematic:['The night begins to move, a spark becomes a flame','The road is calling and it knows us by name','We cross the line where the old world ends','And start again with fire in our hands']};
 const b=banks[mood]||banks.cinematic,hook=titleCase(subject.split(' ').slice(0,5).join(' '));
 return ['[Verse 1]',b[0],b[1],'We carry '+subject+' through the night','[Pre-Chorus]',b[2],b[3],'[Chorus]',hook+' tonight',b[3],b[0],hook+' tonight','[Verse 2]',b[1],'We keep the rhythm underneath our feet',b[0],'[Bridge]','Everything we were is turning into now','Let the music rise and pull us through the crowd','[Final Chorus]',hook+' tonight',b[3],b[0],hook+' tonight'].join('\n');
}
export function prepareMusicGeneration(input={}){const brief=compileMusicRequest(input);return {...brief,lyrics:generateDirectorLyrics(brief)};}
export function getConfiguredMusicEngineUrl(){return String(import.meta?.env?.VITE_MUSIC_ENGINE_URL||'').trim().replace(/\/$/,'');}
