const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),num=(v,d)=>Number.isFinite(Number(v))?Number(v):d;
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const rng=seed=>{let s=seed>>>0||1;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296}};
const ROOTS={c:0,'c#':1,db:1,d:2,'d#':3,eb:3,e:4,f:5,'f#':6,gb:6,g:7,'g#':8,ab:8,a:9,'a#':10,bb:10,b:11};
const SCALES={major:[0,2,4,5,7,9,11],minor:[0,2,3,5,7,8,10],dorian:[0,2,3,5,7,9,10],phrygian:[0,1,3,5,7,8,10],pentatonic:[0,2,4,7,9]};
const P={'vocal-trance':{bpm:138,mode:'minor',drum:'four',bass:'offbeat',lead:'vocal',pad:'wide'},electronic:{bpm:128,mode:'minor',drum:'four',bass:'offbeat',lead:'arp',pad:'wide'},dnb:{bpm:174,mode:'minor',drum:'break',bass:'rolling',lead:'pluck',pad:'dark'},hiphop:{bpm:92,mode:'minor',drum:'boom',bass:'808',lead:'pluck',pad:'dusty'},rock:{bpm:124,mode:'minor',drum:'rock',bass:'picked',lead:'guitar',pad:'wide'},indie:{bpm:116,mode:'major',drum:'rock',bass:'picked',lead:'guitar',pad:'wide'},cinematic:{bpm:118,mode:'minor',drum:'hybrid',bass:'cinematic',lead:'strings',pad:'orchestral'},orchestral:{bpm:108,mode:'minor',drum:'hybrid',bass:'cinematic',lead:'strings',pad:'orchestral'}};
function detectPrompt(prompt=''){const p=String(prompt).toLowerCase();let genre=/vocal\s*trance|trance/.test(p)?'vocal-trance':/dnb|drum.?and.?bass|jungle/.test(p)?'dnb':/hip.?hop|trap|808|rap/.test(p)?'hiphop':/indie/.test(p)?'indie':/rock|guitar|band/.test(p)?'rock':/techno|edm|electronic|house|dance|synth/.test(p)?'electronic':/orchestral|score/.test(p)?'orchestral':'cinematic';const mood=/dark|moody|gritty|noir|menacing|night/.test(p)?'dark':/happy|bright|uplifting|summer|joy/.test(p)?'uplifting':/sad|emotional|melancholy|heart/.test(p)?'emotional':/ambient|peaceful|calm|dreamy/.test(p)?'ambient':'cinematic';const energy=/hyper|extremely fast|very fast|aggressive|racing/.test(p)?'extreme':/fast|energetic|action|chase|driving/.test(p)?'high':/slow|calm|ambient|peaceful|emotional/.test(p)?'low':'medium';const mode=/dorian/.test(p)?'dorian':/phrygian/.test(p)?'phrygian':/major|uplifting|happy|bright/.test(p)?'major':P[genre]?.mode||'minor';const m=p.match(/\b(c#|db|d#|eb|f#|gb|g#|ab|a#|bb|[a-g])\s*(?:minor|major|m)?\b/);return{genre,mood,energy,mode,root:m?.[1]||(mood==='uplifting'?'d':mood==='dark'?'f#':'a')}}
export function createMusicBrief({prompt='',duration=30,bpm='auto',key='auto',mode='auto',seed=''}={}){const d=detectPrompt(prompt),p=P[d.genre]||P.cinematic,t=bpm==='auto'?p.bpm+(d.energy==='high'?4:d.energy==='extreme'?12:d.energy==='low'?-8:0):clamp(num(bpm,p.bpm),55,190),k=key==='auto'?d.root:String(key).toLowerCase();return{version:'music-studio-v4',prompt:String(prompt),duration:clamp(num(duration,30),3,600),bpm:t,key:k,mode:mode==='auto'?d.mode:mode,mood:d.mood,genre:d.genre,energy:d.energy,seed:seed||hash(`${prompt}|${duration}|${t}|${k}`),copyright:{originalOnly:true,noKnownSongImitation:true,noExternalAudioSamples:true}}}
const note=(root,scale,d,oct=4)=>12*(oct+Math.floor(d/scale.length)+1)+root+scale[((d%scale.length)+scale.length)%scale.length];
export function composeFullMusic(input={}){const b=input.version?input:createMusicBrief(input),p=P[b.genre]||P.cinematic,root=ROOTS[b.key]??0,scale=SCALES[b.mode]||SCALES.minor,beat=60/b.bpm,bar=beat*4,r=rng(hash(`${b.seed}|v4`)),names=b.duration<12?['intro','build','climax','outro']:['intro','build','lift','climax','outro'],ratios=names.length===5?[.12,.2,.22,.3,.16]:[.18,.24,.38,.2];let cur=0;const sections=names.map((name,i)=>{const st=cur,en=i===names.length-1?b.duration:Math.min(b.duration,cur+b.duration*ratios[i]);cur=en;return{name,start:+st.toFixed(3),end:+en.toFixed(3),density:clamp(name==='climax'?1:.35+i*.12,.25,1),energy:clamp(name==='intro'?.35:name==='climax'?1:.55+i*.1,.25,1),swing:0}}),prog=b.mode==='major'?[0,4,5,3]:b.mode==='dorian'?[0,3,4,1]:b.mode==='phrygian'?[0,5,2,4]:[0,5,3,4],chords=prog.map((d,i)=>({index:i,degree:d,rootMidi:note(root,scale,d,3),tones:[note(root,scale,d,3),note(root,scale,d+2,3),note(root,scale,d+4,3),note(root,scale,d+6,3)]})),events=[],melody=[],bass=[],drums=[],harmony=[],fx=[];
for(const s of sections){for(let t=s.start,bn=0;t<s.end;bn++,t+=bar){const chord=chords[bn%4],i=s.energy;events.push({time:+t.toFixed(3),type:'section',section:s.name,intensity:+i.toFixed(3)});for(let q=0;q<16;q++){const bt=t+q*beat/4;if(bt>=s.end)break;let kick=p.drum==='four'?q%4===0||s.name==='climax'&&q%4===3:p.drum==='break'?[0,6,10,14].includes(q):p.drum==='boom'?[0,7,10,14].includes(q):p.drum==='rock'?[0,6,8,12].includes(q):[0,6,8,12].includes(q);let sn=[4,12].includes(q);if(p.drum==='break'&&s.name==='climax')sn=sn||q===14;if(kick)drums.push({time:+bt.toFixed(3),type:'kick',velocity:+clamp(.58+i*.36+(r()-.5)*.06,.35,.98).toFixed(3)});if(sn)drums.push({time:+bt.toFixed(3),type:'snare',velocity:+clamp(.5+i*.4,.35,.95).toFixed(3)});if(q%2===0)drums.push({time:+bt.toFixed(3),type:'hat',velocity:+(.13+i*.18+(q%4===2?.05:0)).toFixed(3)});if(s.name==='climax'&&q%4===3)drums.push({time:+bt.toFixed(3),type:'openhat',velocity:.28})}
for(let bi=0;bi<4;bi++){const bt=t+bi*beat;if(bt>=s.end)break;events.push({time:+bt.toFixed(3),type:'beat',section:s.name,accent:bi===0||s.name==='climax',intensity:+i.toFixed(3)});const d=chord.degree+(bi===2?4:0);if(p.bass==='offbeat')bass.push({time:+(bt+beat*.5).toFixed(3),duration:+(beat*.44).toFixed(3),midi:note(root,scale,chord.degree,2),velocity:+(.46+i*.35).toFixed(3),style:'offbeat'});else bass.push({time:+bt.toFixed(3),duration:+(beat*.8).toFixed(3),midi:note(root,scale,d,2),velocity:+(.45+i*.38).toFixed(3),style:p.bass});if(s.name!=='intro'||bn){const seq=p.lead==='guitar'?[0,2,4,2]:p.lead==='strings'?[0,2,3,4]:[0,2,4,5,4,2];if(r()<.7)melody.push({time:+bt.toFixed(3),duration:+(beat*(bi===3?.7:.4)).toFixed(3),midi:note(root,scale,chord.degree+seq[(bn*4+bi)%seq.length],5),velocity:+(.44+i*.42).toFixed(3),style:p.lead})}}
for(let j=0;j<4;j++)harmony.push({time:+t.toFixed(3),duration:+Math.min(s.end-t,bar*.96).toFixed(3),midi:chord.tones[j]+12,velocity:+(.13+i*.11).toFixed(3),pan:[-.55,-.18,.18,.55][j],style:p.pad});if(s.name==='build'||s.name==='lift')fx.push({time:+Math.max(s.start,s.end-beat*2).toFixed(3),type:'riser',duration:+(beat*1.8).toFixed(3),velocity:.3});if(s.name==='climax')fx.push({time:+s.start.toFixed(3),type:'impact',duration:.55,velocity:.7})}}
if(b.genre==='vocal-trance')for(const s of sections.filter(x=>x.name==='lift'||x.name==='climax'))for(let j=0;j<4;j++)harmony.push({time:+(s.start+j*beat).toFixed(3),duration:+(beat*1.8).toFixed(3),midi:note(root,scale,4+j%2,4),velocity:.07,pan:j%2?.3:-.3,style:'vocal'});
return{brief:b,sections,chords,events,melody,bass,drums,harmony,fx,beatGrid:Array.from({length:Math.ceil(b.duration/beat)+1},(_,i)=>+(i*beat).toFixed(3)),stems:{drums:true,bass:true,harmony:true,melody:true,fx:true}}}
const freq=m=>440*Math.pow(2,(m-69)/12),env=(x,d)=>x<.008?x/.008:x>d-.14?Math.max(0,(d-x)/.14):1,clip=x=>Math.tanh(x*1.25),noise=r=>r()*2-1;
function tone(L,R,sr,t,d,f,g,kind,pan=0){const a=Math.max(0,Math.floor(t*sr)),z=Math.min(L.length,Math.ceil((t+d)*sr));for(let i=a;i<z;i++){const x=(i-a)/sr,ph=2*Math.PI*f*x,s=Math.sin(ph),s2=Math.sin(ph*2),s3=Math.sin(ph*3),saw=2*((f*x)%1)-1;let w=kind==='supersaw'?.42*saw+.23*Math.sin(ph*.996)+.23*Math.sin(ph*1.004)+.12*s2:kind==='guitar'?.5*saw+.3*s2+.15*s3:kind==='pluck'?.58*s+.28*s2+.1*s3:kind==='vocal'?.55*s+.28*s2+.12*s3:.7*s+.22*s2+.08*s3;const v=w*g*env(x,d);L[i]+=v*(1-pan*.7);R[i]+=v*(1+pan*.7)}}
function nse(L,R,sr,t,d,g,pan,type,seed){const a=Math.max(0,Math.floor(t*sr)),z=Math.min(L.length,Math.ceil((t+d)*sr)),rr=rng(seed);for(let i=a;i<z;i++){const x=(i-a)/sr,v=noise(rr)*g*Math.exp(-x/(type==='snare'?.09:.05));L[i]+=v*(1-pan*.7);R[i]+=v*(1+pan*.7)}}
function kick(L,R,sr,t,g){const a=Math.floor(t*sr),z=Math.min(L.length,a+Math.floor(.22*sr));for(let i=a;i<z;i++){const x=(i-a)/sr,f=150*Math.pow(45/150,Math.min(1,x/.13)),v=Math.sin(2*Math.PI*f*x)*g*Math.exp(-x/.065);L[i]+=v;R[i]+=v}}
function eight(L,R,sr,t,d,f,g){const a=Math.floor(t*sr),z=Math.min(L.length,Math.ceil((t+d)*sr));for(let i=a;i<z;i++){const x=(i-a)/sr,v=Math.sin(2*Math.PI*f*x)*g*env(x,d);L[i]+=clip(v*1.6);R[i]+=clip(v*1.6)}}
function render(com,{sampleRate=44100,masterGain=.9,stereoWidth=1,lowCutHz=28,limiterDb=-1}={}){const b=com.brief,len=Math.ceil(b.duration*sampleRate),L=new Float32Array(len),R=new Float32Array(len);for(const d of com.drums||[]){if(d.type==='kick')kick(L,R,sampleRate,d.time,.3*d.velocity);else nse(L,R,sampleRate,d.time,d.type==='openhat'?.13:.06,(d.type==='openhat'?.07:.045)*d.velocity,0,d.type==='openhat'?'openhat':'hat',Math.floor(d.time*1e5)+2)}for(const x of com.bass||[]){if(x.style==='808')eight(L,R,sampleRate,x.time,x.duration,freq(x.midi),.17*x.velocity);else tone(L,R,sampleRate,x.time,x.duration,freq(x.midi),.08+x.velocity*.05,x.style==='picked'?'pluck':'supersaw',-.03)}for(const x of com.harmony||[])tone(L,R,sampleRate,x.time,x.duration,freq(x.midi),.035+x.velocity*.065,x.style==='vocal'?'vocal':'pad',x.pan);for(const x of com.melody||[])tone(L,R,sampleRate,x.time,x.duration,freq(x.midi),.07*x.velocity,x.style==='guitar'?'guitar':x.style==='vocal'?'vocal':x.style==='arp'?'supersaw':'pluck',x.style==='arp'?(x.midi%4-1.5)*.14:0);for(const x of com.fx||[]){if(x.type==='riser')nse(L,R,sampleRate,x.time,x.duration,x.velocity*.18,0,'hat',Math.floor(x.time*1e4)+8);else kick(L,R,sampleRate,x.time,.65*x.velocity)}const gain=Math.pow(10,num(masterGain,.9)/20),w=clamp(num(stereoWidth,1),.5,1.5),c=Math.pow(10,num(limiterDb,-1)/20);for(let i=0;i<len;i++){const m=(L[i]+R[i])*.5,s=(L[i]-R[i])*.5*w,cut=clamp(num(lowCutHz,28),20,120),hp=1-Math.exp(-2*Math.PI*cut/sampleRate);let l=m+s*.92,r=m-s*.92;l+=(l-(i?L[i-1]:0))*hp*.12;r+=(r-(i?R[i-1]:0))*hp*.12;L[i]=clamp(clip(l*gain)*c,-.98,.98);R[i]=clamp(clip(r*gain)*c,-.98,.98)}return{L,R}}
function wav(L,R,sr){const n=L.length,b=new ArrayBuffer(44+n*4),v=new DataView(b),s=(o,x)=>{for(let i=0;i<x.length;i++)v.setUint8(o+i,x.charCodeAt(i))};s(0,'RIFF');v.setUint32(4,36+n*4,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,sr,true);v.setUint32(28,sr*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,n*4,true);for(let i=0;i<n;i++){v.setInt16(44+i*4,clamp(L[i],-1,1)*32767,true);v.setInt16(46+i*4,clamp(R[i],-1,1)*32767,true)}return new Blob([b],{type:'audio/wav'})}
export function renderMusicWav(composition,options={}){if(!composition?.brief)throw Error('A valid composition is required.');const x=render(composition,options);return wav(x.L,x.R,Number(options.sampleRate)||44100)}
export function createMusicPreview({composition,context=null,masterGain=.9}={}){if(!composition)throw Error('A composition is required.');const C=typeof window!=='undefined'&&(window.AudioContext||window.webkitAudioContext);if(!C&&!context)throw Error('Web Audio is unavailable.');const ctx=context||new C(),blob=renderMusicWav(composition,{sampleRate:22050,masterGain}),url=URL.createObjectURL(blob),audio=new Audio(url);audio.volume=1;audio.preload='auto';audio.onended=()=>URL.revokeObjectURL(url);audio.play().catch(()=>{});return{context:ctx,master:null,audio,duration:composition.brief.duration,stop:()=>{audio.pause();audio.removeAttribute('src');URL.revokeObjectURL(url);try{ctx.close()}catch{}}}}
export function analyseMusic(c){const b=c?.brief||{},score=clamp(Math.round(58+(c?.melody?.length>20?9:0)+(c?.harmony?.length>20?9:0)+(c?.drums?.length>60?8:0)+(c?.bass?.length>20?7:0)+(c?.sections?.length>=5?5:0)),0,100);return{version:'music-analysis-v4',genre:b.genre||'cinematic',bpm:b.bpm||120,key:b.key||'c',mode:b.mode||'minor',duration:b.duration||0,sections:c?.sections?.length||0,melodyEvents:c?.melody?.length||0,harmonyEvents:c?.harmony?.length||0,bassEvents:c?.bass?.length||0,drumEvents:c?.drums?.length||0,qualityScore:score,production:{instrumental:Boolean(c?.melody?.length&&c?.bass?.length&&c?.drums?.length),originalOnly:true}}}
