import React,{useEffect,useRef,useState} from 'react';
import {createMusicBrief,composeFullMusic,renderMusicWav,createMusicPreview,analyseMusicComposition} from './musicStudioEngine.js';
import {createSongProject,renderStemWav,exportSongProject,validateSongProject} from './musicProjectRuntime.js';
import './musicStudio.css';
export default function MusicStudio(){const[open,setOpen]=useState(false),[prompt,setPrompt]=useState('Create a dark cinematic motorcycle chase soundtrack with a huge final climax'),[duration,setDuration]=useState(30),[bpm,setBpm]=useState('auto'),[key,setKey]=useState('auto'),[mode,setMode]=useState('auto'),[project,setProject]=useState(null),[audioUrl,setAudioUrl]=useState(''),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),audioRef=useRef(null);
 useEffect(()=>{const openMusic=()=>setOpen(true);window.addEventListener('bikeztagram:open-music',openMusic);return()=>window.removeEventListener('bikeztagram:open-music',openMusic)},[]);
 useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl);audioRef.current?.stop?.()},[audioUrl]);
 const make=async()=>{setBusy(true);try{const p=createSongProject({prompt,duration,bpm,key,mode});if(!validateSongProject(p).ok)throw new Error('Generated song project failed its quality contract.');const blob=renderMusicWav(p.composition);if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl(URL.createObjectURL(blob));setProject(p)}finally{setBusy(false)}};
 const preview=async()=>{if(!project)return;try{audioRef.current?.stop?.();audioRef.current=createMusicPreview({composition:project.composition});await audioRef.current.context.resume();setPlaying(true);setTimeout(()=>setPlaying(false),project.brief.duration*1000)}catch{setPlaying(false)}};
 const download=()=>{if(!audioUrl)return;const a=document.createElement('a');a.href=audioUrl;a.download='bikeztagram-original-song.wav';a.click()};
 const downloadProject=()=>{if(!project)return;const blob=new Blob([exportSongProject(project)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bikeztagram-song-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const downloadStem=stem=>{if(!project)return;const {blob}=renderStemWav(project,stem),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bikeztagram-${stem}.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const stats=project?analyseMusicComposition(project.composition):null;
 return <><button className="music-studio-launch" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>🎵 MUSIC MAKER</button>{open&&<aside className="music-studio-panel"><div className="music-studio-head"><div><span>ORIGINAL MUSIC STUDIO</span><h3>Make music from words.</h3></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></div><p className="music-studio-copy">This is the standalone music side of Bikeztagram. Write the kind of track you want to hear, preview it, then export the original WAV. No Gemini, no external samples, no known-song imitation.</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={busy}/><div className="music-controls"><label>Length<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="15">15s</option><option value="30">30s</option><option value="60">60s</option><option value="120">2 min</option></select></label><label>BPM<select value={bpm} onChange={e=>setBpm(e.target.value)}><option value="auto">Auto</option><option>80</option><option>100</option><option>120</option><option>140</option><option>160</option></select></label><label>Key<select value={key} onChange={e=>setKey(e.target.value)}><option value="auto">Auto</option><option>C</option><option>D</option><option>E</option><option>F#</option><option>A</option></select></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="auto">Auto</option><option>major</option><option>minor</option><option>dorian</option><option>phrygian</option></select></label></div><div className="music-actions"><button className="primary-cta" onClick={make} disabled={busy}>{busy?'◌ COMPOSING...':'✦ MAKE ORIGINAL MUSIC'}</button>{project&&<><button onClick={preview} disabled={playing}>{playing?'▶ PLAYING...':'▶ PREVIEW'}</button><button onClick={download}>⬇ WAV</button><button onClick={downloadProject}>⬇ PROJECT</button><button onClick={()=>downloadStem('drums')}>🥁 STEM</button></>}</div>{stats&&<div className="music-stats"><b>{stats.qualityScore}% composition score</b><span>{stats.bpm} BPM · {project.brief.key} · {project.brief.mode}</span><span>{stats.sections} sections · {stats.melodyNotes} melody notes · {stats.beats} beats</span><span>Lyrics + mastering spec + editable arrangement included</span></div>}</aside>}</>}
