/* BIKEZTAGRAM AI — browser-local music maker. No provider, no samples, original synthesis only. */
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const num=(v,d)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const rng=seed=>{let s=seed>>>0||1;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296}};
const SCALES={major:[0,2,4,5,7,9,11],minor:[0,2,3,5,7,8,10],dorian:[0,2,3,5,7,9,10],phrygian:[0,1,3,5,7,8,10],pentatonic:[0,2,4,7,9]};
const ROOTS={c:0,'c#':1,db:1,d:2,'d#':3,eb:3,e:4,f:5,'f#':6,gb:6,g:7,'g#':8,ab:8,a:9,'a#':10,bb:10,b:11};
function detectPrompt(prompt=''){const p=String(prompt).toLowerCase();const mood=/dark|moody|gritty|mysterious|noir/.test(p)?'dark':/happy|bright|uplifting|joy/.test(p)?'uplifting':/sad|emotional|melancholy|heart/.test(p)?'emotional':/ambient|peaceful|calm|dreamy/.test(p)?'ambient':'cinematic';const genre=/rock|guitar/.test(p)?'rock':/techno|edm|electronic/.test(p)?'electronic':/hip.?hop|trap/.test(p)?'hiphop':/drum.?and.?bass|dnb/.test(p)?'dnb':/orchestral|score|film/.test(p)?'orchestral':'cinematic';const energy=/very fast|extremely fast|hyper|aggressive|racing/.test(p)?'extreme':/fast|energetic|action/.test(p)?'high':/slow|calm|ambient|peaceful/.test(p)?'low':'medium';const mode=/dorian/.test(p)?'dorian':/phrygian/.test(p)?'phrygian':/major|uplifting|happy|bright/.test(p)?'major':'minor';const rootMatch=p.match(/\b(c#|db|d#|eb|f#|gb|g#|ab|a#|bb|[a-g])\s*(?:minor|major|m)?\b/);const root=rootMatch?.[1]|| (mood==='uplifting'?'d':mood==='dark'?'f#':'a');return{mood,genre,energy,mode,root}};
export function createMusicBrief({prompt='',duration=30,bpm='auto',key='auto',mode='auto',seed=''}={}){const d=detectPrompt(prompt),tempo=bpm==='auto'?({low:82,medium:112,high:132,extreme:150}[d.energy]):clamp(num(bpm,112),55,190);const rootName=key==='auto'?d.root:String(key).toLowerCase();return{version:'music-studio-v1',prompt:String(prompt),duration:clamp(num(duration,30),3,600),bpm:tempo,key:rootName,mode:mode==='auto'?d.mode:mode,mood:d.mood,genre:d.genre,energy:d.energy,seed:seed||hash(`${prompt}|${duration}|${tempo}|${rootName}|${d.mode}`),copyright:{originalOnly:true,noKnownSongImitation:true,noExternalAudioSamples:true}};}
function note(root,scale,degree,octave=4){const tones=scale.length;const oct=Math.floor(degree/tones);return 12*(octave+oct+1)+root+scale[((degree%tones)+tones)%tones]}
export function composeFullMusic(briefInput={}){const brief=briefInput.version?briefInput:createMusicBrief(briefInput);const root=ROOTS[brief.key]??0,scale=SCALES[brief.mode]||SCALES.minor,beat=60/brief.bpm,bar=beat*4,rand=rng(hash(`${brief.seed}|arrangement`));const sectionNames=brief.duration<15?['intro','build','climax','outro']:['intro','build','lift','climax','outro'];const ratios=sectionNames.length===5?[.12,.22,.24,.26,.16]:[.16,.24,.38,.22];let cursor=0;const sections=sectionNames.map((name,i)=>{const start=cursor,end=i===sectionNames.length-1?brief.duration:Math.min(brief.duration,cursor+brief.duration*ratios[i]);cursor=end;return{name,start:Number(start.toFixed(3)),end:Number(end.toFixed(3)),density:name==='climax'?1:name==='build'||name==='lift'?.72:.4+i*.08};});const events=[];for(const sec of sections){const bars=Math.max(1,Math.ceil((sec.end-sec.start)/bar));for(let b=0;b<bars;b++){const t=sec.start+b*bar;if(t>=brief.duration)break;const intensity=clamp(sec.density*(.8+rand()*.2),.2,1);events.push({time:Number(t.toFixed(3)),type:'section',section:sec.name,intensity:Number(intensity.toFixed(3))});for(let beatIndex=0;beatIndex<4;beatIndex++){const bt=t+beatIndex*beat;if(bt>=sec.end)break;events.push({time:Number(bt.toFixed(3)),type:'beat',section:sec.name,accent:beatIndex===0||sec.name==='climax',intensity});}}}const progression=brief.mode==='major'?[0,3,4,0]:brief.mode==='dorian'?[0,3,4,1]:[0,5,3,4];const chords=progression.map((degree,i)=>({index:i,degree,rootMidi:note(root,scale,degree,3),tones:[note(root,scale,degree,3),note(root,scale,degree+2,3),note(root,scale,degree+4,3)]}));const melody=[];for(let t=0,i=0;t<brief.duration;t+=beat/2,i++){if(rand()>.68)continue;const degree=(i+(brief.mood==='uplifting'?2:0))%7;melody.push({time:Number(t.toFixed(3)),duration:Number((beat*.42).toFixed(3)),midi:note(root,scale,degree,5),velocity:Number((.35+rand()*.4).toFixed(3))});}return{brief,sections,events,chords,melody,beatGrid:Array.from({length:Math.ceil(brief.duration/beat)+1},(_,i)=>Number((i*beat).toFixed(3))),stems:{drums:true,bass:true,harmony:true,melody:true,fx:true}};}
const osc=(ctx,type,freq,when,duration,gain,dest)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,when);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),when+.008);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g);g.connect(dest);o.start(when);o.stop(when+duration+.02)};
export function createMusicPreview({composition,context=null,masterGain=.72}={}){if(!composition)throw new Error('A composition is required.');const C=window.AudioContext||window.webkitAudioContext;if(!C&&!context)throw new Error('Web Audio is unavailable in this browser.');const ctx=context||new C(),master=ctx.createGain();master.gain.value=masterGain;master.connect(ctx.destination);const now=ctx.currentTime+.08,beat=60/composition.brief.bpm,root=ROOTS[composition.brief.key]??0,scale=SCALES[composition.brief.mode]||SCALES.minor;for(let t=0;t<composition.brief.duration;t+=beat){const beatIndex=Math.round(t/beat),accent=beatIndex%4===0;osc(ctx,'sine',midiFreq(note(root,scale,0,2)),now+t,Math.min(beat*.7,.5),accent?.08:.035,master);if(beatIndex%2===1)osc(ctx,'triangle',midiFreq(note(root,scale,0,3)),now+t,Math.min(beat*.35,.25),.025,master)}for(const n of composition.melody.slice(0,3000))osc(ctx,'triangle',midiFreq(n.midi),now+n.time,n.duration,n.velocity*.045,master);return{context:ctx,master,stop:()=>ctx.close(),duration:composition.brief.duration};}
function midiFreq(m){return 440*Math.pow(2,(m-69)/12)}
export function renderMusicWav(composition,{sampleRate=44100,masterGain=.55}={}){const length=Math.ceil(composition.brief.duration*sampleRate),channels=2,data=[new Float32Array(length),new Float32Array(length)],beat=60/composition.brief.bpm,root=ROOTS[composition.brief.key]??0,scale=SCALES[composition.brief.mode]||SCALES.minor,seed=rng(hash(`${composition.brief.seed}|render`));const add=(time,dur,freq,gain,type='sine',pan=0)=>{const start=Math.max(0,Math.floor(time*sampleRate)),end=Math.min(length,Math.ceil((time+dur)*sampleRate));for(let i=start;i<end;i++){const x=(i-start)/sampleRate;const env=Math.exp(-x/Math.max(.03,dur*.42));let wave=type==='noise'?(seed()*2-1):Math.sin(2*Math.PI*freq*x);if(type==='saw')wave=2*((freq*x)%1)-1;const v=wave*gain*env;data[0][i]+=v*(1-pan);data[1][i]+=v*(1+pan)}};for(let t=0;t<composition.brief.duration;t+=beat){const bi=Math.round(t/beat),accent=bi%4===0;add(t,.12,accent?72:52,masterGain*(accent?.17:.07),'sine');if(bi%2===1)add(t,.06,180,.025,'noise',.1)}for(const n of composition.melody.slice(0,10000))add(n.time,n.duration,midiFreq(n.midi),masterGain*n.velocity*.11,'triangle',(seed()-.5)*.35);for(const sec of composition.sections){const chord=composition.chords[Math.floor((sec.start/beat)/4)%composition.chords.length];for(const m of chord.tones)add(sec.start,.9,midiFreq(m),masterGain*.025,'sine',m%2?.15:-.15)}const pcm=new Float32Array(length*2);for(let i=0;i<length;i++){data[0][i]=clamp(data[0][i],-1,1);data[1][i]=clamp(data[1][i],-1,1);pcm[i*2]=data[0][i];pcm[i*2+1]=data[1][i]}return encodeWav(pcm,sampleRate,2);}
function encodeWav(samples,sampleRate,channels){const bytes=44+samples.length*2,b=new ArrayBuffer(bytes),v=new DataView(b);const w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,bytes-8,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*channels*2,true);v.setUint16(32,channels*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,samples.length*2,true);for(let i=0;i<samples.length;i++)v.setInt16(44+i*2,Math.round(clamp(samples[i],-1,1)*32767),true);return new Blob([b],{type:'audio/wav'});}
export function analyseMusicComposition(composition){const d=composition?.brief?.duration||0,bpm=composition?.brief?.bpm||0,beats=composition?.beatGrid?.length||0;return{duration:d,bpm,beats,sections:composition?.sections?.length||0,melodyNotes:composition?.melody?.length||0,stems:Object.keys(composition?.stems||{}),qualityScore:Number(clamp(55+(composition?.sections?.length||0)*7+(composition?.melody?.length?12:0),0,100).toFixed(1))};}
