/* Full song-project layer: lyrics, stems, mastering and editable project metadata. */
import { createMusicBrief,composeFullMusic,renderMusicWav } from './musicStudioEngine.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||a));
export function createSongProject(input={}){const brief=createMusicBrief(input),composition=composeFullMusic(brief);return{version:'song-project-v1',id:`song-${brief.seed}`,brief,composition,lyrics:generateOriginalLyrics(brief),stems:{drums:'planned',bass:'planned',harmony:'planned',melody:'planned',fx:'planned'},mastering:createMasteringSpec(brief),export:{wav:true,project:true}};}
export function generateOriginalLyrics(brief={}){const mood=String(brief.mood||'cinematic'),energy=String(brief.energy||'medium');const lines={dark:['Under the midnight sky','Engines wake and shadows move','No turning back now','We chase the light through the dark'],emotional:['Hold the moment close','Let the silence breathe','Every road remembers','And every ending starts again'],uplifting:['Feel the road beneath us','Let the horizon open wide','We rise into the light','And leave the fear behind'],ambient:['Slow down and breathe','The world becomes a distant glow','Time drifts like a quiet road','Nothing needs to hurry'],cinematic:['The night begins to move','A spark becomes a flame','The road is calling now','And we become the story']}[mood]||['The story starts tonight','Every moment pulls us forward','We rise above the noise','And leave our mark behind'];return{enabled:true,originalOnly:true,style:`${mood} ${energy}`,lines};}
export function createMasteringSpec(brief={}){const target=brief.genre==='hiphop'?-10:brief.genre==='electronic'?-9:-11;return{version:'master-v1',targetLufs:target,truePeakDbtp:-1,limiterCeilingDbtp:-1,stereoWidth:brief.mood==='ambient'?.9:1,lowCutHz:28,highCutHz:19000,dynamicRangeTargetDb:8,normalization:'integrated-lufs',originalOnly:true};}
export function renderStemWav(project,stem='master'){if(!project?.composition)throw new Error('A song project is required.');const blob=renderMusicWav(project.composition,{masterGain:stem==='master'?.55:stem==='drums'?.7:stem==='bass'?.5:.35});return{stem,blob,mimeType:'audio/wav',bytes:blob.size};}
export function exportSongProject(project){return JSON.stringify({version:project.version,id:project.id,brief:project.brief,composition:project.composition,lyrics:project.lyrics,stems:project.stems,mastering:project.mastering,export:project.export},null,2);}
export function validateSongProject(project){const failures=[];if(!project?.brief?.copyright?.originalOnly)failures.push('original-only-policy-missing');if(!project?.composition?.events?.length)failures.push('no-arrangement-events');if(!project?.composition?.melody?.length)failures.push('no-melody');if(!project?.lyrics?.originalOnly)failures.push('lyrics-policy-missing');if(!project?.mastering?.targetLufs)failures.push('mastering-target-missing');return{ok:failures.length===0,failures};}
