/* Music Composition V3: provider-grade original soundtrack blueprint. */
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
const structures={short:['intro','build','impact','hero','outro'],trailer:['intro','theme','build','pre-impact','impact','hero','outro'],song:['intro','verse-a','pre-chorus','chorus','verse-b','bridge','final-chorus','outro'],score:['atmosphere','theme','development-a','development-b','breath','escalation','climax','resolution']};
const roleMap={intro:['pad','texture','light-percussion'],'verse-a':['drums','bass','chords','motif'],'verse-b':['drums','bass','chords','motif-variation'],'pre-chorus':['riser','bass','harmony','snare-build'],chorus:['full-drums','bass','chords','lead-hook','counter-motif'],'final-chorus':['full-drums','bass','chords','lead-hook','counter-motif','octave-lift'],bridge:['half-time-drums','sub-bass','texture','motif-reharmonised'],outro:['tail','texture','final-chord'],theme:['drums','bass','harmony','lead-motif'],build:['percussion','bass','riser','harmony'],impact:['full-drums','bass','lead','sub-hit'],hero:['full-arrangement','lead','counterline'],'pre-impact':['snare-build','riser','bass'],atmosphere:['texture','pad'],'development-a':['bass','motif','percussion'],'development-b':['bass','motif-variation','percussion','harmony'],breath:['pad','texture'],escalation:['drums','bass','riser','harmony'],climax:['full-arrangement','lead','counterline'],resolution:['pad','final-chord']};
export function chooseMusicStructure({duration=30,filmType='trailer',prompt=''}={}){const d=clamp(duration,15,3600),p=String(prompt).toLowerCase();if(d<=35)return 'short';if(p.includes('song')||p.includes('vocal')||p.includes('track'))return 'song';if(p.includes('score')||p.includes('documentary')||p.includes('film'))return 'score';return filmType==='song'?'song':d>120?'score':'trailer';}
export function buildLongFormMusicComposition({duration=30,prompt='',genre='cinematic',mood='cinematic',energy=.72,filmType='trailer',bpm=112,key='original'}={}){
 const total=clamp(duration,15,3600),structure=chooseMusicStructure({duration:total,filmType,prompt}),names=structures[structure];
 const rawWeights=structure==='score'?[.08,.1,.12,.14,.08,.16,.18,.14]:structure==='song'?[.08,.16,.08,.16,.16,.12,.18,.06]:structure==='trailer'?[.08,.12,.18,.12,.14,.26,.1]:[.1,.16,.24,.28,.16];
 const weights=rawWeights.map(v=>v/rawWeights.reduce((a,b)=>a+b,0));let cursor=0;
 const sections=names.map((name,i)=>{const start=cursor,end=i===names.length-1?total:Number((cursor+total*weights[i]).toFixed(3));cursor=end;const highEnergy=['impact','climax','chorus','final-chorus','hero'].includes(name);const lowEnergy=['intro','breath','outro','atmosphere'].includes(name);return{id:`${name}-${i+1}`,name,start,end,duration:Number((end-start).toFixed(3)),energy:Number(clamp(energy+(highEnergy?.16:0)-(lowEnergy?.16:0),.2,1).toFixed(3)),purpose:name,roles:roleMap[name]||['drums','bass','harmony'],variation:i%2?'motif-development':'motif-statement',automation:{filterSweep:highEnergy,riser:highEnergy&&i>0,drop:name==='impact'||name==='climax'}};});
 return {version:'music-composition-v3.1',original:true,duration:total,genre,mood,energy,bpm,key,structure,sections,theme:{type:'original-motif',development:true,variationEveryBars:8,hookRepetitionLimit:4},arrangement:{drums:true,bass:true,harmony:true,lead:true,counterline:true,texture:true,transitions:true,stereoDepth:true,dynamics:true,automation:true,master:true,sectionContrast:true},generation:{providerNeutral:true,requiresProviderForProfessionalAudio:true,localFallbackAllowed:true,localFallbackRole:'audible-production-sketch-not-final-master'},copyright:{originalOnly:true,noNamedSongImitation:true,noReproductionOfExistingMelodies:true},creativeRequest:prompt||'Compose an original professionally produced soundtrack for the film.'};
}
export function buildMusicGenerationPlan(args={}){const composition=buildLongFormMusicComposition(args);return {...composition,providerRequest:{duration:composition.duration,sections:composition.sections,genre:composition.genre,mood:composition.mood,energy:composition.energy,bpm:composition.bpm,arrangement:composition.arrangement,originality:composition.copyright}};}
