/* BIKEZTAGRAM AI — browser-local editable music arrangement runtime. */
import { composeFullMusic,renderMusicWav } from './musicStudioEngine.js';
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const clone=value=>JSON.parse(JSON.stringify(value));
const STEMS=['drums','bass','harmony','melody','fx'];
export function createArrangementProject(options={}){const brief={...(options.brief||{})};const composition=options.composition||composeFullMusic(brief);return{version:3,id:options.id||`song-${Date.now().toString(36)}`,title:String(options.title||brief.title||'Bikeztagram Original'),brief,composition:clone(composition),sectionEdits:[],mutedStems:[],master:{gainDb:0,limiterDb:-1,stereoWidth:1,lowCutHz:28},updatedAt:new Date().toISOString()};}
export function updateArrangementSection(project,sectionIndex,patch={}){const next=clone(project),sections=next.composition?.sections||[];if(!sections[sectionIndex])throw new Error(`Unknown music section ${sectionIndex}.`);const allowed=['name','start','end','durationBeats','energy','density','swing','reverb','filter','octave'];for(const key of allowed)if(patch[key]!==undefined)sections[sectionIndex][key]=patch[key];next.sectionEdits=[...(next.sectionEdits||[]),{sectionIndex,patch:clone(patch),at:new Date().toISOString()}];next.updatedAt=new Date().toISOString();return next;}
export function toggleArrangementStem(project,stem){const next=clone(project),name=String(stem||'').toLowerCase();if(!STEMS.includes(name))throw new Error(`Unsupported stem: ${stem}.`);const muted=new Set(next.mutedStems||[]);muted.has(name)?muted.delete(name):muted.add(name);next.mutedStems=[...muted];next.updatedAt=new Date().toISOString();return next;}
export function updateMastering(project,patch={}){const next=clone(project);next.master={...next.master};if(patch.gainDb!==undefined)next.master.gainDb=clamp(Number(patch.gainDb)||0,-12,6);if(patch.limiterDb!==undefined)next.master.limiterDb=clamp(Number(patch.limiterDb)||-1,-6,0);if(patch.stereoWidth!==undefined)next.master.stereoWidth=clamp(Number(patch.stereoWidth)||1,.5,1.5);if(patch.lowCutHz!==undefined)next.master.lowCutHz=clamp(Number(patch.lowCutHz)||28,20,120);next.updatedAt=new Date().toISOString();return next;}
function sectionForTime(sections,time){return sections.find(section=>time>=Number(section.start||0)-.001&&time<Number(section.end||0)+.001)||sections[sections.length-1]||{};}
function applySectionEdits(composition,project){const sections=composition.sections||[];const mapEvents=events=>(events||[]).map(event=>{const section=sectionForTime(sections,Number(event.time)||0);const energy=clamp(Number(section.energy)||.5,.1,1.5),density=clamp(Number(section.density)||1,.1,1.5);const multiplier=clamp(.65+energy*.35,.45,1.25)*clamp(.78+density*.22,.65,1.12);const next={...event};if(next.velocity!==undefined)next.velocity=clamp(Number(next.velocity)*multiplier,.03,1);const octave=Number(section.octave)||0;if(octave&&next.midi!==undefined)next.midi=Number(next.midi)+octave*12;return next;});return{...composition,melody:mapEvents(composition.melody),bass:mapEvents(composition.bass),harmony:mapEvents(composition.harmony),drums:mapEvents(composition.drums),fx:mapEvents(composition.fx)};}
export function materializeArrangementComposition(project,stemFilter=null){const base=clone(project?.composition||composeFullMusic(project?.brief||{}));const edited=applySectionEdits(base,project||{});const muted=new Set(project?.mutedStems||[]);const active=stemFilter?new Set([String(stemFilter)]):null;for(const stem of STEMS)if(muted.has(stem)||active&&!active.has(stem))edited[stem]=[];return edited;}
export async function renderArrangementWav(project,options={}){const composition=materializeArrangementComposition(project,options.stem||null);const masterGain=Math.pow(10,(Number(project?.master?.gainDb)||0)/20)*.78;const wav=renderMusicWav(composition,{masterGain,sampleRate:Number(options.sampleRate)||44100});const audioDataUrl=typeof URL!=='undefined'?URL.createObjectURL(wav):'';return{blob:wav,mimeType:'audio/wav',bytes:wav.size,mastering:project?.master||{},stem:options.stem||'master',audioDataUrl};}
export async function renderArrangementStemWav(project,stem,options={}){if(!STEMS.includes(String(stem)))throw new Error(`Unsupported stem: ${stem}.`);return renderArrangementWav(project,{...options,stem:String(stem)});}
export function arrangementStemNames(){return[...STEMS];}
export function analyseArrangement(project){const c=project?.composition||{},sections=Array.isArray(c.sections)?c.sections:[],events=Array.isArray(c.events)?c.events:[],muted=new Set(project?.mutedStems||[]),activeStemCount=STEMS.length-muted.size,energy=sections.length?sections.reduce((s,x)=>s+Number(x.energy||0),0)/sections.length:0;return{ok:Boolean(c.beatGrid?.length&&events.length&&sections.length),bpm:Number(c.brief?.bpm||c.bpm)||120,key:c.brief?.key||c.key||'C',mode:c.brief?.mode||c.mode||'minor',sections:sections.length,events:events.length,activeStemCount,averageEnergy:Number(energy.toFixed(3)),mutedStems:[...muted],editCount:Array.isArray(project?.sectionEdits)?project.sectionEdits.length:0,mastering:project?.master||{},stems:Object.fromEntries(STEMS.map(stem=>[stem,!muted.has(stem)]))};}
