/* BIKEZTAGRAM AI — cinematic product renderer */
export async function renderProject(mediaItems, plan, onProgress) {
  return new Promise((resolve, reject) => {
    try {
      const canvas=document.createElement('canvas'); canvas.width=1080; canvas.height=1920;
      const ctx=canvas.getContext('2d'); if(!ctx) throw new Error('Could not create canvas context.');
      const stream=canvas.captureStream(30);
      const mimeTypes=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4;codecs=h264','video/mp4'];
      const selectedType=mimeTypes.find(type=>MediaRecorder.isTypeSupported(type))||'';
      const recorder=selectedType?new MediaRecorder(stream,{mimeType:selectedType}):new MediaRecorder(stream);
      const chunks=[];let settled=false;
      const fail=error=>{if(settled)return;settled=true;try{if(recorder.state!=='inactive')recorder.stop();}catch{}reject(error instanceof Error?error:new Error(String(error)));};
      recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data);}; recorder.onerror=e=>fail(e.error||new Error('Video recording failed.'));
      recorder.onstop=()=>{if(settled)return;settled=true;if(!chunks.length)return reject(new Error(`MediaRecorder produced no video data. Codec selected: ${selectedType||'browser default'}.`));resolve(new Blob(chunks,{type:chunks[0]?.type||selectedType||'video/webm'}));};
      const clamp=(v,min,max)=>Math.max(min,Math.min(max,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=v=>v<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2;
      let cuts=Array.isArray(plan?.cuts)?plan.cuts:[]; if(!cuts.length&&Array.isArray(plan?.scenes))cuts=plan.scenes.map((s,i)=>({...s,mediaIndex:s.mediaIndex??0,startTime:Number(s.startTime)||0,duration:Number(s.duration)||2,purpose:s.purpose||'cinematic-scene',sourceType:s.sourceType||'uploaded',generated:s.sourceType==='generated',generationPrompt:s.generationPrompt||'',transition:s.transitionIn||(i?'crossfade':'fade-in'),motionStyle:s.motionStyle||'slow-push',motionIntensity:s.motionIntensity||.9,colorGrade:s.colorGrade||plan.colorGrade||'cinematic'}));
      if(!cuts.length)return fail(new Error('AI edit plan contains no cuts.'));
      const findMedia=cut=>{if(cut?.mediaId!=null){const found=mediaItems.find(item=>String(item.id)===String(cut.mediaId));if(found)return found;}const index=Number(cut?.mediaIndex);return Number.isInteger(index)?mediaItems[index]||null:null;};
      const getSourceUrl=media=>media?.sourceUrl?{url:media.sourceUrl,revoke:false,remote:true}:media?.file?{url:URL.createObjectURL(media.file),revoke:true,remote:false}:null;
      const isGenerated=cut=>Boolean(cut?.generated||cut?.sourceType==='generated'||cut?.sourceType==='procedural'||cut?.generationPrompt);
      const gradeFilter=grade=>{const g=String(grade||'').toLowerCase();if(g.includes('natural')||g.includes('neutral'))return'brightness(.98) contrast(1.08) saturate(1.08)';if(g.includes('warm')||g.includes('golden'))return'brightness(.94) contrast(1.15) saturate(1.14) sepia(.08)';if(g.includes('blue')||g.includes('moody')||g.includes('dark'))return'brightness(.88) contrast(1.20) saturate(1.14) hue-rotate(-6deg)';if(g.includes('vivid')||g.includes('energetic'))return'brightness(.95) contrast(1.20) saturate(1.28)';return'brightness(.90) contrast(1.18) saturate(1.12)';};
      const drawCover=(element,t,grade)=>{const sw=element.videoWidth||element.naturalWidth||1080,sh=element.videoHeight||element.naturalHeight||1920;if(!sw||!sh)throw new Error('Source media has no decoded dimensions.');const ratio=sw/sh,target=canvas.width/canvas.height;let width,height;if(ratio>target){height=canvas.height*t.scale;width=height*ratio;}else{width=canvas.width*t.scale;height=width/ratio;}const x=(canvas.width-width)/2+t.x,y=(canvas.height-height)/2+t.y;ctx.save();ctx.filter=gradeFilter(grade);if(t.r){ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(t.r);ctx.translate(-canvas.width/2,-canvas.height/2);}ctx.drawImage(element,x,y,width,height);ctx.restore();};
      const motion=(cut,p)=>{const m=String(cut.motionStyle||'static').toLowerCase(),e=ease(p),intensity=clamp(Number(cut.motionIntensity)||1,.35,1.6);let scale=cut.stabilization?1.065:1.025,x=0,y=0,r=0;if(m.includes('slow-push')||m.includes('push')||m==='zoom')scale+=e*.115*intensity;else if(m.includes('slow-pull')||m.includes('pull')||m.includes('zoom-out'))scale+=(1-e)*.115*intensity;else if(m.includes('pan-right')){scale=Math.max(scale,1.08);x=(e-.5)*canvas.width*.15*intensity;}else if(m.includes('pan-left')){scale=Math.max(scale,1.08);x=(.5-e)*canvas.width*.15*intensity;}else if(m.includes('tilt-up')){scale=Math.max(scale,1.08);y=(.5-e)*canvas.height*.09*intensity;}else if(m.includes('tilt-down')){scale=Math.max(scale,1.08);y=(e-.5)*canvas.height*.09*intensity;}return{scale:clamp(scale,1.01,1.28),x,y,r};};
      const transition=(name,p,first)=>{const n=String(name||'hard-cut').toLowerCase(),len=.20;if(first&&(n==='fade-in'||n==='fade'||n==='cinematic')){ctx.save();ctx.fillStyle='#000';ctx.globalAlpha=1-clamp(p/len,0,1);ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();}if(n==='fade-out'){ctx.save();ctx.fillStyle='#000';ctx.globalAlpha=clamp((p-(1-len))/len,0,1);ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();}if(n==='dip-black'){const a=Math.max(0,1-Math.abs(p-.5)*5);ctx.save();ctx.fillStyle='#000';ctx.globalAlpha=a*.92;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();}if(n==='crossfade'){ctx.save();ctx.fillStyle='#000';ctx.globalAlpha=Math.max(0,1-p/.3)*.25;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();}};
      const finish=(cut,p)=>{const prompt=String(plan?.creativePrompt||'').toLowerCase(),purpose=String(cut.purpose||'').toLowerCase();if(plan?.style||/cinematic|film|trailer|commercial/.test(prompt)){const v=ctx.createRadialGradient(canvas.width/2,canvas.height/2,canvas.height*.22,canvas.width/2,canvas.height/2,canvas.height*.78);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(.72,'rgba(0,0,0,.08)');v.addColorStop(1,'rgba(0,0,0,.55)');ctx.save();ctx.fillStyle=v;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();}if(/trailer|film|cinematic|commercial/.test(prompt)){const bar=Math.round(canvas.height*.035);ctx.save();ctx.fillStyle='rgba(0,0,0,.92)';ctx.fillRect(0,0,canvas.width,bar);ctx.fillRect(0,canvas.height-bar,canvas.width,bar);ctx.restore();}};
      const loadVideo=async(element,source)=>{element.muted=true;element.playsInline=true;element.preload='auto';element.crossOrigin=source.remote?'anonymous':'';element.src=source.url;await new Promise((resolve,rejectLoad)=>{let done=false;const timeout=setTimeout(()=>finish(new Error('Timed out loading source video.')),12000);const cleanup=()=>{clearTimeout(timeout);element.removeEventListener('loadedmetadata',onMeta);element.removeEventListener('loadeddata',onData);element.removeEventListener('canplay',onCanPlay);element.removeEventListener('error',onError);};const finish=error=>{if(done)return;done=true;cleanup();error?rejectLoad(error):resolve();};const onMeta=()=>{if(element.videoWidth&&element.videoHeight)finish();};const onData=()=>{if(element.videoWidth&&element.videoHeight)finish();};const onCanPlay=()=>{if(element.videoWidth&&element.videoHeight)finish();};const onError=()=>{const e=element.error;finish(new Error(`Could not decode source video. MediaError code=${e?.code??'unknown'}; ${e?.message||'browser media decoder rejected the source'}; readyState=${element.readyState}; networkState=${element.networkState}.`));};element.addEventListener('loadedmetadata',onMeta);element.addEventListener('loadeddata',onData);element.addEventListener('canplay',onCanPlay);element.addEventListener('error',onError);element.load();});if(!element.videoWidth||!element.videoHeight||!Number.isFinite(element.duration))throw new Error(`Source video decoded incorrectly: ${element.videoWidth}x${element.videoHeight}, duration=${element.duration}.`);};
      recorder.start(1000);
      const renderCut=async index=>{if(index>=cuts.length){if(recorder.state!=='inactive')recorder.stop();return;}const cut=cuts[index]||{};const generated=isGenerated(cut);const media=generated?null:findMedia(cut);if(!generated&&!media)throw new Error(`Cut ${index+1} references missing media.`);const isVideo=!generated&&String(media.type||'').startsWith('video');const source=generated?null:getSourceUrl(media);if(!generated&&!source)throw new Error(`Cut ${index+1} has no usable source file or Blob URL.`);const element=generated?null:(isVideo?document.createElement('video'):new Image());const duration=clamp(Number(cut.duration)||2,.5,8),speedStart=clamp(Number(cut.speed)||1,.5,1.75),speedEnd=clamp(Number(cut.speedEnd??cut.speed)||speedStart,.5,1.75);try{if(isVideo){await loadVideo(element,source);const start=Number(cut.startTime);if(Number.isFinite(start)&&start>=0){element.currentTime=Math.min(start,Math.max(0,element.duration-.05));await new Promise(done=>{let finished=false;const finish=()=>{if(finished)return;finished=true;clearTimeout(timer);element.removeEventListener('seeked',finish);done();};const timer=setTimeout(finish,1800);element.addEventListener('seeked',finish,{once:true});});}element.playbackRate=speedStart;await element.play();}const started=performance.now();await new Promise(done=>{const tick=()=>{const p=clamp((performance.now()-started)/(duration*1000),0,1);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);if(!generated)drawCover(element,motion(cut,p),cut.colorGrade||plan.colorGrade);finish(cut,p);transition(cut.transition,p,index===0);onProgress?.(Math.round(((index+p)/cuts.length)*100));if(p>=1){done();return;}requestAnimationFrame(tick);};requestAnimationFrame(tick);});if(isVideo)element.pause();if(source?.revoke)URL.revokeObjectURL(source.url);await renderCut(index+1);}catch(error){if(source?.revoke){try{URL.revokeObjectURL(source.url);}catch{}}throw new Error(`Cut ${index+1} failed: ${error?.message||String(error)}`);}};
      renderCut(0).catch(fail);
    }catch(error){reject(error);}
  });
}
