/* Bikeztagram AI — provider-neutral scene-generation planner V3. */
const text=v=>String(v??'').trim();
const num=(v,fallback=0)=>Number.isFinite(Number(v))?Number(v):fallback;
const clamp=(v,a,b,fallback=a)=>Math.max(a,Math.min(b,num(v,fallback)));
const stableId=(role,prompt,duration,seed='')=>{let h=2166136261;for(const c of `${role}|${prompt}|${duration}|${seed}`)h=Math.imul(h^c.charCodeAt(0),16777619);return `scene-${role}-${(h>>>0).toString(36).padStart(7,'0')}`;};
const CAMERA={opening:'slow cinematic push-in, 35mm equivalent, controlled parallax',reveal:'low three-quarter tracking shot, subtle orbit, 50mm equivalent',action:'dynamic tracking camera, low angle, controlled motion blur',bridge:'lateral tracking shot, foreground parallax, stable horizon',hero:'slow pull-back hero composition, locked horizon, premium commercial framing'};
const LIGHT={dark:'moody directional key, cool rim light, deep controlled shadows',cinematic:'soft directional key, motivated practicals, controlled highlights',golden:'warm low-angle key, soft rim, long cinematic shadows',neon:'cool neon practicals, cyan rim, magenta ambient bounce'};
function inferEnvironment(prompt,media=[]){const p=text(prompt).toLowerCase();if(/city|urban|street|neon/.test(p))return'night urban environment with wet reflective surfaces';if(/mountain|alps|hill|countryside/.test(p))return'dramatic mountain road environment with atmospheric depth';if(/desert|sand|dune|mars/.test(p))return'open arid landscape with cinematic atmospheric haze';if(/space|galaxy|cosmic/.test(p))return'original abstract cosmic environment with stars and volumetric light';if(/forest|woodland/.test(p))return'dense forest environment with layered depth and shafts of light';if(media.some(m=>/road|ride|bike|motor|motorcycle/i.test(`${m?.name||''} ${m?.subjectLabel||''}`)))return'cinematic road environment inferred from uploaded motorcycle media';return'cinematic environment inferred from the uploaded assets';}
function inferLighting(prompt){const p=text(prompt).toLowerCase();if(/neon|cyber|futur/.test(p))return LIGHT.neon;if(/golden|sunset|warm/.test(p))return LIGHT.golden;if(/dark|moody|noir|menacing/.test(p))return LIGHT.dark;return LIGHT.cinematic;}
function inferAction(prompt,role){const p=text(prompt).toLowerCase();if(role==='action')return/motorcycle|bike|car|vehicle/.test(p)?'accelerate through frame with purposeful forward momentum':'increase movement and visual intensity toward the musical peak';if(role==='reveal')return'reveal the primary subject with a clean motivated camera move';if(role==='hero')return'settle into a confident hero pose and hold the strongest composition';if(role==='bridge')return'move through the environment while preserving subject continuity';return'establish atmosphere and anticipation before the reveal';}
function sceneDuration(total,role){const ratios={opening:.12,bridge:.16,reveal:.20,action:.20,hero:.16};return clamp(total*(ratios[role]||.16),.75,4.5,2);}
function eventForRole(events,role){const list=Array.isArray(events)?events:[];if(role==='action')return list.find(e=>e?.type==='drop'||e?.type==='impact')||null;if(role==='hero')return list.find(e=>e?.type==='hero'||e?.type==='outro')||null;return list.find(e=>e?.type==='hook'||e?.type==='build')||null;}
export function buildGeneratedSceneBlueprint({prompt='',role='bridge',duration=15,aspectRatio='9:16',subjectIds=[],referenceAssets=[],visual={},continuity={},musicEvent=null,seed=''}={}){
 const safeRole=['opening','bridge','reveal','action','hero'].includes(role)?role:'bridge';
 const env=text(visual.environment)||inferEnvironment(prompt,referenceAssets),lighting=text(visual.lighting)||inferLighting(prompt),camera=text(visual.camera)||CAMERA[safeRole],style=text(visual.style)||'cinematic original film language',action=inferAction(prompt,safeRole),anchors=Array.isArray(continuity.anchors)?continuity.anchors:[],ids=[...new Set(subjectIds.filter(Boolean))];
 return {version:'generated-scene-blueprint-v3',id:stableId(safeRole,prompt,duration,seed),role:safeRole,duration:clamp(duration,.5,60,sceneDuration(duration,safeRole)),aspectRatio:['9:16','1:1','16:9'].includes(aspectRatio)?aspectRatio:'9:16',prompt:text(prompt),direction:{style,camera,lighting,environment:env,motion:text(visual.motion)||'controlled cinematic motion',action},subjectIds:ids,subjects:{subjectIds:ids,preserveIdentity:ids.length>0,referenceAssets:[...new Set(referenceAssets.filter(Boolean))]},continuity:{anchors,matchPrevious:safeRole!=='opening',matchFollowing:safeRole!=='hero',matchColour:true},musicEvent:musicEvent?{type:musicEvent.type,time:num(musicEvent.time,0),strength:num(musicEvent.strength,musicEvent.type==='drop'?1:.7)}:null,constraints:{originalOnly:true,noNamedStyleImitation:true,noCopyrightedCharacters:true,noLogosUnlessProvided:true,noTextArtifacts:true},negativePrompt:'warped geometry, duplicate subject, identity drift, extra limbs, unstable horizon, unreadable text, accidental logos, flicker, frame-to-frame texture crawl',render:{preferredProvider:'procedural-or-model',fallback:'browser-procedural-scene',status:'planned'}};
}
export function buildSceneGenerationSet({prompt='',duration=15,aspectRatio='9:16',subjectIds=[],referenceAssets=[],visual={},musicEvents=[]}={}){const total=clamp(duration,5,600,15);return ['opening','reveal','action','hero'].map(role=>{const event=eventForRole(musicEvents,role);return buildGeneratedSceneBlueprint({prompt,role,duration:sceneDuration(total,role),aspectRatio,subjectIds,referenceAssets,visual,musicEvent:event,seed:`${total}|${role}|${event?.time??'none'}`,continuity:{anchors:[`film-${Math.round(total*10)}`,`role-${role}`,event?`music-${event.time}`:'no-explicit-event']}});});}
export function scoreGeneratedScene(scene,{prompt='',role=''}={}){const s=scene||{},checks={hasPrompt:Boolean(text(s.prompt)||text(prompt)),hasDirection:Boolean(s.direction?.camera&&s.direction?.environment),hasOriginality:Boolean(s.constraints?.originalOnly),hasContinuity:Boolean(s.continuity?.matchColour),hasDuration:num(s.duration)>0,correctRole:!role||s.role===role,hasRenderFallback:s.render?.fallback==='browser-procedural-scene'};const passed=Object.values(checks).filter(Boolean).length;return{version:'generated-scene-score-v2',score:passed/Object.keys(checks).length,checks,ready:passed===Object.keys(checks).length};}
