/* BIKEZTAGRAM AI — universal cinematic timeline director */
import { buildShotDirection, classifyMediaSubject } from './director.js';
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const num=(value,fallback)=>{const n=Number(value);return Number.isFinite(n)?n:fallback;};
const lower=(value)=>String(value||'').toLowerCase();
function creativeFlags(prompt){const p=lower(prompt);return{action:/action|chase|race|speed|pursuit|fight|battle|aggressive|energetic|playful/.test(p),trailer:/trailer|cinematic|film|movie|commercial|advert|promo/.test(p),dark:/dark|moody|night|dramatic|gritty|noir|mysterious|horror/.test(p),emotional:/emotional|romantic|beautiful|heartfelt|nostalgic|sentimental/.test(p),social:/tiktok|reel|shorts|viral|social/.test(p),comedy:/funny|comedy|comic|humorous|meme/.test(p)};}
function roleFor(index,total,flags){if(index===0)return'hook';if(index===total-1)return flags.comedy?'payoff':'hero-ending';if(flags.action)return index%3===0?'build':'action';if(flags.emotional)return index===1?'emotional-build':'emotional-beat';return index===1?'build':index===total-2?'peak':'story-beat';}
function motionFor(role,index,flags,existing,subjectType,cameraIntent){if(existing&&existing!=='static')return existing;const directed=buildShotDirection({role,intent:cameraIntent||role,subjectType,index});return directed.motion.type;}
function transitionFor(index,total,flags,existing){if(index===0)return'fade-in';if(index===total-1)return flags.dark?'dip-black':'fade-out';if(existing&&existing!=='hard-cut'&&existing!=='crossfade')return existing;if(flags.action)return index%3===0?'whip-right':index%2?'zoom-punch':'flash-cut';if(flags.dark)return index%2?'dip-black':'crossfade';if(flags.emotional)return'crossfade';if(flags.comedy)return index%2?'hard-cut':'flash-cut';return index%3===1?'crossfade':'hard-cut';}
function sourceId(cut){const id=cut?.mediaId;return id!=null&&String(id).trim()?String(id):Number.isInteger(Number(cut?.mediaIndex))?`media:${Number(cut.mediaIndex)}`:'unknown';}
export function refineCinematicTimeline(cuts,options={}){if(!Array.isArray(cuts)||!cuts.length)return[];const flags=creativeFlags(options.creativePrompt);const total=cuts.length;const sourceCounts=new Map();cuts.forEach(c=>{const id=sourceId(c);sourceCounts.set(id,(sourceCounts.get(id)||0)+1);});return cuts.map((original,index)=>{const cut={...original};const role=original.editorialRole||original.role||roleFor(index,total,flags);const subjectType=lower(cut.subjectType||cut.subject||classifyMediaSubject(cut));const cameraIntent=lower(cut.cameraIntent||cut.coverage?.cameraIntent||'');cut.subjectType=subjectType;cut.role=role;cut.motionStyle=motionFor(role,index,flags,cut.motionStyle,subjectType,cameraIntent);cut.transition=transitionFor(index,total,flags,cut.transition);const baseIntensity=num(cut.motionIntensity,.9);cut.motionIntensity=Number(clamp(role==='action'||role==='peak'?Math.max(baseIntensity,1.05):role==='hero-ending'?Math.min(baseIntensity,.9):baseIntensity,.35,1.6).toFixed(2));let speed=clamp(num(cut.speed,1),.5,1.75);if(flags.action&&(role==='action'||role==='peak'))speed=Math.max(speed,1.12);if(role==='hook'||role==='hero-ending'||flags.emotional)speed=Math.min(speed,.92);cut.speed=Number(speed.toFixed(2));if(flags.action&&(role==='action'||role==='peak'))cut.speedEnd=Number(clamp(speed*.82,.55,1.55).toFixed(2));else if(role==='hero-ending'||flags.emotional)cut.speedEnd=Number(clamp(speed*.88,.5,1.35).toFixed(2));else cut.speedEnd=Number(clamp(speed*1.02,.5,1.75).toFixed(2));cut.stabilization=cut.stabilization!==false;cut.colorGrade=cut.colorGrade||(flags.dark?'dark-cinematic':flags.emotional?'warm-cinematic':'cinematic');const id=sourceId(cut);const prior=cuts.slice(0,index).some(candidate=>sourceId(candidate)===id);cut.coverage={...(cut.coverage||{}),role,subjectType,preserveSubject:true,avoidUnnecessaryRepeat:prior,sourceUsage:sourceCounts.get(id)||1,cameraIntent:cameraIntent||buildShotDirection({role,subjectType}).cameraIntent,pacingIntent:flags.action?'escalate':flags.emotional?'breathe':index===total-1?'resolve':'build'};if(cut.directorSelectionScore!=null)cut.coverage.directorSelectionScore=num(cut.directorSelectionScore,0);if(cut.directorSelectionIndex!=null)cut.coverage.directorSelectionIndex=Number(cut.directorSelectionIndex);if(cut.editorialRole)cut.coverage.editorialRole=cut.editorialRole;return cut;});}
export function timelineSummary(cuts){if(!Array.isArray(cuts)||!cuts.length)return{cuts:0,duration:0,roles:[]};return{cuts:cuts.length,duration:Number(cuts.reduce((sum,cut)=>sum+num(cut.duration,0),0).toFixed(2)),roles:cuts.map(cut=>cut.role||'story-beat'),sources:[...new Set(cuts.map(sourceId))],subjects:[...new Set(cuts.map(cut=>cut.subjectType||'unknown'))]};}
