/* BIKEZTAGRAM AI — universal cinematic timeline director */
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const num=(v,f)=>{const n=Number(v);return Number.isFinite(n)?n:f};const lower=v=>String(v||'').toLowerCase();
function creativeFlags(prompt){const p=lower(prompt);return{action:/action|chase|race|speed|pursuit|fight|battle|aggressive|energetic/.test(p),trailer:/trailer|cinematic|film|movie|commercial|advert|promo/.test(p),dark:/dark|moody|night|dramatic|gritty|noir|mysterious|horror/.test(p),emotional:/emotional|romantic|beautiful|heartfelt|nostalgic|sentimental/.test(p),social:/tiktok|reel|shorts|viral|social/.test(p),comedy:/funny|comedy|comic|humorous|meme/.test(p)}}
function roleFor(i,total,flags){if(i===0)return'hook';if(i===total-1)return flags.comedy?'payoff':'hero-ending';if(flags.action)return i===total-2?'peak':i%3===0?'build':'action';if(flags.emotional)return i===1?'emotional-build':'emotional-beat';return i===1?'build':i===total-2?'peak':'story-beat'}
function motionFor(role,index,flags,existing){if(existing)return existing;if(role==='hook')return'slow-pull';if(role==='build')return index%2?'pan-right':'slow-push';if(role==='action')return index%2?'pan-right':'slow-push';if(role==='peak')return'slow-push';if(role==='hero-ending')return'slow-push';if(role==='emotional-build')return'slow-pull';return'static'}
function transitionFor(index,total,flags,existing){if(index===0)return'fade-in';if(index===total-1)return flags.dark?'dip-black':'fade-out';const aggressive=['whip-right','whip-left','flash-cut','zoom-punch'];if(existing&&!aggressive.includes(existing))return existing;if(flags.emotional||flags.dark)return'crossfade';if(flags.comedy)return'hard-cut';return index%3===1?'crossfade':'hard-cut'}
function sourceKey(cut){return String(cut?.mediaId??cut?.mediaIndex??'unknown')}
function shotText(cut){return lower([cut?.description,cut?.purpose,cut?.coverage?.role,cut?.motionStyle].filter(Boolean).join(' '))}
function diversifyRole(role,index,flags,cut,previous){const text=shotText(cut);if(/close.?up|detail|macro|hero/.test(text))return'hero-detail';if(/wide|landscape|establish/.test(text))return'establishing';if(/corner|lean|accelerat|chase|overtake|ride|riding/.test(text))return'action';if(index===0)return'hook';if(index===1)return'build';if(index>1&&index<6&&flags.action&&index%2===0)return'build';return role}
export function refineCinematicTimeline(cuts,options={}){if(!Array.isArray(cuts)||!cuts.length)return[];const flags=creativeFlags(options.creativePrompt),total=cuts.length,seenSources=new Map();return cuts.map((original,index)=>{const cut={...original},role=roleFor(index,total,flags),previous=cuts[index-1]||null,current=Number(cut.mediaIndex),previousIndex=Number(previous?.mediaIndex);const explicitStatic=cut.motionStyle==='static'||cut.motionIntent==='static'||cut.preserveMotion===false;cut.role=diversifyRole(role,index,flags,cut,previous);cut.mediaIndex=Number.isInteger(current)?current:cut.mediaIndex;const key=sourceKey(cut);const repeatCount=seenSources.get(key)||0;seenSources.set(key,repeatCount+1);cut.coverage={...(cut.coverage||{}),role:cut.role,preserveSubject:true,avoidUnnecessaryRepeat:Number.isInteger(current)&&Number.isInteger(previousIndex)&&current===previousIndex||repeatCount>0,cameraIntent:cut.motionStyle||'static'};
if(!explicitStatic&&(!cut.motionStyle||cut.motionStyle==='auto'))cut.motionStyle=motionFor(cut.role,index,flags,null);else if(!cut.motionStyle)cut.motionStyle=motionFor(cut.role,index,flags,null);
cut.transition=transitionFor(index,total,flags,cut.transition);const base=num(cut.motionIntensity,.35);cut.motionIntensity=Number(clamp(cut.motionStyle==='static'?0:cut.role==='action'?Math.min(base,.5):cut.role==='peak'?Math.min(base,.55):Math.min(base,.45),0,.6).toFixed(2));let speed=clamp(num(cut.speed,1),.5,1.75);if(flags.action&&(cut.role==='action'||cut.role==='peak'))speed=Math.max(speed,1.08);if(cut.role==='hook'||cut.role==='hero-ending'||flags.emotional)speed=Math.min(speed,.92);cut.speed=Number(speed.toFixed(2));cut.speedEnd=flags.action&&(cut.role==='action'||cut.role==='peak')?Number(clamp(speed*.9,.6,1.45).toFixed(2)):cut.role==='hero-ending'||flags.emotional?Number(clamp(speed*.92,.5,1.3).toFixed(2)):Number(clamp(speed*1.01,.5,1.7).toFixed(2));cut.stabilization=cut.stabilization!==false;cut.colorGrade=cut.colorGrade||(flags.dark?'dark-cinematic':flags.emotional?'warm-cinematic':'cinematic');cut.coverage.pacingIntent=flags.action?'escalate':flags.emotional?'breathe':index===total-1?'resolve':'build';return cut})}
export function timelineSummary(cuts){if(!Array.isArray(cuts)||!cuts.length)return{cuts:0,duration:0,roles:[],uniqueSources:0,repeatedAdjacent:0};let repeatedAdjacent=0;for(let i=1;i<cuts.length;i++)if(sourceKey(cuts[i])===sourceKey(cuts[i-1]))repeatedAdjacent++;return{cuts:cuts.length,duration:Number(cuts.reduce((s,c)=>s+num(c.duration,0),0).toFixed(2)),roles:cuts.map(c=>c.role||'story-beat'),uniqueSources:new Set(cuts.map(sourceKey)).size,repeatedAdjacent}}
