const ROLE_RULES={
  hook:{patterns:/hook|attention|opening|striking|unexpected|impact/,preferred:['high','striking','movement','contrast']},
  establish:{patterns:/establish|wide|landscape|environment|location|setting|travel|city|mountain|beach|room/,preferred:['wide','environment','composition']},
  build:{patterns:/build|anticipation|approach|journey|progress|preparation|waiting|slow/,preferred:['movement','progress','anticipation']},
  reveal:{patterns:/reveal|unveil|showcase|portrait|profile|detail|hero subject|product/,preferred:['subject','detail','composition']},
  action:{patterns:/action|running|riding|driving|accelerat|chase|jump|play|fight|dance|fly|swim|movement/,preferred:['movement','energy','action']},
  emotion:{patterns:/emotion|cute|funny|joy|love|smile|reaction|calm|beautiful|heart|connection/,preferred:['emotion','expression','connection']},
  hero:{patterns:/hero|final|ending|outro|epic|spectacular|beautiful|portrait|showcase/,preferred:['subject','composition','quality']}
};
function text(v){return String(v??'').trim();}
function lower(v){return text(v).toLowerCase();}
function mode(prompt){const p=lower(prompt);return{action:/action|chase|race|speed|aggressive|energetic|adventure/.test(p),travel:/travel|journey|holiday|explore|adventure|destination/.test(p),emotion:/cute|funny|emotional|beautiful|heart|love|joy|calm|peaceful/.test(p),reveal:/reveal|showcase|unveil|launch|commercial|product/.test(p),trailer:/trailer|cinematic|film|movie|teaser|promo/.test(p)};}
function momentText(m){return lower([m?.description,m?.reason,m?.action,m?.event,m?.purpose,m?.tags,m?.shotType,m?.composition,m?.subjectType].filter(Boolean).join(' '));}
function scoreMoment(m,role,profile){const s=momentText(m);let score=Number(m?.score??m?.confidence??50);const rule=ROLE_RULES[role];if(rule?.patterns.test(s))score+=25;for(const word of rule?.preferred||[])if(s.includes(word))score+=8;if(profile?.subjectType&&s.includes(lower(profile.subjectType)))score+=3;if(Number(m?.duration)>1)score+=3;return Math.max(0,Math.min(100,score));}
function candidateMoments(analysis){if(Array.isArray(analysis?.bestMoments))return analysis.bestMoments;if(Array.isArray(analysis?.cuts))return analysis.cuts;if(Array.isArray(analysis?.plan?.cuts))return analysis.plan.cuts;return[];}
function roleOrder(prompt){const m=mode(prompt);if(m.action)return['hook','establish','build','reveal','action','action','hero'];if(m.travel)return['hook','establish','build','reveal','emotion','hero'];if(m.emotion)return['hook','emotion','build','reveal','emotion','hero'];if(m.reveal)return['hook','establish','build','reveal','action','hero'];if(m.trailer)return['hook','establish','build','reveal','action','hero'];return['hook','establish','build','reveal','action','hero'];}
function readSubject(analysis){const s=analysis?.subject||{};return text(s.description)||text(s.primarySubject)||text(analysis?.primarySubject)||text(analysis?.subjectDescription)||text(analysis?.contentType)||'the uploaded subject';}
function readEnvironment(analysis){return text(analysis?.scene?.environment)||text(analysis?.environment)||text(analysis?.setting)||text(analysis?.sceneDescription)||'the source environment';}
function continuityProfile(analysis,subject,environment){const identity=analysis?.subject?.identity||analysis?.subject?.visualIdentity||analysis?.identity||subject;return{subjectIdentity:identity,environmentConsistency:environment,screenDirection:'preserve where observable',appearance:'preserve subject-defining attributes from source media',cameraContinuity:'match source perspective, scale, direction and movement where possible',lightingContinuity:'match source lighting direction, intensity and colour temperature where possible',avoid:['unexplained subject replacement','unmotivated environment jumps','geometry or appearance drift','generated details that contradict observed media']};}
export function buildUniversalProductionBlueprint(analysis={},creativePrompt='',options={}){
 const moments=candidateMoments(analysis);const profiles=analysis?.mediaProfile?.items||[];const roles=roleOrder(creativePrompt);const used=new Set();const selections=[];
 for(const role of roles){const ranked=moments.map((moment,index)=>({moment,index,score:scoreMoment(moment,role,profiles[Number(moment?.mediaIndex)||index])})).sort((a,b)=>b.score-a.score);const pick=ranked.find(item=>!used.has(item.index))||ranked[0];if(pick){used.add(pick.index);selections.push({role,momentIndex:pick.index,mediaIndex:Number.isInteger(Number(pick.moment?.mediaIndex))?Number(pick.moment.mediaIndex):null,score:Math.round(pick.score)});}}
 const subject=readSubject(analysis);const environment=readEnvironment(analysis);const requestedDuration=Math.max(5,Math.min(60,Number(options.targetDuration)||15));
 return{version:'universal-production-v2',subject,environment,creativeIntent:text(creativePrompt)||'Create a cinematic social video from the strongest available moments.',targetDuration:requestedDuration,storyArc:roles,selection:selections,continuity:continuityProfile(analysis,subject,environment),generationPolicy:{enabled:true,preferRealFootage:true,generatedContentMustSupportStory:true,preserveSubjectIdentity:true,subjectAgnostic:true,originalContentOnly:true},editLanguage:{camera:'intent-driven',motion:'subject-aware',transitions:'story-aware',speed:'emotion-and-action-aware',text:'minimal unless requested'},qualityGoals:['strong opening','clear narrative progression','visual variety','subject continuity','environment continuity','deliberate ending']};
}
export function describeBlueprint(blueprint){if(!blueprint)return'No production blueprint.';return`Universal production blueprint: ${blueprint.storyArc?.length||0} story roles • subject: ${blueprint.subject} • ${blueprint.targetDuration}s target • ${blueprint.selection?.length||0} selected moments • subject/environment continuity protected`;}
