/* Video Generation V2 — first-class generated timeline media. */
import { generateProceduralSceneVideo } from './proceduralSceneRendererV2.js';
const text=v=>String(v??'').trim(); const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a,b,f=a)=>Math.max(a,Math.min(b,n(v,f)));
export function createVideoGenerationRequest({type='text-to-video',prompt='',duration=3,aspectRatio='9:16',referenceAssets=[],subjectIds=[],camera='',motion='',lighting='',environment='',timelineRole='insert',sceneBlueprint=null}={}){const allowed=['text-to-video','image-to-video','subject-scene','infill','transition','establishing-shot','insert'];if(!allowed.includes(type))throw new Error(`Unsupported video generation type: ${type}`);return{version:'video-generation-request-v2',id:`video-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,type,prompt:text(prompt),duration:clamp(duration,.5,60,3),aspectRatio:['9:16','1:1','16:9'].includes(aspectRatio)?aspectRatio:'9:16',referenceAssets:Array.isArray(referenceAssets)?referenceAssets:[],subjectIds:Array.isArray(subjectIds)?subjectIds:[],direction:{camera:text(camera),motion:text(motion),lighting:text(lighting),environment:text(environment)},timelineRole,sceneBlueprint:sceneBlueprint||null,constraints:{preserveSubjectIdentity:subjectIds.length>0,originalOnly:true,noNamedStyleImitation:true},status:'queued'};}
export function buildScenePlan({brief,media=[],musicEvents=[],subjectManifest=null}={}){const b=brief||{},slots=[],duration=n(b.duration,15),events=Array.isArray(musicEvents)?musicEvents:[];if(duration>0)slots.push({role:'opening',start:0,duration:Math.min(2,duration),generation:'optional'});for(const e of events.filter(x=>x.type==='drop'))slots.push({role:'music-drop-insert',start:n(e.time),duration:Math.min(2,Math.max(.75,duration*.12)),generation:'preferred'});return{version:'scene-plan-v3',slots,mediaCount:Array.isArray(media)?media.length:0,subjectIds:(subjectManifest?.subjects||[]).map(s=>s.id),strategy:'use real media first; generate only where it improves story, continuity or impact',generationPolicy:{maxGeneratedInserts:4,preferSubjectReferences:true,proceduralFallback:true}};}
export function buildProceduralSceneRequest(sceneBlueprint,{width=1080,height=1920,fps=30}={}){if(!sceneBlueprint?.role)throw new Error('Procedural scene blueprint requires a role.');return{version:'procedural-scene-request-v2',id:`proc-${sceneBlueprint.id||Date.now()}`,width,height,fps,duration:clamp(sceneBlueprint.duration,.5,60,2),role:sceneBlueprint.role,direction:sceneBlueprint.direction||{},subjects:sceneBlueprint.subjects||{},continuity:sceneBlueprint.continuity||{},constraints:sceneBlueprint.constraints||{originalOnly:true},renderer:'browser-world-synthesis-v2',status:'queued'};}
export function buildVideoGenerationAdapter({generate,proceduralGenerate}={}){return{async generateScene(request,context={}){if(typeof generate==='function'){const result=await generate(request,context);if(result?.videoUrl||result?.videoBlob||result?.blob)return{...result,request,status:'ready',source:result.source||'model'};}
 const procedural=typeof proceduralGenerate==='function'?proceduralGenerate:async(sceneRequest)=>generateProceduralSceneVideo(sceneRequest,context);
 try{const result=await procedural(buildProceduralSceneRequest(request.sceneBlueprint||request),context);if(result?.videoUrl||result?.videoBlob||result?.blob)return{...result,request,status:'ready',source:result.source||'browser-procedural'};}catch(error){if(typeof proceduralGenerate==='function')throw error;return{request,status:'planned',source:'provider-agnostic-no-output',fallback:'browser-renderer',warning:error?.message||'Procedural browser video unavailable in this runtime.'};}
 return{request,status:'planned',source:'provider-agnostic-no-output',fallback:'browser-renderer'};}};}
