/* BIKEZTAGRAM AI — stable world compositor v8
   Keeps the public renderWorldScene API but removes the unstable high-frequency camera shake.
   The original v7 file is preserved on batch4-worldscene-v7-backup-2026-08-20.
*/
import { FilesetResolver, ImageSegmenter } from '@mediapipe/tasks-vision';

const MODEL_URL='https://storage.googleapis.com/mediapipe-models/image_segmenter/deeplab_v3/float32/1/deeplab_v3.tflite';
const MOTORBIKE_CLASS=14;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ease=v=>v<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2;
const noise=n=>{const x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x)};
function modeFor(prompt=''){const p=String(prompt).toLowerCase();if(/mars|red planet|martian/.test(p))return'mars';if(/neon|cyber|future|futuristic|sci-fi|city|street|night city/.test(p))return'neon';if(/drone|pursuit|chase|military/.test(p))return'drone';if(/desert|dust|sand/.test(p))return'desert';if(/space|galaxy|cosmic|stars/.test(p))return'space';return'world'}
function palette(m){if(m==='mars')return['#120407','#5b1714','#32130f','255,105,55'];if(m==='desert')return['#0d1720','#75462a','#3b281d','255,184,92'];if(m==='space')return['#010208','#0a1021','#080914','115,130,255'];if(m==='neon'||m==='drone')return['#01040a','#092239','#03070d','45,205,255'];return['#02070d','#123043','#101a20','75,190,230']}
function background(ctx,w,h,m,t){const [a,b,g,glow]=palette(m);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,a);sky.addColorStop(1,b);ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);const sun=ctx.createRadialGradient(w*(.5+Math.sin(t*.18)*.12),h*.24,2,w*.5,h*.24,h*.42);sun.addColorStop(0,`rgba(${glow},.25)`);sun.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=sun;ctx.fillRect(0,0,w,h);if(m==='space'){for(let i=0;i<140;i++){ctx.fillStyle=`rgba(255,255,255,${.2+noise(i+90)*.7})`;const s=.6+noise(i)*2;ctx.fillRect(noise(i*3)*w,noise(i*7)*h*.6,s,s)}}const horizon=h*.56;ctx.fillStyle=g;ctx.fillRect(0,horizon,w,h-horizon);if(m!=='space'){ctx.save();ctx.globalAlpha=.18;ctx.strokeStyle=m==='mars'?'#ff8b4d':'#54dfff';ctx.lineWidth=2;for(let i=-8;i<=8;i++){ctx.beginPath();ctx.moveTo(w*.5+i*5,horizon);ctx.lineTo(w*.5+i*w*.18,h);ctx.stroke()}for(let i=1;i<10;i++){const q=i/10,y=horizon+Math.pow(q,1.8)*(h-horizon);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}}
function city(ctx,w,h,t,m){if(m!=='neon'&&m!=='drone')return;const horizon=h*.53;for(let depth=0;depth<2;depth++){const count=depth?18:24;for(let i=0;i<count;i++){const s=i+depth*100;const bw=45+noise(s)*100,bh=80+noise(s+8)*330,x=((i/count)*w+Math.sin(t*(.16+depth*.12)+s)*15+w)%(w+bw)-bw/2;ctx.fillStyle=depth?'rgba(8,19,31,.84)':'rgba(2,9,17,.96)';ctx.fillRect(x,horizon-bh,bw,bh);for(let r=0;r<5;r++)if(noise(s+r*11)>.45){ctx.fillStyle=r%2?'rgba(40,205,255,.32)':'rgba(255,188,90,.30)';ctx.fillRect(x+10+noise(s+r)*bw*.65,horizon-bh+18+r*bh*.15,5,10)}}}}
function atmosphere(ctx,w,h,m,t,prompt){const p=String(prompt).toLowerCase();if(/rain|storm|wet|night/.test(p)){ctx.save();ctx.globalAlpha=.18;ctx.strokeStyle='#c8e7ff';for(let i=0;i<70;i++){const x=noise(i*2)*w,y=(noise(i+8)*h+t*520)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-12,y+40);ctx.stroke()}ctx.restore()}if(m==='mars'||m==='desert'){ctx.save();ctx.globalAlpha=.08;ctx.fillStyle=m==='mars'?'#ff9150':'#ffd796';for(let i=0;i<70;i++)ctx.fillRect((noise(i)*w+t*25)%w,h*(.45+noise(i+5)*.45),2,2);ctx.restore()}if(m==='drone'){ctx.save();for(let i=0;i<3;i++){const x=w*(.18+i*.32)+Math.sin(t*(1.5+i))*35,y=h*(.18+(i%2)*.1);ctx.fillStyle='rgba(3,7,12,.95)';ctx.fillRect(x-26,y-6,52,12);ctx.fillStyle=i===1?'rgba(255,55,65,.9)':'rgba(55,220,255,.9)';ctx.fillRect(x-15,y+7,8,3);ctx.fillRect(x+7,y+7,8,3)}ctx.restore()}}
async function loadVideo(source){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.crossOrigin=source.remote?'anonymous':'';v.src=source.url;v.load();await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Timed out loading source for world scene.')),12000);const done=e=>{clearTimeout(timer);v.removeEventListener('loadedmetadata',meta);v.removeEventListener('error',err);e?reject(e):resolve()};const meta=()=>v.videoWidth&&done();const err=()=>done(new Error(`Could not decode source (MediaError ${v.error?.code??'unknown'}).`));v.addEventListener('loadedmetadata',meta);v.addEventListener('error',err)});return v}
function maskCanvas(result){const confidence=result.confidenceMasks?.[MOTORBIKE_CLASS];if(!confidence)return null;const values=confidence.getAsFloat32Array(),w=confidence.width,h=confidence.height,c=document.createElement('canvas');c.width=w;c.height=h;const out=c.getContext('2d'),img=new ImageData(w,h);let count=0;for(let i=0;i<values.length;i++){const a=values[i]>.48?Math.round(clamp((values[i]-.48)/.52*255,0,255)):0;if(a)count++;const j=i*4;img.data[j]=img.data[j+1]=img.data[j+2]=255;img.data[j+3]=a}if(!count)return null;out.putImageData(img,0,0);return c}
async function makeSegmenter(){const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');return ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL_URL,delegate:'CPU'},runningMode:'IMAGE',outputCategoryMask:false,outputConfidenceMasks:true})}
async function seek(v,time){return new Promise(resolve=>{const target=clamp(time,0,Math.max(0,v.duration-.05));if(Math.abs(v.currentTime-target)<.03){resolve();return}const done=()=>{v.removeEventListener('seeked',done);resolve()};v.addEventListener('seeked',done,{once:true});v.currentTime=target})}
function drawSubject(ctx,source,mask,w,h,scale,x,y,grade='rgba(255,255,255,.98)'){ctx.save();ctx.translate(w/2+x,h/2+y);ctx.scale(scale,scale);ctx.translate(-w/2,-h/2);ctx.filter=grade;ctx.drawImage(source,0,0,w,h);ctx.filter='none';if(mask){ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0,w,h)}ctx.restore()}
function grade(ctx,w,h,m){const [, , ,glow]=palette(m);ctx.save();ctx.globalCompositeOperation='soft-light';ctx.fillStyle=`rgba(${glow},.06)`;ctx.fillRect(0,0,w,h);ctx.restore();const v=ctx.createRadialGradient(w*.5,h*.45,h*.1,w*.5,h*.45,h*.8);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.68)');ctx.fillStyle=v;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(0,0,w,24);ctx.fillRect(0,h-24,w,24)}

export async function renderWorldScene({file,sourceUrl,prompt='',duration=8,onProgress}){
 const source=sourceUrl?{url:sourceUrl,remote:true}:{url:URL.createObjectURL(file),remote:false};
 try{const video=await loadVideo(source),w=1080,h=1920,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Could not create world-scene canvas.');
  const sourceCanvas=document.createElement('canvas');sourceCanvas.width=video.videoWidth;sourceCanvas.height=video.videoHeight;const sctx=sourceCanvas.getContext('2d');let masks=[];try{const seg=await makeSegmenter();for(const fraction of [.1,.5,.9]){await seek(video,video.duration*fraction);sctx.drawImage(video,0,0,sourceCanvas.width,sourceCanvas.height);const mask=maskCanvas(await seg.segment(sourceCanvas));if(mask)masks.push({fraction,mask})}seg.close()}catch(error){console.warn('[Bikeztagram] Subject matte unavailable; using full-frame source.',error)}
  const sourceRatio=video.videoWidth/video.videoHeight,targetRatio=w/h;let dw,dh;if(sourceRatio>targetRatio){dh=h*1.06;dw=dh*sourceRatio}else{dw=w*1.06;dh=dw/sourceRatio}const sx=(w-dw)/2,sy=(h-dh)/2;const mode=modeFor(prompt);const stream=canvas.captureStream(30);const types=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4;codecs=h264','video/mp4'];const type=types.find(x=>MediaRecorder.isTypeSupported(x))||'';const recorder=type?new MediaRecorder(stream,{mimeType:type}):new MediaRecorder(stream);const chunks=[];const stopped=new Promise((resolve,reject)=>{recorder.ondataavailable=e=>e.data?.size&&chunks.push(e.data);recorder.onerror=e=>reject(e.error||new Error('World scene recorder failed.'));recorder.onstop=()=>chunks.length?resolve(new Blob(chunks,{type:chunks[0].type||type||'video/webm'})):reject(new Error('World scene produced no video data.'))});
  await seek(video,0);video.playbackRate=1;try{await video.play()}catch{}
  recorder.start(500);const durationMs=Math.max(.5,Number(duration)||8)*1000,started=performance.now();let lastFrame=-1;
  await new Promise(resolve=>{const frame=now=>{const elapsed=Math.min(durationMs,Math.max(0,now-started)),t=elapsed/durationMs;if(Math.floor(elapsed*30)!==lastFrame){lastFrame=Math.floor(elapsed*30);const story=t<.34?0:t<.70?1:2,q=story===0?clamp(t/.34,0,1):story===1?clamp((t-.34)/.36,0,1):clamp((t-.70)/.30,0,1),e=ease(q);const cameraScale=story===0?1.07+e*.06:story===1?1.12+Math.sin(q*Math.PI)*.05:1.18-e*.08;const x=story===0?-w*.025*e:story===1?Math.sin(q*Math.PI)*w*.035:w*.03*e;const y=story===1?Math.sin(q*Math.PI)*h*.012:story===2?-h*.018*e:0;ctx.clearRect(0,0,w,h);background(ctx,w,h,mode,t);city(ctx,w,h,t,mode);sctx.drawImage(video,0,0,sourceCanvas.width,sourceCanvas.height);const ratio=sourceCanvas.width/sourceCanvas.height;let fdw,fdh;if(ratio>w/h){fdh=h*1.06;fdw=fdh*ratio}else{fdw=w*1.06;fdh=fdw/ratio}const fdx=(w-fdw)/2,fdy=(h-fdh)/2;const foreground=document.createElement('canvas');foreground.width=w;foreground.height=h;const f=foreground.getContext('2d');f.filter='brightness(.86) contrast(1.14) saturate(1.08)';f.drawImage(sourceCanvas,fdx,fdy,fdw,fdh);f.filter='none';if(masks.length){const current=video.currentTime/Math.max(.001,video.duration);let chosen=masks[0],best=Infinity;for(const item of masks){const d=Math.abs(item.fraction-current);if(d<best){best=d;chosen=item}}f.globalCompositeOperation='destination-in';f.drawImage(chosen.mask,fdx,fdy,fdw,fdh);f.globalCompositeOperation='source-over'}ctx.save();ctx.translate(w/2+x,h/2+y);ctx.scale(cameraScale,cameraScale);ctx.translate(-w/2,-h/2);ctx.drawImage(foreground,0,0);ctx.restore();atmosphere(ctx,w,h,mode,t,prompt);grade(ctx,w,h,mode);onProgress?.(Math.round(t*100))}if(elapsed>=durationMs){resolve();return}requestAnimationFrame(frame)};requestAnimationFrame(frame)});
  recorder.stop();return await stopped;
 }finally{if(!sourceUrl){try{URL.revokeObjectURL(source.url)}catch{}}}}
