import { GoogleGenAI, createUserContent, createPartFromUri } from '@google/genai';
const text=(v)=>String(v??'').trim(); const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||min)); const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
function buildPrompt(prompt,items,targetDuration){return `You are Stage 1 + Stage 2 of a GENERAL-PURPOSE AI FILMMAKER.

You have a SOURCE LIBRARY containing multiple uploaded images and/or videos. Analyse the ACTUAL supplied media together, then direct one coherent social-media film from the strongest verified material.

The subject may be anything: motorcycle, car, person, puppy, animal, travel, landscape, product, event, architecture, food, object, mixed media or something else. Do not assume the subject from filenames.

SOURCE LIBRARY:
${items.map((item,i)=>`${i}: ${item.filename} (${item.mediaType})`).join('\n')}

USER CREATIVE REQUEST:
${text(prompt)||'Create the strongest cinematic social-media film from this source library.'}

TARGET DURATION: ${clamp(targetDuration,5,60)} seconds

RULES:
- Only use moments actually verified in the supplied media.
- Never invent actions, objects, locations, identities or visual details.
- Select across different source files when that improves story, variety and continuity.
- Never repeat the same exact moment.
- Prefer hook → build → reveal/action/emotion → hero where supported.
- Every selected video moment must have precise sourceIndex, startTime and endTime.
- Images use startTime=0 and endTime=0.
- Keep cuts 0.5–4 seconds.
- Return 3–8 cuts when enough material exists.
- Preserve subject identity and continuity.
- Motorcycles are not a special case.
- For each supplied VIDEO source, if spoken dialogue is actually audible, return short time-coded speech cues in that source's speechCues array. Do not invent speech, do not include lyrics from music, and use an empty array when no reliable speech is present.
- Speech cue times are relative to the ORIGINAL SOURCE VIDEO, not the finished edit timeline.

Return ONLY valid JSON:
{
  "title":"","style":"","colorGrade":"","editorialStructure":["hook","build","reveal","action","hero"],
  "subject":{"primarySubject":"","category":"","identity":"","confidence":0},"librarySummary":"",
  "sourceLibrary":[{"sourceIndex":0,"filename":"","mediaType":"","role":"","cinematicScore":0,"verifiedMoments":[{"startTime":0,"endTime":0,"description":"","editorialRole":"","score":0}],"speechCues":[{"start":0,"end":1,"text":"","confidence":0.9}]}],
  "cuts":[{"sourceIndex":0,"startTime":0,"endTime":2,"duration":2,"purpose":"hook","transition":"fade-in","motionStyle":"static","speed":1,"text":""}],
  "continuityNotes":"","avoid":""
}`;}
function validate(plan,count,targetDuration){if(!plan||!Array.isArray(plan.cuts))return null;const transitions=new Set(['hard-cut','fade-in','fade-out','dip-black','crossfade']);const motions=new Set(['static','slow-push','slow-pull','pan-left','pan-right','tilt-up','tilt-down']);const seen=new Set();const cuts=plan.cuts.map(c=>{const sourceIndex=Number(c?.sourceIndex);if(!Number.isInteger(sourceIndex)||sourceIndex<0||sourceIndex>=count)return null;const start=Math.max(0,Number(c?.startTime)||0);const endRaw=Number(c?.endTime);const end=Number.isFinite(endRaw)?Math.max(start+.1,endRaw):start+.1;const duration=clamp(c?.duration,.5,4);const key=`${sourceIndex}:${Math.round(start*10)}:${Math.round(end*10)}`;if(seen.has(key))return null;seen.add(key);return{sourceIndex,startTime:Number(start.toFixed(2)),endTime:Number(end.toFixed(2)),duration:Number(duration.toFixed(2)),purpose:text(c?.purpose)||'cinematic',transition:transitions.has(text(c?.transition))?text(c.transition):'hard-cut',motionStyle:motions.has(text(c?.motionStyle))?text(c.motionStyle):'static',speed:Math.max(.5,Math.min(1.5,Number(c?.speed)||1)),text:text(c?.text)}}).filter(Boolean).slice(0,8);if(!cuts.length)return null;const sourceLibrary=Array.isArray(plan.sourceLibrary)?plan.sourceLibrary.map((source,index)=>({...source,sourceIndex:Number.isInteger(Number(source?.sourceIndex))?Number(source.sourceIndex):index,speechCues:Array.isArray(source?.speechCues)?source.speechCues.map(c=>({start:Math.max(0,Number(c?.start)||0),end:Math.max(Math.max(0,Number(c?.start)||0)+.05,Number(c?.end)||0),text:text(c?.text),confidence:Math.max(0,Math.min(1,Number(c?.confidence)||0))})).filter(c=>c.text).slice(0,120):[]})):[];return{title:text(plan.title)||'Universal AI Film',style:text(plan.style)||'cinematic',colorGrade:text(plan.colorGrade)||'cinematic',editorialStructure:Array.isArray(plan.editorialStructure)?plan.editorialStructure.map(text).filter(Boolean).slice(0,8):[],subject:plan.subject||{},librarySummary:text(plan.librarySummary),sourceLibrary, cuts,continuityNotes:text(plan.continuityNotes),avoid:text(plan.avoid),targetDuration:clamp(targetDuration,5,60),stage:'multi-media-gemini-director'};}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});try{const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(500).json({success:false,error:'GEMINI_API_KEY is missing.'});const{items=[],prompt='',targetDuration=15}=req.body||{};if(!Array.isArray(items)||!items.length)return res.status(400).json({success:false,error:'No media library items were supplied.'});if(items.length>12)return res.status(400).json({success:false,error:'Maximum source-library size is 12 media files per analysis.'});const ai=new GoogleGenAI({apiKey});const parts=[];const normalized=[];for(let i=0;i<items.length;i++){const item=items[i]||{};const url=text(item.url);const mimeType=text(item.mimeType)||'application/octet-stream';if(!url)throw new Error(`Source ${i+1} has no Blob URL.`);if(!mimeType.startsWith('image/')&&!mimeType.startsWith('video/'))throw new Error(`Source ${i+1} has unsupported MIME type: ${mimeType}`);const response=await fetch(url);if(!response.ok)throw new Error(`Could not download source ${i+1}. HTTP ${response.status}`);const contentType=response.headers.get('content-type')||mimeType;const bytes=Buffer.from(await response.arrayBuffer());if(!bytes.length)throw new Error(`Source ${i+1} downloaded empty.`);const file=await ai.files.upload({file:new Blob([bytes],{type:contentType}),config:{mimeType:contentType,displayName:text(item.filename)||`source-${i}`}});if(!file?.uri||!file?.name)throw new Error(`Gemini did not return a valid file for source ${i+1}.`);if(contentType.startsWith('video/')){for(let attempt=0;attempt<60;attempt++){const state=String(file?.state||'').toUpperCase();if(state==='ACTIVE')break;if(state==='FAILED')throw new Error(`Gemini failed while processing source ${i+1}.`);await sleep(1500);Object.assign(file,await ai.files.get({name:file.name}));}if(String(file?.state||'').toUpperCase()!=='ACTIVE')throw new Error(`Gemini timed out processing source ${i+1}.`);}parts.push(createPartFromUri(file.uri,file.mimeType||contentType));normalized.push({sourceIndex:i,filename:text(item.filename)||`source-${i}`,mediaType:contentType.startsWith('image/')?'image':'video',mimeType:contentType});}
const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:createUserContent([...parts,buildPrompt(prompt,normalized,targetDuration)]),config:{responseMimeType:'application/json'}});const raw=text(response?.text).replace(/```json/gi,'').replace(/```/g,'').trim();if(!raw)throw new Error('Gemini returned no mixed-media analysis.');let parsed;try{parsed=JSON.parse(raw);}catch{throw new Error('Gemini returned invalid mixed-media JSON.');}const plan=validate(parsed,normalized.length,targetDuration);if(!plan)throw new Error('Gemini returned no valid mixed-media edit plan.');const analysis={mediaType:'mixed-media-library',sourceCount:normalized.length,sources:normalized,subject:plan.subject,librarySummary:plan.librarySummary,sourceLibrary:plan.sourceLibrary,continuityNotes:plan.continuityNotes,avoid:plan.avoid,cinematicScore:Math.round(plan.sourceLibrary.reduce((sum,s)=>sum+(Number(s.cinematicScore)||0),0)/Math.max(1,plan.sourceLibrary.length)),directorPipeline:{stages:['actual-multi-media-analysis','verified-multi-source-edit-direction','verified-source-speech-cues'],stage1:'gemini-3.6-flash-multimedia',stage2:'gemini-3.6-flash-multimedia-director',sourceOfTruth:'uploaded-media',architecture:'universal-ai-filmmaker'}};return res.status(200).json({success:true,analysis,aiEditPlan:plan});}catch(error){console.error('[ANALYSE-LIBRARY]',error?.message||error);return res.status(500).json({success:false,error:error?.message||'Unknown mixed-media analysis error.'});}}
