/* BIKEZTAGRAM AI — universal production-plan bridge.
   Product layer only. Upload/Gemini authentication and rendering infrastructure remain untouched.
   The endpoint turns real-media analysis + creative intent into a subject-agnostic production plan.
*/
import { buildSoundtrackBrief } from '../src/musicDirector.js';
import { attachSoundtrackToPlan } from '../src/beatAwareTimeline.js';
function clamp(value,min,max){return Math.max(min,Math.min(max,Number(value)||min));}
function text(value){return String(value||'').trim();}
function allBestMoments(analysis){return(Array.isArray(analysis?.bestMoments)?analysis.bestMoments:[]).filter(m=>m&&m.start!=null&&m.end!=null).map(m=>({start:Number(m.start),end:Number(m.end),description:text(m.description),score:Number(m.score||0)})).filter(m=>Number.isFinite(m.start)&&Number.isFinite(m.end)&&m.end>m.start).sort((a,b)=>(b.score||0)-(a.score||0));}
function subjectOf(analysis){const s=analysis?.subject||{};return text(s.description)||text(s.primarySubject)||text(analysis?.primarySubject)||text(analysis?.subjectDescription)||text(analysis?.contentType)||'the uploaded subject';}
function environmentOf(analysis){return text(analysis?.scene?.environment)||text(analysis?.environment)||text(analysis?.setting)||text(analysis?.sceneDescription)||'the source environment';}
function detectStyle(prompt){const p=text(prompt).toLowerCase();return{action:/action|race|chase|pursuit|fast|speed|aggressive|energetic/.test(p),trailer:/trailer|blockbuster|movie|cinematic|epic|teaser/.test(p),dark:/dark|moody|night|dramatic|noir/.test(p),emotion:/emotional|romantic|beautiful|nostalgic|heartfelt|cute|joy|calm/.test(p),travel:/travel|journey|holiday|explore|destination|landscape/.test(p)};}
function generatedPrompt({creativeRequest,subject,environment,style,purpose}){const direction=[style.action?'dynamic movement and camera energy':'controlled cinematic movement',style.trailer?'premium cinematic trailer photography':'cinematic social-video photography',style.dark?'dramatic low-key atmosphere':'natural cinematic lighting',style.emotion?'emotionally expressive visual pacing':'clear visual storytelling'].join(', ');return[`Create ORIGINAL visual material that supports ${subject} within ${environment}.`,`Purpose: ${purpose}.`,`User creative request: ${creativeRequest}.`,`Visual direction: ${direction}.`,'Preserve the source subject identity, appearance, proportions and observable motion; match perspective, scale, screen direction, lighting and environment continuity to the supplied media where applicable.','Generate original material only; do not reproduce copyrighted characters, logos, vehicles, scenes, dialogue or soundtrack from a named franchise.'].join(' ');}
function uploadedScene(id,purpose,start,end,description,transitionIn,transitionOut,priority='required'){return{id,sourceType:'uploaded',purpose,duration:Number(Math.max(.5,end-start).toFixed(2)),startTime:Number(start.toFixed(2)),endTime:Number(end.toFixed(2)),generationPrompt:'',continuityNotes:description||'Use the real supplied footage as the authoritative source.',transitionIn,transitionOut,priority};}
function generatedScene(id,purpose,duration,prompt,transitionIn,transitionOut,priority='required'){return{id,sourceType:'generated',purpose,duration:Number(duration.toFixed(2)),startTime:null,endTime:null,generationPrompt:prompt,continuityNotes:'Original generated material must support the real subject, story and continuity; it must not silently replace source identity.',transitionIn,transitionOut,priority};}
function buildScenes(analysis,creativeRequest,targetDuration){const sourceDuration=clamp(Number(analysis?.durationInSeconds)||11,3,60);const target=clamp(Number(targetDuration)||15,5,60);const moments=allBestMoments(analysis);const best=moments[0]||null;const second=moments.find(m=>!best||Math.abs(m.start-best.start)>1);const subject=subjectOf(analysis);const environment=environmentOf(analysis);const style=detectStyle(creativeRequest);const scenes=[];const opening=Math.min(2.2,sourceDuration);scenes.push(uploadedScene('scene-01','real-opening',0,opening,`Establish ${subject} and its authentic camera movement.`,'fade-in','cinematic-blend'));scenes.push(generatedScene('scene-02','generated-world-establishing',Math.min(2.2,Math.max(1.5,target*.14)),generatedPrompt({creativeRequest,subject,environment,style,purpose:'Establish the requested world, scale, atmosphere and direction before the main story beat.'}),'cinematic-blend','match-cut'));if(best){const start=clamp(best.start,0,Math.max(0,sourceDuration-.5));const end=clamp(best.end,start+.5,sourceDuration);scenes.push(uploadedScene('scene-03','real-primary-moment',start,end,best.description||'Use the strongest analysed source moment.','match-cut','action-blend'));}scenes.push(generatedScene('scene-04',style.action?'generated-action-fill':'generated-story-fill',Math.min(3.2,Math.max(1.8,target*(style.action?.22:.16))),generatedPrompt({creativeRequest,subject,environment,style,purpose:style.action?'Bridge the real footage with an original action continuation.':'Extend the story or environment where the real footage has a narrative gap.'}),'action-blend','impact-cut'));if(second){const start=clamp(second.start,0,Math.max(0,sourceDuration-.5));const end=clamp(second.end,start+.5,sourceDuration);scenes.push(uploadedScene('scene-05','real-secondary-moment',start,end,second.description||'Use a distinct analysed source moment for visual variety.','impact-cut','hero-rise','recommended'));}scenes.push(generatedScene('scene-06','generated-hero-ending',Math.min(2.4,Math.max(1.5,target*.14)),generatedPrompt({creativeRequest,subject,environment,style,purpose:'Finish with a memorable original hero image or movement beat while preserving the source subject as the identity anchor.'}),'hero-rise','fade-out'));let total=scenes.reduce((sum,s)=>sum+s.duration,0);if(total>target){for(let i=scenes.length-1;i>=0&&total>target;i--){const s=scenes[i];const minimum=s.priority==='required'?.8:.6;const reduction=Math.min(Math.max(0,s.duration-minimum),total-target);s.duration=Number((s.duration-reduction).toFixed(2));total-=reduction;}}return{scenes,totalDuration:Number(total.toFixed(2)),style};}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});try{const{prompt='',analysis={},targetDuration=15}=req.body||{};if(!analysis||typeof analysis!=='object')return res.status(400).json({success:false,error:'Video analysis is required.'});const creativeRequest=text(prompt)||'Create a cinematic social-media video from the supplied media.';const requestedDuration=clamp(Number(targetDuration)||15,5,60);const subject=subjectOf(analysis);const environment=environmentOf(analysis);const built=buildScenes(analysis,creativeRequest,requestedDuration);const soundtrack=buildSoundtrackBrief({prompt:creativeRequest,duration:requestedDuration});const basePlan={version:'8.2',title:'AI Director — Universal Production + Beat-Aware Soundtrack',creativeRequest,creativeDirection:`Turn the supplied ${subject} media into an original cinematic production driven by the user's creative request.`,subject,environment,targetDuration:requestedDuration,plannedDuration:built.totalDuration,style:built.style,sourceAnalysis:{filename:text(analysis?.filename),durationSeconds:Number(analysis?.durationInSeconds||0),strongestMoments:allBestMoments(analysis).slice(0,5)},continuity:{subjectIdentity:analysis?.subject?.identity||analysis?.subject?.visualIdentity||subject,environmentConsistency:environment,screenDirection:'preserve where observable',appearance:'preserve source-defining attributes',camera:'match source perspective, scale and movement',lighting:'match source lighting where possible'},music:{...soundtrack,enabled:true,role:'editorial-timing'},scenes:built.scenes,generationPolicy:{engine:'bikeztagram-local-browser-compositor',paidVideoGeneration:false,externalVideoGenerator:false,useGeneratedFill:true,subjectAgnostic:true,preserveSubjectIdentity:true,generatedContentMustSupportStory:true,originalContentOnly:true},assemblyNotes:['Use real uploaded media as the identity anchor.','Use generated scenes only to support creative intent and fill genuine narrative or environmental gaps.','Match generated material to observable subject, camera, environment, lighting and motion continuity.','Use deliberate transitions and pacing rather than unrelated clip stitching.','Align editorial events to the soundtrack beat grid where practical.','Keep Blob, Gemini, upload and render infrastructure outside this product-layer change.']};const productionPlan=attachSoundtrackToPlan(basePlan,soundtrack);return res.status(200).json({success:true,productionPlan});}catch(error){console.error('[PRODUCTION-PLAN] ERROR',error);return res.status(500).json({success:false,error:error?.message||'Failed to build production plan.'});}}
